# GENERATED by scripts/gen-types.mjs from schemas/ in github.com/troothllc/trooth-cli.
# Do not edit by hand: change the schema and run `node scripts/gen-types.mjs`.
"""Pydantic v2 models for the documents Trooth publishes about a witness statement."""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class CorrectionPayload(BaseModel):
    "The JSON a trooth.correction.v1 payload holds: Trooth withdrawing or replacing a statement it signed. Signed like a v3 statement (RFC 8785 bytes, Ed25519, the signer inside the signed bytes) and entered in the witness statement log. The statement it corrects stays in the log; nothing is deleted."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    statement: Literal["trooth.correction.v1"] = Field(..., description="The payload type.")
    correction_id: str = Field(..., description="An identifier for this correction, unique in the log.")
    supersedes: str = Field(..., description="The statement id this correction withdraws or replaces. It must already be in the log.")
    subject_id: str = Field(..., description="The subject of the statement it corrects.")
    effect: Literal["withdrawn", "replaced"] = Field(..., description="withdrawn: no statement takes its place. replaced: the replacement statement does.")
    replacement: Optional[str] = Field(..., description="The replacing statement id, which must already be in the log; null for withdrawn.")
    reason: CorrectionReason = Field(..., description="Why.")
    issued_at: str = Field(..., description="When Trooth issued it, as Trooth asserts. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    signer: Signer = Field(..., description="The signing key, inside the signed bytes.")

class CorrectionReason(BaseModel):
    "The reason for a correction."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    code: Literal["evaluator_defect", "mapping_defect", "source_misread", "signing_key_compromised", "dispute_upheld", "withdrawn_by_trooth"] = Field(..., description="evaluator_defect: the evaluator read wrongly. mapping_defect: the check mapping was wrong. source_misread: a source was misread. signing_key_compromised: the key that signed it is compromised. dispute_upheld: a dispute about the reading was upheld. withdrawn_by_trooth: withdrawn for another stated reason.")
    explanation: str = Field(..., description="The reason in words, 10 to 1000 characters.")

class ManifestEntry(BaseModel):
    "One check and the evidence behind it: a public `source`, or a `commitment` to a private one. Exactly one of the two."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    check_id: str = Field(..., description="The check id. Unique in the manifest.")
    source: Optional[str] = Field(None, description="The public URL the check read.")
    commitment: Optional[str] = Field(None, description="`sha256:` plus the hex SHA-256 of salt, a newline byte and the private reference. Only its holder can open it.")

class KeyList(BaseModel):
    "The body of https://api.trooth.co/public/keys, or a saved copy of it. Save it with the time you read it: a saved list cannot show a compromise announced later."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    keys: List[PublicKey] = Field(..., description="Every key, current and past.")
    list_read_at: Optional[str] = Field(None, description="When the list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    active_kid: Optional[str] = Field(None, description="The kid of the key currently used for new statements.")
    note: Optional[str] = Field(None, description="A note from the key service.")

class PublicKey(BaseModel):
    "One published key and its lifecycle. Only `kid`, `alg`, `encoding`, `public_key`, `status` and the three lifecycle times decide trust (docs/VERIFY.md section 3)."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    kid: str = Field(..., description="The key id a statement names in key_id.")
    alg: Literal["Ed25519"] = Field(..., description="Always Ed25519.")
    encoding: Optional[Literal["hex", "base64"]] = Field(None, description="How public_key is written: hex or base64.")
    public_key: str = Field(..., description="The 32-byte Ed25519 public key, in `encoding`.")
    status: Literal["active", "retired", "revoked", "compromised"] = Field(..., description="active, retired, revoked or compromised.")
    state: Optional[str] = Field(None, description="The same lifecycle state as written by the key service.")
    retired_at: Optional[str] = Field(None, description="When the key was retired. Statements carrying a read_at strictly before this stay trusted. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    compromised_at: Optional[str] = Field(None, description="When the key was found compromised. Nothing signed by it is relied on. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    revoked_at: Optional[str] = Field(None, description="When the key was revoked. A revocation with no compromise recorded is treated as a compromise. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    created_at: Optional[str] = Field(None, description="When the key was created, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    activated_at: Optional[str] = Field(None, description="When the key was first used, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    first_listed_at: Optional[str] = Field(None, description="When the key first appeared on the list. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    fingerprint: Optional[str] = Field(None, description="A short fingerprint of the key, for display.")
    purpose: Optional[str] = Field(None, description="What the key is for, as a short label.")
    signs: Optional[str] = Field(None, description="What the key signs, in words.")
    events: Optional[List[KeyEvent]] = Field(None, description="Lifecycle events, oldest first.")

class KeyEvent(BaseModel):
    "One lifecycle event of a key."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    event: str = Field(..., description="What happened (for example first_listed, retired, compromised).")
    at: str = Field(..., description="When. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    note: Optional[str] = Field(None, description="A note, or null.")

class LogReceipt(BaseModel):
    "A receipt from Trooth's witness statement log (docs/LOG.md): the entry index, a checkpoint signed by the log key, and an RFC 9162 inclusion proof from the entry to the checkpoint root. The entry is RFC 8785 JSON of {kind, statement}; its leaf hash is SHA-256(0x00 || entry)."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    log: Literal["trooth.co/witness-log/v1"] = Field(..., description="The log origin, which the checkpoint must also name.")
    index: int = Field(..., description="The zero-based entry index.")
    tree_size: int = Field(..., description="The size of the signed tree the proof is against. Equals the checkpoint size.")
    root_hash: str = Field(..., description="Standard base64 of the 32-byte root at tree_size. Equals the checkpoint root.")
    inclusion_proof: List[str] = Field(..., description="The RFC 9162 audit path, leaf to root, each a 32-byte hash in standard base64.")
    checkpoint: str = Field(..., description="A C2SP checkpoint (origin, size, base64 root, each on its own line) followed by a blank line and C2SP signed-note signature lines; the log key's line is an em dash, the key name and base64 of the 4-byte key hash and the 64-byte Ed25519 signature.")

class PublicRecordStatement(BaseModel):
    "The payload Trooth signs for a public record reading: it names the reading by the SHA-256 of its RFC 8785 bytes. Carried as the `payload` of a witness-statement envelope (RFC 8785, Ed25519) under `signed.statement` in a reading, and logged as a public_record entry. The signature says what Trooth read and when, not that what the sources say is true."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    statement: Literal["trooth.public-record.v1"] = Field(..., description="The payload type.")
    subject_id: str = Field(..., description="trooth:domain:<domain>.")
    domain: str = Field(..., description="The domain read.")
    read_at: str = Field(..., description="The reading's read_at. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    record_sha256: str = Field(..., description="SHA-256, hex, of the reading's RFC 8785 bytes without `signed`.")
    record_canonicalization: Literal["RFC8785"] = Field(..., description="How those bytes were made.")
    entity_id: Optional[str] = Field(..., description="The reading's entity id, or null.")
    bindings: List[BindingStatus] = Field(..., description="Each binding's id and status.")
    sources: int = Field(..., description="How many responses the reading read.")
    issued_at: str = Field(..., description="When the statement was signed. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    signer: StatementSigner = Field(..., description="The signing key, inside the signed bytes.")

class BindingStatus(BaseModel):
    "A binding as the statement names it."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str = Field(..., description="trooth:cik or trooth:lei id.")
    status: str = Field(..., description="The binding status.")

class StatementSigner(BaseModel):
    "The signing key."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    key_id: str = Field(..., description="The kid on https://api.trooth.co/public/keys.")
    issuer: Literal["trooth.co"] = Field(..., description="Always trooth.co.")

class PublicRecordReading(BaseModel):
    "What a company has published outside its own website, read from the authorities that hold it (SEC EDGAR, the GLEIF LEI registry, DNS, a Certificate Transparency monitor, the OFAC list), beside what its own site states, and the evidence tying each identifier to the domain. Served at https://api.trooth.co/scan/public-record/<domain>. Every fact carries the URL to read it again. Since trooth 0.11.0 each reading also carries `signed`: a statement naming the SHA-256 of the reading's RFC 8785 bytes (everything except `signed`), signed with Trooth's statement key and logged. Nothing in it grades, rates or ranks a company. docs/EVIDENCE.md in trooth-cli is the normative text."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    format: Literal["trooth.public-record.v1"] = Field(..., description="The format.")
    domain: str = Field(..., description="The domain read.")
    subject_id: str = Field(..., description="trooth:domain:<domain>.")
    read_at: str = Field(..., description="When Trooth read the sources. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    site: SiteRead = Field(..., description="What the company's own pages say about which legal entity it is.")
    bindings: List[EntityBinding] = Field(..., description="Each identifier found and the evidence for and against tying it to the domain.")
    sec: Optional[SecRecord] = Field(..., description="The SEC filer's record, or null when no filer was identified.")
    lei: Optional[LeiRecord] = Field(..., description="The LEI record, or null when none was identified.")
    dns: List[PublicFact] = Field(..., description="Mail-authentication records beyond SPF and DMARC, and DNSSEC.")
    entity: Optional[Entity] = Field(None, description="The legal entity the domain is tied to, when a binding is corroborated; null otherwise. Added in trooth 0.11.0.")
    certificates: Optional[Certificates] = Field(None, description="Unexpired certificates for the exact domain name in Certificate Transparency logs, as a CT monitor returned them; null when it did not answer. Added in trooth 0.11.0.")
    security_txt: Optional[SecurityTxt] = Field(None, description="The site's /.well-known/security.txt (RFC 9116), or null when there is none or the site opted out of being read. Added in trooth 0.11.0.")
    sanctions: Optional[Sanctions] = Field(None, description="Entries on the OFAC sanctions list with exactly the legal names above. A name match is not an identification. Null when the list could not be read or no name was found. Added in trooth 0.11.0.")
    sources: Optional[List[Source]] = Field(None, description="Every response read for this reading, with the SHA-256 of the bytes read; Trooth keeps the bytes under that hash so a disputed fact can be replayed. Added in trooth 0.11.0.")
    not_read: List[NotRead] = Field(..., description="Each source that was not read, or did not answer, and why. A source not read is never guessed at.")
    note: str = Field(..., description="What the reading is and is not, as a paragraph.")
    signed: Optional[Signed] = Field(None, description="The statement that names this reading, and its log receipt. Not part of the bytes it names. Added in trooth 0.11.0.")

class Entity(BaseModel):
    "A legal entity, named by a Trooth id derived from its LEI or SEC CIK (docs/IDS.md)."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str = Field(..., description="trooth:entity:lei:<LEI> when the LEI binding is corroborated, otherwise trooth:entity:cik:<CIK>.")
    name: Optional[str] = Field(..., description="The legal name the registry holds.")
    identifiers: List[str] = Field(..., description="The corroborated identifiers (trooth:lei, trooth:cik).")
    basis: str = Field(..., description="Which bindings are corroborated.")

class Certificates(BaseModel):
    "Certificates for the exact domain name in Certificate Transparency logs."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    source: str = Field(..., description="The CT monitor URL read.")
    unexpired: int = Field(..., description="How many unexpired certificates the monitor returned.")
    issuers: List[str] = Field(..., description="The issuing authorities, at most 10.")
    newest_issued: Optional[str] = Field(..., description="The latest not-before time.")
    soonest_expiry: Optional[str] = Field(..., description="The earliest not-after time.")
    page_full: bool = Field(..., description="True when the monitor's first page was full, so there may be more.")

class SecurityTxt(BaseModel):
    "A security.txt file (RFC 9116)."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    url: str = Field(..., description="Where it was read.")
    contacts: List[str] = Field(..., description="Contact fields, at most 5.")
    expires: Optional[str] = Field(..., description="The Expires field.")
    expired: Optional[bool] = Field(..., description="Whether Expires was in the past when read; null when it does not parse.")
    policy: Optional[str] = Field(..., description="The Policy field.")
    canonical: List[str] = Field(..., description="Canonical fields.")
    signed: bool = Field(..., description="Whether the file is OpenPGP clear-signed. The signature is not checked.")

class Sanctions(BaseModel):
    "An exact-name check against a sanctions list."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    list: str = Field(..., description="The list and the part of it read.")
    source: str = Field(..., description="The list URL.")
    read_at: str = Field(..., description="When the list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    names_checked: List[str] = Field(..., description="The legal names checked.")
    matches: List[SanctionsEntry] = Field(..., description="Entries with exactly one of those names (case, punctuation and suffix spellings folded). A name match is not an identification.")

class SanctionsEntry(BaseModel):
    "A list entry."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    uid: str = Field(..., description="The entry number on the list.")
    name: str = Field(..., description="The name as listed.")
    programs: str = Field(..., description="The sanctions programs.")

class Source(BaseModel):
    "One response read."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    url: str = Field(..., description="The URL requested.")
    status: int = Field(..., description="The HTTP status.")
    sha256: str = Field(..., description="SHA-256 of the bytes read, hex.")
    bytes: int = Field(..., description="How many bytes were read.")
    complete: bool = Field(..., description="False when only the start of the document was read (a filing's first 256 KB).")
    fetched_at: str = Field(..., description="When it was requested. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")

class Signed(BaseModel):
    "The statement naming the reading, and its log receipt."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    record_sha256: str = Field(..., description="SHA-256, hex, of the RFC 8785 bytes of the reading without `signed` (finite numbers in ECMAScript shortest form).")
    record_canonicalization: Literal["RFC8785"] = Field(..., description="How those bytes were made.")
    statement: Optional[WitnessStatement] = Field(..., description="The signed envelope; its payload is a public-record-statement.v1 document. Null when the reading could not be signed.")
    statement_id: Optional[str] = Field(..., description="trooth:statement:<sha256 of the payload>.")
    log: Optional[LogReceipt] = Field(..., description="The receipt of the statement as a public_record entry of the witness statement log, or null when it was not logged.")
    problem: Optional[str] = Field(..., description="What could not be done (not signed, or signed and not logged), or null.")

class PublicFact(BaseModel):
    "One fact as its source published it, with the URL it was read from."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    key: str = Field(..., description="A stable key, source.field (for example sec.tickers, lei.jurisdiction, dns.mta_sts).")
    label: str = Field(..., description="The fact as words.")
    value: Union[str, float, bool, None, List[str]] = Field(..., description="The value as published: text, a number, true or false, a list of text, or null when the source states nothing.")
    source: str = Field(..., description="Where it was read: a URL, or dns:<name> <type> for a DNS record.")

class BindingEvidence(BaseModel):
    "One piece of evidence for or against a binding."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    kind: str = Field(..., description="For: filing_namespace_names_domain, registry_lists_domain, through_corroborated_filer (these tie the identifier to the domain), site_names_registry_name (a claim by the site), registries_agree, edgar_names_lei. Against: registry_lists_other_domain, registries_disagree, edgar_names_other_lei.")
    detail: str = Field(..., description="What was seen, as a sentence.")
    source: Optional[str] = Field(..., description="Where it was seen, or null when it follows from other evidence.")

class EntityBinding(BaseModel):
    "A link between the domain and a legal-entity identifier, with the evidence for and against it. Nothing is asserted beyond the evidence."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    identifier: Literal["cik", "lei"] = Field(..., description="cik (SEC Central Index Key) or lei (Legal Entity Identifier).")
    value: str = Field(..., description="The identifier: 10 digits for a CIK, 20 characters for an LEI.")
    id: str = Field(..., description="The stable id: trooth:cik:<10 digits> or trooth:lei:<LEI> (docs/IDS.md).")
    found_by: Literal["asked", "ticker", "site_legal_name", "edgar_lei_field", "registry_name_match"] = Field(..., description="How the identifier was found: asked (given by the requester), ticker, site_legal_name (the legal name the site states matched exactly one listed SEC filer), edgar_lei_field, registry_name_match (exact legal name and, when the SEC gives one, the jurisdiction).")
    status: Literal["corroborated", "claimed_by_site", "registries_only", "uncorroborated", "contradicted", "not_found"] = Field(..., description="corroborated: authoritative evidence ties it to the domain (the company's own filing or the registry record names the domain). claimed_by_site: the site names this entity, and nothing authoritative ties it. registries_only: registries agree with each other, nothing ties the domain. uncorroborated: no evidence either way. contradicted: authoritative evidence points elsewhere. not_found: the registry holds no such identifier.")
    for_: List[BindingEvidence] = Field(..., alias="for", description="Evidence for the binding.")
    against: List[BindingEvidence] = Field(..., description="Evidence against it.")

class Filing(BaseModel):
    "One SEC filing, as EDGAR lists it."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    form: str = Field(..., description="The form type (10-K, 10-Q, 8-K, DEF 14A, 20-F ...).")
    filed: str = Field(..., description="The filing date, YYYY-MM-DD.")
    report_date: Optional[str] = Field(..., description="The period or event date, when EDGAR gives one.")
    items: List[str] = Field(..., description="For an 8-K, the item numbers it reports (for example 1.05, 4.01).")
    description: Optional[str] = Field(..., description="EDGAR's description of the primary document.")
    url: str = Field(..., description="The primary document on www.sec.gov.")

class FinancialFact(BaseModel):
    "A value the company filed in XBRL, as it filed it: the latest annual (10-K, full fiscal year) value of the concept."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    tag: str = Field(..., description="The XBRL concept, taxonomy:Name.")
    label: str = Field(..., description="The concept as words.")
    value: float = Field(..., description="The value as filed.")
    unit: str = Field(..., description="The unit (USD).")
    period_start: Optional[str] = Field(..., description="The period start for a flow such as revenue; null for a balance such as assets.")
    period_end: str = Field(..., description="The period end.")
    form: str = Field(..., description="The form the value was filed in.")
    filed: str = Field(..., description="The filing date.")
    accession: str = Field(..., description="The accession number of that filing.")
    source: str = Field(..., description="The data.sec.gov URL the value was read from.")

class SiteRead(BaseModel):
    "The legal names the company's pages state in copyright notices."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    legal_names: List[SiteName] = Field(..., description="Each legal name stated, with the page.")
    read: bool = Field(..., description="Whether any page of the site could be read.")
    reason: Optional[str] = Field(..., description="Why no name was found, or why the site was not read (for example its robots.txt opts out).")
    links: Optional[List[SiteLink]] = Field(None, description="Pages the home page links to on the company's own domain: investor relations, trust center, security, status, sustainability. Linked, not read. Added in trooth 0.11.0.")

class SiteLink(BaseModel):
    "A page the home page links to."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    kind: Literal["investor_relations", "trust_center", "security", "status", "sustainability"] = Field(..., description="What the page is.")
    url: str = Field(..., description="The link, without query or fragment.")

class SiteName(BaseModel):
    "A legal name a page states."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str = Field(..., description="The name as written.")
    source: str = Field(..., description="The page.")

class SecRecord(BaseModel):
    "The SEC filer's registration facts, filings and annual XBRL values."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    cik: str = Field(..., description="The Central Index Key, 10 digits.")
    facts: List[PublicFact] = Field(..., description="Registration facts on file with the SEC.")
    latest: Dict[str, Filing] = Field(..., description="The latest filing of each key form type, keyed by form.")
    events: List[Filing] = Field(..., description="8-K filings of the last two years, newest first, at most 50.")
    events_cover_since: Optional[str] = Field(..., description="The earliest date the events cover.")
    cybersecurity_incidents: List[Filing] = Field(..., description="8-K filings reporting Item 1.05, a material cybersecurity incident.")
    auditor_changes: List[Filing] = Field(..., description="8-K filings reporting Item 4.01, a change of certifying accountant.")
    non_reliance: List[Filing] = Field(..., description="8-K filings reporting Item 4.02, non-reliance on financial statements issued before.")
    insider_forms_last_90_days: int = Field(..., description="Forms 3, 4 and 5 filed in the last 90 days.")
    financials: List[FinancialFact] = Field(..., description="Annual values as filed.")

class LeiRecord(BaseModel):
    "The Legal Entity Identifier record."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    lei: str = Field(..., description="The LEI.")
    facts: List[PublicFact] = Field(..., description="The record's facts.")
    direct_parent: Optional[Parent] = Field(..., description="The direct parent the record reports, or null.")
    ultimate_parent: Optional[Parent] = Field(..., description="The ultimate parent the record reports, or null.")

class Parent(BaseModel):
    "A parent entity."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    lei: str = Field(..., description="The parent's LEI.")
    name: Optional[str] = Field(..., description="Its legal name.")

class NotRead(BaseModel):
    "A source not read."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    source: str = Field(..., description="The source.")
    reason: str = Field(..., description="Why.")

class VerificationBundle(BaseModel):
    "Everything needed to check one witness statement with no network: the statement, its evidence manifest, the key list as read, and the exact mapping bytes. Written by `trooth verify --save-bundle`; read by `trooth verify --bundle` and the SDKs. A bundle is only as fresh as its key list."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    bundle: Literal["trooth.verification-bundle.v1"] = Field(..., description="The bundle format.")
    created_at: str = Field(..., description="When the bundle was written. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    domain: Optional[str] = Field(..., description="The domain the bundle was saved for. A reader may ask about another; a statement for a different domain is a mismatch.")
    statement: WitnessStatement = Field(..., description="The signed envelope, exactly as published.")
    manifest: Optional[EvidenceManifest] = Field(..., description="The evidence manifest, or null when none was saved.")
    keys: BundleKeys = Field(..., description="The key list as read when the bundle was written.")
    mapping: Optional[BundleMapping] = Field(..., description="The exact mapping bytes, or null when none were saved.")
    log: Optional[BundleLog] = Field(None, description="What the witness statement log answered when the bundle was written: the log key used, the receipt or null, and every correction. Absent in a bundle written before the log, or when the log was not read.")

class BundleLog(BaseModel):
    "The log answer, carried so the log part can be checked offline too."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    vkey: str = Field(..., description="The log verifier key the receipt was checked against, as a signed-note key (name+hash+key). A pinned key, when the checker has one, replaces it.")
    receipt: Optional[LogReceipt] = Field(..., description="The receipt for the statement, or null when the log held no entry for it.")
    corrections: List[LoggedCorrection] = Field(..., description="Every logged correction naming this statement, each with its own receipt.")

class LoggedCorrection(BaseModel):
    "A correction envelope and its receipt."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    statement: WitnessStatement = Field(..., description="The correction envelope: its payload is a trooth.correction.v1 document in RFC 8785 bytes.")
    receipt: LogReceipt = Field(..., description="The receipt for the correction.")

class BundleKeys(BaseModel):
    "The key list as read."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    keys: List[PublicKey] = Field(..., description="The keys array of the key list.")
    list_read_at: Optional[str] = Field(..., description="When the key list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    source: Optional[str] = Field(..., description="Where it was read from: a URL or a file path.")

class BundleMapping(BaseModel):
    "The mapping document, byte for byte."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    url: Optional[str] = Field(..., description="Where the bytes were read from.")
    digest: str = Field(..., description="The digest of the carried bytes, for display. A checker hashes the bytes itself and compares with the signed digest.")
    bytes_base64: str = Field(..., description="The exact mapping bytes, standard base64.")

class VerifyResult(BaseModel):
    "The JSON document `trooth verify --json` writes, and the shape the SDKs return. The verdict is the only conclusion; everything else says how it was reached."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    domain: Optional[str] = Field(..., description="The domain asked about, or the signed domain when none was asked.")
    verdict: Literal["checked", "checked_v1", "partially_checked", "signature_not_trusted", "mismatch", "superseded"] = Field(..., description="checked: v2 or v3, everything bound and matching. checked_v1: a v1 statement that checks. partially_checked: a mapping or manifest was not supplied. signature_not_trusted: malformed, invalid or untrusted key. mismatch: trusted, but a count, the domain, the mapping, the manifest or a log receipt disagrees. superseded: everything held, and a correction Trooth signed and logged withdraws or replaces the statement.")
    version: Literal["v1", "v2", "v3", "unknown"] = Field(..., description="The statement version, or unknown.")
    read_at: Optional[str] = Field(None, description="The read_at the payload carries. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    reading_id: Optional[str] = Field(None, description="The reading id the payload carries.")
    statement_id: Optional[str] = Field(None, description="trooth:statement: plus the hex SHA-256 of the exact payload bytes (docs/IDS.md).")
    signature: Literal["valid", "invalid", "malformed"] = Field(..., description="valid, invalid or malformed.")
    key: KeyTrust = Field(..., description="The signing key and whether it is trusted at read_at.")
    subject: Subject = Field(..., description="The signed domain against the domain asked about.")
    binding: Binding = Field(..., description="The mapping and manifest against their signed digests.")
    counts: CountCheck = Field(..., description="Whether the signed counts agree with the signed checks.")
    log: Optional[LogCheck] = Field(None, description="The witness statement log part of the check. Absent when the log was not asked (offline from saved files, --no-log) or the signature was not trusted.")
    assurance: str = Field(..., description="What a valid signature of this version shows and does not show, in words.")
    keys_read_at: Optional[str] = Field(None, description="When the key list used was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    sources: Optional[Dict[str, Optional[str]]] = Field(None, description="Where each input came from: a URL, a file path, or null when not supplied.")

class KeyTrust(BaseModel):
    "The key decision."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    kid: str = Field(..., description="The key id the envelope names.")
    state: Literal["active", "retired", "compromised", "revoked_unrecorded", "unknown"] = Field(..., description="The lifecycle state found on the key list.")
    trusted: bool = Field(..., description="Whether a valid signature from this key at this time is relied on.")
    reason: str = Field(..., description="Why, in words.")

class Subject(BaseModel):
    "The subject decision."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    signed: Optional[str] = Field(..., description="The domain in the signed payload.")
    asked: Optional[str] = Field(..., description="The domain asked about.")
    status: Literal["match", "mismatch", "not_checked"] = Field(..., description="match, mismatch, or not_checked (no domain given, or the signature was not trusted).")

class Binding(BaseModel):
    "The binding decision."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: Literal["bound", "partially_checked", "mismatch", "absent", "unchecked"] = Field(..., description="bound, partially_checked, mismatch, absent (v1 binds neither) or unchecked (signature not trusted).")
    mapping: Literal["match", "mismatch", "not_supplied", "absent"] = Field(..., description="The mapping result.")
    manifest: Literal["match", "mismatch", "not_supplied", "absent"] = Field(..., description="The manifest result.")

class LogCheck(BaseModel):
    "What the log showed about the statement."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: Literal["included", "not_logged", "unavailable", "checkpoint_invalid", "proof_invalid"] = Field(..., description="included: the receipt checks against a checkpoint signed by the log key. not_logged: the log holds no entry for it (reported, not a failure in this version). unavailable: the log could not be read. checkpoint_invalid: the checkpoint is not signed by the log key or names another log. proof_invalid: the receipt does not take this statement to the signed root.")
    index: Optional[int] = Field(..., description="The entry index the receipt names, or null.")
    tree_size: Optional[int] = Field(..., description="The signed tree size the receipt is against, or null.")
    reason: Optional[str] = Field(..., description="Why, in words.")
    corrections: List[CorrectionCheck] = Field(..., description="Each correction the log returned and whether it checked.")
    superseded_by: Optional[str] = Field(..., description="The statement id of the first correction that checked, or null.")
    vkey_source: Optional[str] = Field(None, description="Where the log key came from: pinned in this release, --log-vkey, carried in a bundle, or served by the log.")

class CorrectionCheck(BaseModel):
    "One correction and whether it is relied on."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    valid: bool = Field(..., description="True when it is signed by a trusted key, in RFC 8785 bytes, names this statement, and is included in the log.")
    correction_statement_id: Optional[str] = Field(..., description="The statement id of the correction itself.")
    code: Optional[str] = Field(..., description="The reason code it carries.")
    effect: Optional[str] = Field(..., description="withdrawn or replaced.")
    replacement: Optional[str] = Field(..., description="The replacing statement id, for replaced.")
    issued_at: Optional[str] = Field(..., description="When Trooth issued it, as Trooth asserts. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    reason: Optional[str] = Field(..., description="Why it is or is not relied on, in words.")

class CountCheck(BaseModel):
    "The count decision."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    identities_hold: bool = Field(..., description="True when every identity holds.")
    problems: List[str] = Field(..., description="Each identity that does not hold, in words.")

class WitnessPayloadV1(BaseModel):
    "The JSON a trooth.witness-statement.v1 payload holds. v1 binds the outcomes and counts only: no mapping, manifest, evaluator or subject scope."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    statement: Literal["trooth.witness-statement.v1"] = Field(..., description="The statement version.")
    reading_id: str = Field(..., description="The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).")
    domain: str = Field(..., description="The domain the reading was taken of: lowercase, no trailing dot.")
    read_at: str = Field(..., description="When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    checks: List[CheckV1] = Field(..., description="Every check in the reading.")
    counts: CountsV1 = Field(..., description="The two counts, which must agree with the checks.")

class CheckV1(BaseModel):
    "One check in a v1 reading. v1 carries no reason."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str = Field(..., description="The check id.")
    category: str = Field(..., description="The check category.")
    kind: str = Field(..., description="probe or attest.")
    outcome: Literal["as expected", "not as expected", "not read"] = Field(..., description="One of three outcomes.")

class CountsV1(BaseModel):
    "The two counts a v1 payload carries."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    read: int = Field(..., description="Checks whose outcome is not `not read`.")
    as_expected: int = Field(..., description="Checks whose outcome is `as expected`.")

class WitnessPayloadV2(BaseModel):
    "The JSON a trooth.witness-statement.v2 payload holds. Its members are signed in exactly this order with no whitespace. It binds the check mapping, the evaluator, the subject scope and the evidence manifest."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    statement: Literal["trooth.witness-statement.v2"] = Field(..., description="The statement version.")
    reading_id: str = Field(..., description="The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).")
    domain: str = Field(..., description="The domain the reading was taken of: lowercase, no trailing dot.")
    read_at: str = Field(..., description="When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    subject_scope: SubjectScope = Field(..., description="What the reading covered.")
    methodology: Methodology = Field(..., description="The check mapping, bound by digest.")
    evaluator: Evaluator = Field(..., description="The software that took the reading.")
    evidence_manifest: EvidenceManifestRef = Field(..., description="The evidence manifest, bound by digest.")
    checks: List[Check] = Field(..., description="Every check in the reading.")
    counts: Counts = Field(..., description="Counts that must agree with the checks.")

class Check(BaseModel):
    "One check in the reading and its outcome."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str = Field(..., description="The check id in the check mapping the payload names (for example S1, L2).")
    category: str = Field(..., description="The check category in the mapping (for example security, legal, ai, ip, business).")
    kind: str = Field(..., description="How the check is taken: `probe` reads the public surface; `attest` reads something the company published about itself.")
    outcome: Literal["as expected", "not as expected", "not read"] = Field(..., description="One of three outcomes. There is no fourth value and no score.")
    reason: Optional[CheckReason] = Field(..., description="Null when the outcome is `as expected`; otherwise why.")

class CheckReason(BaseModel):
    "Why a check is not `as expected`. Present on every check whose outcome is `not read` or `not as expected`."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    code: Literal["source_unavailable", "timeout", "evaluator_limitation", "carried_from_earlier_reading", "check_misconfigured", "contrary_observation", "expected_item_absent"] = Field(..., description="The reason code. source_unavailable, timeout, evaluator_limitation, carried_from_earlier_reading and check_misconfigured go with `not read`; contrary_observation and expected_item_absent go with `not as expected`.")
    version: Literal["trooth.check-explanations.v1"] = Field(..., description="The version of the reason vocabulary.")
    source_ref: Optional[str] = Field(..., description="The public source the reason refers to, or null. Always null when `withheld` is true.")
    withheld: bool = Field(..., description="True when the source behind this reason is not published (for example a private document); only a commitment to it is in the evidence manifest.")
    withheld_reason: Optional[str] = Field(..., description="Why the source is withheld. Required, non-empty, when `withheld` is true; otherwise null.")

class Counts(BaseModel):
    "Counts that MUST agree with the checks: read + not_read = in_reading; as_expected + not_as_expected = read; in_reading = the number of checks. They are reported apart and never added into one number."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    read: int = Field(..., description="Checks whose outcome is not `not read`.")
    as_expected: int = Field(..., description="Checks whose outcome is `as expected`.")
    not_as_expected: int = Field(..., description="Checks whose outcome is `not as expected`.")
    not_read: int = Field(..., description="Checks whose outcome is `not read`.")
    in_reading: int = Field(..., description="All checks in the reading.")

class SubjectScope(BaseModel):
    "What the reading covered."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    domain: str = Field(..., description="The domain read. Equals the payload domain.")
    surface: str = Field(..., description="Which surface was read. `public`: only what anyone can fetch.")
    checks_in_scope: int = Field(..., description="The number of checks in scope. Equals the number of checks listed.")

class Methodology(BaseModel):
    "The exact check mapping the reading used, bound by digest."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    standard: str = Field(..., description="The name of the standard the mapping belongs to.")
    mapping_version: str = Field(..., description="The mapping version.")
    mapping_url: str = Field(..., description="Where the exact mapping bytes are served. Immutable versions live under https://trooth.co/standard/check-mapping/.")
    mapping_digest: str = Field(..., description="`sha256:` plus the lowercase hex SHA-256 of the exact mapping bytes.")

class Evaluator(BaseModel):
    "The software that took the reading."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str = Field(..., description="The evaluator name.")
    version: str = Field(..., description="The evaluator version.")

class EvidenceManifestRef(BaseModel):
    "The evidence manifest the reading binds, by digest."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    digest: str = Field(..., description="`sha256:` plus the hex SHA-256 of the canonical manifest bytes (evidence-manifest.schema.json).")
    entries: int = Field(..., description="The number of manifest entries.")
    canonicalization: str = Field(..., description="How the manifest bytes are formed: entries sorted by check_id, keys check_id then source or commitment, no whitespace, UTF-8.")

class WitnessPayloadV3(BaseModel):
    "The JSON a trooth.witness-statement.v3 payload holds: the v2 content plus subject_id and signer, serialized as RFC 8785 (JCS). Every number is an integer between -(2^53 - 1) and 2^53 - 1, so every implementation produces the same bytes."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    checks: List[Check] = Field(..., description="Every check in the reading.")
    counts: Counts = Field(..., description="Counts that must agree with the checks.")
    domain: str = Field(..., description="The domain the reading was taken of: lowercase, no trailing dot.")
    evaluator: Evaluator = Field(..., description="The software that took the reading.")
    evidence_manifest: EvidenceManifestRef = Field(..., description="The evidence manifest, bound by digest.")
    methodology: Methodology = Field(..., description="The check mapping, bound by digest.")
    read_at: str = Field(..., description="When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    reading_id: str = Field(..., description="The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).")
    signer: Signer = Field(..., description="The signing key, inside the signed bytes.")
    statement: Literal["trooth.witness-statement.v3"] = Field(..., description="The statement version.")
    subject_id: str = Field(..., description="The subject by its stable id, trooth:domain:<domain> (docs/IDS.md). MUST name the payload domain.")
    subject_scope: SubjectScope = Field(..., description="What the reading covered.")

class Signer(BaseModel):
    "The signing key, named inside the signed bytes so the envelope cannot point at another key."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    key_id: str = Field(..., description="The kid of the signing key. MUST equal the envelope key_id.")
    issuer: Literal["trooth.co"] = Field(..., description="Who signs: trooth.co.")

class WitnessStatement(BaseModel):
    "The signed envelope Trooth publishes as `witnessStatement` on a record. The signature covers the exact UTF-8 bytes of `payload`, nothing else. How to check it: docs/VERIFY.md in github.com/troothllc/trooth-cli."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    payload: str = Field(..., description="The signing input: the exact JSON text that was signed. Parse it to read it; never re-serialize it to check it. Its `statement` field names the version (witness-payload.v1, v2 or v3).")
    signature: str = Field(..., description="The Ed25519 signature over the payload bytes: `ed25519:` followed by standard base64 of the 64 signature bytes.")
    key_id: str = Field(..., description="The `kid` of the signing key on https://api.trooth.co/public/keys. A v3 payload names the same key inside the signed bytes, at signer.key_id.")
    alg: Literal["Ed25519"] = Field(..., description="The signature algorithm. Always Ed25519 (RFC 8032, pure EdDSA).")
    canonicalization: Literal["json-fixed-key-order-no-whitespace-utf8", "RFC8785"] = Field(..., description="How the payload bytes were produced. `json-fixed-key-order-no-whitespace-utf8` for v1 and v2; `RFC8785` (JSON Canonicalization Scheme, integers only) for v3, where the payload MUST equal the canonical form of the JSON it holds.")

EvidenceManifest = List[ManifestEntry]
"""The evidence manifest a v2 or v3 statement binds by digest, published beside the statement as `witnessEvidenceManifest`. Canonical bytes: entries sorted by check_id, each as {"check_id":..,"source":..} or {"check_id":..,"commitment":..}, no whitespace, UTF-8."""


CorrectionPayload.model_rebuild()
CorrectionReason.model_rebuild()
ManifestEntry.model_rebuild()
KeyList.model_rebuild()
PublicKey.model_rebuild()
KeyEvent.model_rebuild()
LogReceipt.model_rebuild()
PublicRecordStatement.model_rebuild()
BindingStatus.model_rebuild()
StatementSigner.model_rebuild()
PublicRecordReading.model_rebuild()
Entity.model_rebuild()
Certificates.model_rebuild()
SecurityTxt.model_rebuild()
Sanctions.model_rebuild()
SanctionsEntry.model_rebuild()
Source.model_rebuild()
Signed.model_rebuild()
PublicFact.model_rebuild()
BindingEvidence.model_rebuild()
EntityBinding.model_rebuild()
Filing.model_rebuild()
FinancialFact.model_rebuild()
SiteRead.model_rebuild()
SiteLink.model_rebuild()
SiteName.model_rebuild()
SecRecord.model_rebuild()
LeiRecord.model_rebuild()
Parent.model_rebuild()
NotRead.model_rebuild()
VerificationBundle.model_rebuild()
BundleLog.model_rebuild()
LoggedCorrection.model_rebuild()
BundleKeys.model_rebuild()
BundleMapping.model_rebuild()
VerifyResult.model_rebuild()
KeyTrust.model_rebuild()
Subject.model_rebuild()
Binding.model_rebuild()
LogCheck.model_rebuild()
CorrectionCheck.model_rebuild()
CountCheck.model_rebuild()
WitnessPayloadV1.model_rebuild()
CheckV1.model_rebuild()
CountsV1.model_rebuild()
WitnessPayloadV2.model_rebuild()
Check.model_rebuild()
CheckReason.model_rebuild()
Counts.model_rebuild()
SubjectScope.model_rebuild()
Methodology.model_rebuild()
Evaluator.model_rebuild()
EvidenceManifestRef.model_rebuild()
WitnessPayloadV3.model_rebuild()
Signer.model_rebuild()
WitnessStatement.model_rebuild()
