# GENERATED by scripts/gen-types.mjs from schemas/ in github.com/troothllc/trooth-cli.
# Do not edit by hand: change the schema and run `node scripts/gen-types.mjs`.
"""Pydantic v2 models for the documents Trooth publishes about a witness statement."""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class ManifestEntry(BaseModel):
    "One check and the evidence behind it: a public `source`, or a `commitment` to a private one. Exactly one of the two."

    model_config = ConfigDict(extra="allow")

    check_id: str = Field(..., description="The check id. Unique in the manifest.")
    source: Optional[str] = Field(None, description="The public URL the check read.")
    commitment: Optional[str] = Field(None, description="`sha256:` plus the hex SHA-256 of salt, a newline byte and the private reference. Only its holder can open it.")

class KeyList(BaseModel):
    "The body of https://api.trooth.co/public/keys, or a saved copy of it. Save it with the time you read it: a saved list cannot show a compromise announced later."

    model_config = ConfigDict(extra="allow")

    keys: List[PublicKey] = Field(..., description="Every key, current and past.")
    list_read_at: Optional[str] = Field(None, description="When the list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    active_kid: Optional[str] = Field(None, description="The kid of the key currently used for new statements.")
    note: Optional[str] = Field(None, description="A note from the key service.")

class PublicKey(BaseModel):
    "One published key and its lifecycle. Only `kid`, `alg`, `encoding`, `public_key`, `status` and the three lifecycle times decide trust (docs/VERIFY.md section 3)."

    model_config = ConfigDict(extra="allow")

    kid: str = Field(..., description="The key id a statement names in key_id.")
    alg: Literal["Ed25519"] = Field(..., description="Always Ed25519.")
    encoding: Optional[Literal["hex", "base64"]] = Field(None, description="How public_key is written: hex or base64.")
    public_key: str = Field(..., description="The 32-byte Ed25519 public key, in `encoding`.")
    status: Literal["active", "retired", "revoked", "compromised"] = Field(..., description="active, retired, revoked or compromised.")
    state: Optional[str] = Field(None, description="The same lifecycle state as written by the key service.")
    retired_at: Optional[str] = Field(None, description="When the key was retired. Statements carrying a read_at strictly before this stay trusted. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    compromised_at: Optional[str] = Field(None, description="When the key was found compromised. Nothing signed by it is relied on. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    revoked_at: Optional[str] = Field(None, description="When the key was revoked. A revocation with no compromise recorded is treated as a compromise. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    created_at: Optional[str] = Field(None, description="When the key was created, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    activated_at: Optional[str] = Field(None, description="When the key was first used, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    first_listed_at: Optional[str] = Field(None, description="When the key first appeared on the list. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    fingerprint: Optional[str] = Field(None, description="A short fingerprint of the key, for display.")
    purpose: Optional[str] = Field(None, description="What the key is for, as a short label.")
    signs: Optional[str] = Field(None, description="What the key signs, in words.")
    events: Optional[List[KeyEvent]] = Field(None, description="Lifecycle events, oldest first.")

class KeyEvent(BaseModel):
    "One lifecycle event of a key."

    model_config = ConfigDict(extra="allow")

    event: str = Field(..., description="What happened (for example first_listed, retired, compromised).")
    at: str = Field(..., description="When. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    note: Optional[str] = Field(None, description="A note, or null.")

class VerificationBundle(BaseModel):
    "Everything needed to check one witness statement with no network: the statement, its evidence manifest, the key list as read, and the exact mapping bytes. Written by `trooth verify --save-bundle`; read by `trooth verify --bundle` and the SDKs. A bundle is only as fresh as its key list."

    model_config = ConfigDict(extra="allow")

    bundle: Literal["trooth.verification-bundle.v1"] = Field(..., description="The bundle format.")
    created_at: str = Field(..., description="When the bundle was written. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    domain: Optional[str] = Field(..., description="The domain the bundle was saved for. A reader may ask about another; a statement for a different domain is a mismatch.")
    statement: WitnessStatement = Field(..., description="The signed envelope, exactly as published.")
    manifest: Optional[EvidenceManifest] = Field(..., description="The evidence manifest, or null when none was saved.")
    keys: BundleKeys = Field(..., description="The key list as read when the bundle was written.")
    mapping: Optional[BundleMapping] = Field(..., description="The exact mapping bytes, or null when none were saved.")

class BundleKeys(BaseModel):
    "The key list as read."

    model_config = ConfigDict(extra="allow")

    keys: List[PublicKey] = Field(..., description="The keys array of the key list.")
    list_read_at: Optional[str] = Field(..., description="When the key list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    source: Optional[str] = Field(..., description="Where it was read from: a URL or a file path.")

class BundleMapping(BaseModel):
    "The mapping document, byte for byte."

    model_config = ConfigDict(extra="allow")

    url: Optional[str] = Field(..., description="Where the bytes were read from.")
    digest: str = Field(..., description="The digest of the carried bytes, for display. A checker hashes the bytes itself and compares with the signed digest.")
    bytes_base64: str = Field(..., description="The exact mapping bytes, standard base64.")

class VerifyResult(BaseModel):
    "The JSON document `trooth verify --json` writes, and the shape the SDKs return. The verdict is the only conclusion; everything else says how it was reached."

    model_config = ConfigDict(extra="allow")

    domain: Optional[str] = Field(..., description="The domain asked about, or the signed domain when none was asked.")
    verdict: Literal["checked", "checked_v1", "partially_checked", "signature_not_trusted", "mismatch"] = Field(..., description="checked: v2 or v3, everything bound and matching. checked_v1: a v1 statement that checks. partially_checked: a mapping or manifest was not supplied. signature_not_trusted: malformed, invalid or untrusted key. mismatch: trusted, but a count, the domain, the mapping or the manifest disagrees.")
    version: Literal["v1", "v2", "v3", "unknown"] = Field(..., description="The statement version, or unknown.")
    read_at: Optional[str] = Field(None, description="The read_at the payload carries. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    reading_id: Optional[str] = Field(None, description="The reading id the payload carries.")
    statement_id: Optional[str] = Field(None, description="trooth:statement: plus the hex SHA-256 of the exact payload bytes (docs/IDS.md).")
    signature: Literal["valid", "invalid", "malformed"] = Field(..., description="valid, invalid or malformed.")
    key: KeyTrust = Field(..., description="The signing key and whether it is trusted at read_at.")
    subject: Subject = Field(..., description="The signed domain against the domain asked about.")
    binding: Binding = Field(..., description="The mapping and manifest against their signed digests.")
    counts: CountCheck = Field(..., description="Whether the signed counts agree with the signed checks.")
    assurance: str = Field(..., description="What a valid signature of this version shows and does not show, in words.")
    keys_read_at: Optional[str] = Field(None, description="When the key list used was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    sources: Optional[Dict[str, Optional[str]]] = Field(None, description="Where each input came from: a URL, a file path, or null when not supplied.")

class KeyTrust(BaseModel):
    "The key decision."

    model_config = ConfigDict(extra="allow")

    kid: str = Field(..., description="The key id the envelope names.")
    state: Literal["active", "retired", "compromised", "revoked_unrecorded", "unknown"] = Field(..., description="The lifecycle state found on the key list.")
    trusted: bool = Field(..., description="Whether a valid signature from this key at this time is relied on.")
    reason: str = Field(..., description="Why, in words.")

class Subject(BaseModel):
    "The subject decision."

    model_config = ConfigDict(extra="allow")

    signed: Optional[str] = Field(..., description="The domain in the signed payload.")
    asked: Optional[str] = Field(..., description="The domain asked about.")
    status: Literal["match", "mismatch", "not_checked"] = Field(..., description="match, mismatch, or not_checked (no domain given, or the signature was not trusted).")

class Binding(BaseModel):
    "The binding decision."

    model_config = ConfigDict(extra="allow")

    status: Literal["bound", "partially_checked", "mismatch", "absent", "unchecked"] = Field(..., description="bound, partially_checked, mismatch, absent (v1 binds neither) or unchecked (signature not trusted).")
    mapping: Literal["match", "mismatch", "not_supplied", "absent"] = Field(..., description="The mapping result.")
    manifest: Literal["match", "mismatch", "not_supplied", "absent"] = Field(..., description="The manifest result.")

class CountCheck(BaseModel):
    "The count decision."

    model_config = ConfigDict(extra="allow")

    identities_hold: bool = Field(..., description="True when every identity holds.")
    problems: List[str] = Field(..., description="Each identity that does not hold, in words.")

class WitnessPayloadV1(BaseModel):
    "The JSON a trooth.witness-statement.v1 payload holds. v1 binds the outcomes and counts only: no mapping, manifest, evaluator or subject scope."

    model_config = ConfigDict(extra="allow")

    statement: Literal["trooth.witness-statement.v1"] = Field(..., description="The statement version.")
    reading_id: str = Field(..., description="The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).")
    domain: str = Field(..., description="The domain the reading was taken of: lowercase, no trailing dot.")
    read_at: str = Field(..., description="When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    checks: List[CheckV1] = Field(..., description="Every check in the reading.")
    counts: CountsV1 = Field(..., description="The two counts, which must agree with the checks.")

class CheckV1(BaseModel):
    "One check in a v1 reading. v1 carries no reason."

    model_config = ConfigDict(extra="allow")

    id: str = Field(..., description="The check id.")
    category: str = Field(..., description="The check category.")
    kind: str = Field(..., description="probe or attest.")
    outcome: Literal["as expected", "not as expected", "not read"] = Field(..., description="One of three outcomes.")

class CountsV1(BaseModel):
    "The two counts a v1 payload carries."

    model_config = ConfigDict(extra="allow")

    read: int = Field(..., description="Checks whose outcome is not `not read`.")
    as_expected: int = Field(..., description="Checks whose outcome is `as expected`.")

class WitnessPayloadV2(BaseModel):
    "The JSON a trooth.witness-statement.v2 payload holds. Its members are signed in exactly this order with no whitespace. It binds the check mapping, the evaluator, the subject scope and the evidence manifest."

    model_config = ConfigDict(extra="allow")

    statement: Literal["trooth.witness-statement.v2"] = Field(..., description="The statement version.")
    reading_id: str = Field(..., description="The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).")
    domain: str = Field(..., description="The domain the reading was taken of: lowercase, no trailing dot.")
    read_at: str = Field(..., description="When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    subject_scope: SubjectScope = Field(..., description="What the reading covered.")
    methodology: Methodology = Field(..., description="The check mapping, bound by digest.")
    evaluator: Evaluator = Field(..., description="The software that took the reading.")
    evidence_manifest: EvidenceManifestRef = Field(..., description="The evidence manifest, bound by digest.")
    checks: List[Check] = Field(..., description="Every check in the reading.")
    counts: Counts = Field(..., description="Counts that must agree with the checks.")

class Check(BaseModel):
    "One check in the reading and its outcome."

    model_config = ConfigDict(extra="allow")

    id: str = Field(..., description="The check id in the check mapping the payload names (for example S1, L2).")
    category: str = Field(..., description="The check category in the mapping (for example security, legal, ai, ip, business).")
    kind: str = Field(..., description="How the check is taken: `probe` reads the public surface; `attest` reads something the company published about itself.")
    outcome: Literal["as expected", "not as expected", "not read"] = Field(..., description="One of three outcomes. There is no fourth value and no score.")
    reason: Optional[CheckReason] = Field(..., description="Null when the outcome is `as expected`; otherwise why.")

class CheckReason(BaseModel):
    "Why a check is not `as expected`. Present on every check whose outcome is `not read` or `not as expected`."

    model_config = ConfigDict(extra="allow")

    code: Literal["source_unavailable", "timeout", "evaluator_limitation", "carried_from_earlier_reading", "check_misconfigured", "contrary_observation", "expected_item_absent"] = Field(..., description="The reason code. source_unavailable, timeout, evaluator_limitation, carried_from_earlier_reading and check_misconfigured go with `not read`; contrary_observation and expected_item_absent go with `not as expected`.")
    version: Literal["trooth.check-explanations.v1"] = Field(..., description="The version of the reason vocabulary.")
    source_ref: Optional[str] = Field(..., description="The public source the reason refers to, or null. Always null when `withheld` is true.")
    withheld: bool = Field(..., description="True when the source behind this reason is not published (for example a private document); only a commitment to it is in the evidence manifest.")
    withheld_reason: Optional[str] = Field(..., description="Why the source is withheld. Required, non-empty, when `withheld` is true; otherwise null.")

class Counts(BaseModel):
    "Counts that MUST agree with the checks: read + not_read = in_reading; as_expected + not_as_expected = read; in_reading = the number of checks. They are reported apart and never added into one number."

    model_config = ConfigDict(extra="allow")

    read: int = Field(..., description="Checks whose outcome is not `not read`.")
    as_expected: int = Field(..., description="Checks whose outcome is `as expected`.")
    not_as_expected: int = Field(..., description="Checks whose outcome is `not as expected`.")
    not_read: int = Field(..., description="Checks whose outcome is `not read`.")
    in_reading: int = Field(..., description="All checks in the reading.")

class SubjectScope(BaseModel):
    "What the reading covered."

    model_config = ConfigDict(extra="allow")

    domain: str = Field(..., description="The domain read. Equals the payload domain.")
    surface: str = Field(..., description="Which surface was read. `public`: only what anyone can fetch.")
    checks_in_scope: int = Field(..., description="The number of checks in scope. Equals the number of checks listed.")

class Methodology(BaseModel):
    "The exact check mapping the reading used, bound by digest."

    model_config = ConfigDict(extra="allow")

    standard: str = Field(..., description="The name of the standard the mapping belongs to.")
    mapping_version: str = Field(..., description="The mapping version.")
    mapping_url: str = Field(..., description="Where the exact mapping bytes are served. Immutable versions live under https://trooth.co/standard/check-mapping/.")
    mapping_digest: str = Field(..., description="`sha256:` plus the lowercase hex SHA-256 of the exact mapping bytes.")

class Evaluator(BaseModel):
    "The software that took the reading."

    model_config = ConfigDict(extra="allow")

    name: str = Field(..., description="The evaluator name.")
    version: str = Field(..., description="The evaluator version.")

class EvidenceManifestRef(BaseModel):
    "The evidence manifest the reading binds, by digest."

    model_config = ConfigDict(extra="allow")

    digest: str = Field(..., description="`sha256:` plus the hex SHA-256 of the canonical manifest bytes (evidence-manifest.schema.json).")
    entries: int = Field(..., description="The number of manifest entries.")
    canonicalization: str = Field(..., description="How the manifest bytes are formed: entries sorted by check_id, keys check_id then source or commitment, no whitespace, UTF-8.")

class WitnessPayloadV3(BaseModel):
    "The JSON a trooth.witness-statement.v3 payload holds: the v2 content plus subject_id and signer, serialized as RFC 8785 (JCS). Every number is an integer between -(2^53 - 1) and 2^53 - 1, so every implementation produces the same bytes."

    model_config = ConfigDict(extra="allow")

    checks: List[Check] = Field(..., description="Every check in the reading.")
    counts: Counts = Field(..., description="Counts that must agree with the checks.")
    domain: str = Field(..., description="The domain the reading was taken of: lowercase, no trailing dot.")
    evaluator: Evaluator = Field(..., description="The software that took the reading.")
    evidence_manifest: EvidenceManifestRef = Field(..., description="The evidence manifest, bound by digest.")
    methodology: Methodology = Field(..., description="The check mapping, bound by digest.")
    read_at: str = Field(..., description="When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    reading_id: str = Field(..., description="The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).")
    signer: Signer = Field(..., description="The signing key, inside the signed bytes.")
    statement: Literal["trooth.witness-statement.v3"] = Field(..., description="The statement version.")
    subject_id: str = Field(..., description="The subject by its stable id, trooth:domain:<domain> (docs/IDS.md). MUST name the payload domain.")
    subject_scope: SubjectScope = Field(..., description="What the reading covered.")

class Signer(BaseModel):
    "The signing key, named inside the signed bytes so the envelope cannot point at another key."

    model_config = ConfigDict(extra="allow")

    key_id: str = Field(..., description="The kid of the signing key. MUST equal the envelope key_id.")
    issuer: Literal["trooth.co"] = Field(..., description="Who signs: trooth.co.")

class WitnessStatement(BaseModel):
    "The signed envelope Trooth publishes as `witnessStatement` on a record. The signature covers the exact UTF-8 bytes of `payload`, nothing else. How to check it: docs/VERIFY.md in github.com/troothllc/trooth-cli."

    model_config = ConfigDict(extra="allow")

    payload: str = Field(..., description="The signing input: the exact JSON text that was signed. Parse it to read it; never re-serialize it to check it. Its `statement` field names the version (witness-payload.v1, v2 or v3).")
    signature: str = Field(..., description="The Ed25519 signature over the payload bytes: `ed25519:` followed by standard base64 of the 64 signature bytes.")
    key_id: str = Field(..., description="The `kid` of the signing key on https://api.trooth.co/public/keys. A v3 payload names the same key inside the signed bytes, at signer.key_id.")
    alg: Literal["Ed25519"] = Field(..., description="The signature algorithm. Always Ed25519 (RFC 8032, pure EdDSA).")
    canonicalization: Literal["json-fixed-key-order-no-whitespace-utf8", "RFC8785"] = Field(..., description="How the payload bytes were produced. `json-fixed-key-order-no-whitespace-utf8` for v1 and v2; `RFC8785` (JSON Canonicalization Scheme, integers only) for v3, where the payload MUST equal the canonical form of the JSON it holds.")

EvidenceManifest = List[ManifestEntry]
"""The evidence manifest a v2 or v3 statement binds by digest, published beside the statement as `witnessEvidenceManifest`. Canonical bytes: entries sorted by check_id, each as {"check_id":..,"source":..} or {"check_id":..,"commitment":..}, no whitespace, UTF-8."""


ManifestEntry.model_rebuild()
KeyList.model_rebuild()
PublicKey.model_rebuild()
KeyEvent.model_rebuild()
VerificationBundle.model_rebuild()
BundleKeys.model_rebuild()
BundleMapping.model_rebuild()
VerifyResult.model_rebuild()
KeyTrust.model_rebuild()
Subject.model_rebuild()
Binding.model_rebuild()
CountCheck.model_rebuild()
WitnessPayloadV1.model_rebuild()
CheckV1.model_rebuild()
CountsV1.model_rebuild()
WitnessPayloadV2.model_rebuild()
Check.model_rebuild()
CheckReason.model_rebuild()
Counts.model_rebuild()
SubjectScope.model_rebuild()
Methodology.model_rebuild()
Evaluator.model_rebuild()
EvidenceManifestRef.model_rebuild()
WitnessPayloadV3.model_rebuild()
Signer.model_rebuild()
WitnessStatement.model_rebuild()
