# GENERATED by scripts/gen-types.mjs from schemas/ in github.com/troothllc/trooth-cli.
# Do not edit by hand: change the schema and run `node scripts/gen-types.mjs`.
"""Pydantic v2 models for the documents Trooth publishes about a witness statement."""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class CorrectionPayload(BaseModel):
    "The JSON a trooth.correction.v1 payload holds: Trooth withdrawing or replacing a statement it signed. Signed like a v3 statement (RFC 8785 bytes, Ed25519, the signer inside the signed bytes) and entered in the witness statement log. The statement it corrects stays in the log; nothing is deleted."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    statement: Literal["trooth.correction.v1"] = Field(..., description="The payload type.")
    correction_id: str = Field(..., description="An identifier for this correction, unique in the log.")
    supersedes: str = Field(..., description="The statement id this correction withdraws or replaces. It must already be in the log.")
    subject_id: str = Field(..., description="The subject of the statement it corrects.")
    effect: Literal["withdrawn", "replaced"] = Field(..., description="withdrawn: no statement takes its place. replaced: the replacement statement does.")
    replacement: Optional[str] = Field(..., description="The replacing statement id, which must already be in the log; null for withdrawn.")
    reason: CorrectionReason = Field(..., description="Why.")
    issued_at: str = Field(..., description="When Trooth issued it, as Trooth asserts. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    signer: Signer = Field(..., description="The signing key, inside the signed bytes.")

class CorrectionReason(BaseModel):
    "The reason for a correction."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    code: Literal["evaluator_defect", "mapping_defect", "source_misread", "signing_key_compromised", "dispute_upheld", "withdrawn_by_trooth"] = Field(..., description="evaluator_defect: the evaluator read wrongly. mapping_defect: the check mapping was wrong. source_misread: a source was misread. signing_key_compromised: the key that signed it is compromised. dispute_upheld: a dispute about the reading was upheld. withdrawn_by_trooth: withdrawn for another stated reason.")
    explanation: str = Field(..., description="The reason in words, 10 to 1000 characters.")

class DomainDeclaration(BaseModel):
    "The domain-signed declaration a company publishes at https://<domain>/.well-known/trooth.json (docs/DECLARATION.md): its own Ed25519 key, its products, its APIs and its code repositories, signed with that key over the RFC 8785 bytes of the document without `signature`. At most 64 KB. It is self-signed: a declaration that checks shows that whoever controlled the site's content when it was read published this key and these subjects; it does not establish the legal entity or a person's authority to act for it. Added in trooth 0.14.0."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    format: Literal["trooth.declaration.v1"] = Field(..., description="The format.")
    domain: str = Field(..., description="The domain, lower case. It must equal the host the document is served from.")
    issued_at: str = Field(..., description="When the declaration was signed, ISO 8601 in UTC. Not in the future.")
    expires_at: str = Field(..., description="When the declaration stops checking, ISO 8601 in UTC; after issued_at and at most 400 days after it.")
    record: Optional[str] = Field(None, description="Optional: the company's Trooth record, https://trooth.co/network/company/<slug>. The one URL not on the domain.")
    keys: List[DeclarationKey] = Field(..., description="The company's own public keys, one to eight; more than one during a key rotation. Never a private key.")
    products: Optional[List[DeclaredProduct]] = Field(None, description="Products the domain's owner names. Each url is on the domain or a subdomain of it.")
    apis: Optional[List[DeclaredApi]] = Field(None, description="APIs the domain's owner names, each with an optional MCP server and the SHA-256 of its tool manifest.")
    repositories: Optional[List[str]] = Field(None, description="Organizations or users on a code host (github.com, gitlab.com, bitbucket.org, codeberg.org) the domain's owner names.")
    signature: DeclarationSignature = Field(..., description="Ed25519 over the RFC 8785 bytes of the document without this member, by one of `keys`.")

class DeclarationKey(BaseModel):
    "An Ed25519 public key as a JWK (RFC 8037) with its id."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    kid: str = Field(..., description="<domain>#<the RFC 7638 JWK thumbprint of the key, base64url>.")
    kty: Literal["OKP"] = Field(..., description="The key type.")
    crv: Literal["Ed25519"] = Field(..., description="The curve.")
    x: str = Field(..., description="The 32-byte public key, base64url without padding.")

class DeclaredProduct(BaseModel):
    "A product the domain's owner names. Its subject id is trooth:product:<domain>/<id>."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str = Field(..., description="The product's id, unique in the declaration.")
    name: str = Field(..., description="The product's name, 1 to 200 characters.")
    url: str = Field(..., description="An https URL on the domain or a subdomain of it.")

class DeclaredMcp(BaseModel):
    "The MCP server of an API."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    url: str = Field(..., description="The MCP endpoint, an https URL on the domain or a subdomain of it.")
    manifest_sha256: str = Field(..., description="Lowercase hex SHA-256 of the server's tool manifest (docs/EVIDENCE.md section 9).")

class DeclaredApi(BaseModel):
    "An API the domain's owner names."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    base_url: str = Field(..., description="The API's base URL, https, on the domain or a subdomain of it.")
    mcp: Optional[DeclaredMcp] = Field(None, description="Optional: its MCP server.")

class DeclarationSignature(BaseModel):
    "The signature over the declaration."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    kid: str = Field(..., description="The kid of the key in `keys` that signed.")
    alg: Literal["Ed25519"] = Field(..., description="The algorithm.")
    canonicalization: Literal["RFC8785"] = Field(..., description="The canonicalization of the signed bytes.")
    value: str = Field(..., description="ed25519: and the 64-byte signature in base64.")

class ManifestEntry(BaseModel):
    "One check and the evidence behind it: a public `source`, or a `commitment` to a private one. Exactly one of the two."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    check_id: str = Field(..., description="The check id. Unique in the manifest.")
    source: Optional[str] = Field(None, description="The public URL the check read.")
    commitment: Optional[str] = Field(None, description="`sha256:` plus the hex SHA-256 of salt, a newline byte and the private reference. Only its holder can open it.")

class GuardDecision(BaseModel):
    "One decision of the Trooth guard (trooth/guard, docs/GUARD.md): allow, hold for a person, or deny an ACTION the customer's agent is about to take, under the customer's policy, with reason codes. It is made on the customer's machine and is never a statement about whether a company is safe. The contract is the one in section 8 of the Trooth Network brief; reasons may also carry a detail string. `trooth guard decide --json` prints this document when the policy covers the tool, and a GuardNotCovered ($defs/notCovered) when it does not; schemas/guard-decide-output.v1.schema.json accepts either."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    decision: Literal["allow", "hold", "deny"] = Field(..., description="allow: every required check held and every rule passed. hold: route the action to a person. deny: a proof failed or a rule the customer marked absolute failed (or the customer's policy chose deny for no record or no source).")
    reasons: List[GuardReason] = Field(..., description="Why, one entry per check or rule. An allow carries only RULE_PASSED.")
    subject: str = Field(..., description="Exact entity ID checked, e.g. trooth:domain:acme.com. Empty when the action named no host.")
    policy: GuardPolicyRef = Field(..., description="The policy the decision was made under.")
    evidence: List[GuardEvidence] = Field(..., description="The signed, logged facts the rules read.")
    action: Optional[Dict[str, Any]] = Field(None, description="The intercepted tool call: name, target host, amount or data class. Stored locally, never sent to Trooth.")
    decided_at: str = Field(..., description="When the decision was made (RFC 3339).")

class GuardNotCovered(BaseModel):
    "What `trooth guard decide --json` prints when the policy does not cover the tool: nothing was decided, nothing was read, and the command exits 0. It is not an allow and carries no decision; the caller lets the call run as its own controls intend."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    covered: Literal[False] = Field(..., description="Always false: the policy's applies_to.tools does not match the tool.")
    tool: str = Field(..., description="The tool name given with --tool.")
    policy: GuardPolicyRef = Field(..., description="The policy that does not cover the tool.")
    note: str = Field(..., description="A plain sentence saying that nothing was decided.")

class GuardReason(BaseModel):
    "One reason code, with what it is about."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    code: Literal["RULE_PASSED", "EVIDENCE_MISSING", "EVIDENCE_STALE", "EVIDENCE_DISPUTED", "NO_RECORD", "SIGNATURE_INVALID", "KEY_NOT_TRUSTED", "NOT_IN_LOG", "SUBJECT_MISMATCH", "SCHEMA_UNSUPPORTED", "ABSOLUTE_RULE_FAILED", "SOURCE_UNREACHABLE"] = Field(..., description="The reason code.")
    fact_id: Optional[str] = Field(None, description="Stable ID of the fact this reason is about")
    rule_id: Optional[str] = Field(None, description="The customer's rule that produced this reason")
    needed: Optional[str] = Field(None, description="For EVIDENCE_MISSING: the claim type that would satisfy the rule")
    detail: Optional[str] = Field(None, description="A plain sentence on what was found. Written by the guard, never copied from vendor content.")

class GuardPolicyRef(BaseModel):
    "Which policy, by id, version and the SHA-256 of its RFC 8785 canonical JSON."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str = Field(..., description="The policy's name (its `policy` key).")
    version: int = Field(..., description="The policy's version number.")
    sha256: str = Field(..., description="SHA-256 (hex) of the RFC 8785 canonical JSON of the policy as parsed.")

class GuardEvidence(BaseModel):
    "One signed, logged fact a rule read."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    fact_id: str = Field(..., description="trooth:statement:<sha256>#<claim>: the statement and the claim read from it.")
    statement_sha256: str = Field(..., description="SHA-256 (hex) of the statement's exact payload bytes.")
    log_index: Optional[int] = Field(..., description="The statement's entry in Trooth's log, or null when it is not shown in the log.")
    observed_at: str = Field(..., description="When the fact was observed.")
    stale_after: Optional[str] = Field(..., description="When the fact stops being fresh for this rule (the rule's max_age_days, else the evidence class's stale-after), or null when unknown.")

class GuardPolicy(BaseModel):
    "A customer's guard policy (docs/GUARD.md section 3), written in YAML (the strict subset bin/lib/yaml-lite.mjs reads) or JSON. The guard refuses unknown keys, wrong types, duplicate rule ids, on_fail deny without absolute, and allow for source_unreachable or failMode. The policy's sha256 is the SHA-256 of the RFC 8785 canonical JSON of the document as parsed."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    policy: str = Field(..., description="The policy's name.")
    version: int = Field(..., description="The policy's version number; raise it on every change.")
    description: Optional[str] = Field(None, description="Free text for people; the guard never reads it.")
    applies_to: GuardAppliesTo = Field(..., description="Which actions are checked. Everything else passes straight through.")
    host_from: Optional[List[str]] = Field(None, description="Typed argument fields (dotted paths allowed) the target host is read from, in order. Default: url, endpoint, host, domain, base_url, webhook_url, email, to.")
    log: Optional[GuardLogRequirement] = Field(None, description="What the guard needs from Trooth's log. Default: required true, min_witnesses 1.")
    rules: List[GuardRule] = Field(..., description="The rules, each tested against signed, logged facts. Rule ids are unique.")
    destinations: Optional[GuardDestinations] = Field(None, description="Hosts for CI mode (trooth guard ci).")
    unknown_counterparty: Optional[Literal["hold", "deny"]] = Field(None, description="The decision when no Trooth record exists for the host. Default hold.")
    source_unreachable: Optional[Literal["hold", "deny"]] = Field(None, description="The decision when no Trooth source answers and no cached bundle is held. Default hold. allow is refused.")

class GuardAppliesTo(BaseModel):
    "The tools and HTTP destinations the policy covers."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    tools: Optional[List[str]] = Field(None, description="Tool names; \"*\" stands for any run of characters (mcp__bank__*).")
    http: Optional[List[GuardHttpTarget]] = Field(None, description="For the http adapter: methods and host patterns whose requests are checked.")

class GuardHttpTarget(BaseModel):
    "One method and host pattern (an exact host, or *. followed by a domain of at least two labels)."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    method: str = Field(..., description="The HTTP method, or * for any.")
    host: str = Field(..., description="The host pattern.")

class GuardLogRequirement(BaseModel):
    "Log inclusion and witness cosignatures the policy asks for."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    required: Optional[bool] = Field(None, description="Whether a statement must be shown in the log (hold NOT_IN_LOG otherwise). A failed proof denies either way.")
    min_witnesses: Optional[int] = Field(None, description="How many pinned witnesses must have cosigned a checkpoint covering the statement.")

class GuardRule(BaseModel):
    "One rule. A claim missing, stale or disputed holds; a rule marked absolute that fails denies."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str = Field(..., description="The rule's id, unique in the policy.")
    description: Optional[str] = Field(None, description="Free text for people; the guard never reads it.")
    require: Union[GuardClaimRequire, GuardSignatureRequire] = Field(..., description="A claim with an optional maximum age, or a valid signature by a key in an accepted state.")
    on_fail: Optional[Literal["hold", "deny"]] = Field(None, description="hold (default), or deny for a rule marked absolute.")
    absolute: Optional[bool] = Field(None, description="When true, the rule failing denies the action (ABSOLUTE_RULE_FAILED).")

class GuardClaimRequire(BaseModel):
    "A claim read from a signed, logged Trooth artifact."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    claim: str = Field(..., description="trooth_reading, check:<check_id>, legal_entity_registry_record, no_sanctions_name_match, no_sam_exclusion_name_match, domain_registration_record, security_txt_published, or domain_control_confirmed (since trooth 0.14.0, from a confirmed proof in the signed public record binding the domain to the company record or to its declaration key).")
    max_age_days: Optional[int] = Field(None, description="The oldest observation the rule accepts, in days. Default: the evidence class's stale-after.")

class GuardSignatureRequire(BaseModel):
    "A valid signature by a key in one of the accepted states at signing time."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    signature: Literal["valid"] = Field(..., description="Always valid.")
    key_status: Optional[List[Literal["active", "retired_before_use"]]] = Field(None, description="Accepted key states. Default both.")

class GuardDestinations(BaseModel):
    "For CI mode: hosts a build may add, and the hosts to watch."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    allowed: Optional[List[str]] = Field(None, description="Host patterns a build may add without failing.")
    watch: Optional[List[str]] = Field(None, description="Host patterns CI mode reports when added and not allowed. Default (empty): every new external host.")

class KeyList(BaseModel):
    "The body of https://api.trooth.co/public/keys, or a saved copy of it. Save it with the time you read it: a saved list cannot show a compromise announced later."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    keys: List[PublicKey] = Field(..., description="Every key, current and past.")
    list_read_at: Optional[str] = Field(None, description="When the list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    active_kid: Optional[str] = Field(None, description="The kid of the key currently used for new statements.")
    note: Optional[str] = Field(None, description="A note from the key service.")

class PublicKey(BaseModel):
    "One published key and its lifecycle. Only `kid`, `alg`, `encoding`, `public_key`, `status` and the three lifecycle times decide trust (docs/VERIFY.md section 3)."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    kid: str = Field(..., description="The key id a statement names in key_id.")
    alg: Literal["Ed25519"] = Field(..., description="Always Ed25519.")
    encoding: Optional[Literal["hex", "base64"]] = Field(None, description="How public_key is written: hex or base64.")
    public_key: str = Field(..., description="The 32-byte Ed25519 public key, in `encoding`.")
    status: Literal["active", "retired", "revoked", "compromised"] = Field(..., description="active, retired, revoked or compromised.")
    state: Optional[str] = Field(None, description="The same lifecycle state as written by the key service.")
    retired_at: Optional[str] = Field(None, description="When the key was retired. Statements carrying a read_at strictly before this stay trusted. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    compromised_at: Optional[str] = Field(None, description="When the key was found compromised. Nothing signed by it is relied on. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    revoked_at: Optional[str] = Field(None, description="When the key was revoked. A revocation with no compromise recorded is treated as a compromise. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    created_at: Optional[str] = Field(None, description="When the key was created, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    activated_at: Optional[str] = Field(None, description="When the key was first used, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    first_listed_at: Optional[str] = Field(None, description="When the key first appeared on the list. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    fingerprint: Optional[str] = Field(None, description="A short fingerprint of the key, for display.")
    purpose: Optional[str] = Field(None, description="What the key is for, as a short label.")
    signs: Optional[str] = Field(None, description="What the key signs, in words.")
    events: Optional[List[KeyEvent]] = Field(None, description="Lifecycle events, oldest first.")

class KeyEvent(BaseModel):
    "One lifecycle event of a key."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    event: str = Field(..., description="What happened (for example first_listed, retired, compromised).")
    at: str = Field(..., description="When. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    note: Optional[str] = Field(None, description="A note, or null.")

class LogReceipt(BaseModel):
    "A receipt from Trooth's witness statement log (docs/LOG.md): the entry index, a checkpoint signed by the log key, and an RFC 9162 inclusion proof from the entry to the checkpoint root. The entry is RFC 8785 JSON of {kind, statement}; its leaf hash is SHA-256(0x00 || entry)."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    log: Literal["trooth.co/witness-log/v1"] = Field(..., description="The log origin, which the checkpoint must also name.")
    index: int = Field(..., description="The zero-based entry index.")
    tree_size: int = Field(..., description="The size of the signed tree the proof is against. Equals the checkpoint size.")
    root_hash: str = Field(..., description="Standard base64 of the 32-byte root at tree_size. Equals the checkpoint root.")
    inclusion_proof: List[str] = Field(..., description="The RFC 9162 audit path, leaf to root, each a 32-byte hash in standard base64.")
    checkpoint: str = Field(..., description="A C2SP checkpoint (origin, size, base64 root, each on its own line) followed by a blank line and C2SP signed-note signature lines; the log key's line is an em dash, the key name and base64 of the 4-byte key hash and the 64-byte Ed25519 signature.")

class McpToolsStatement(BaseModel):
    "The payload Trooth signs for an MCP tool reading, carried as the payload of a witness-statement envelope (RFC 8785, Ed25519) and logged as an mcp_tools entry. It names every tool's description and definition hash, so the log alone tells when a server changed what it tells agents."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    statement: Literal["trooth.mcp-tools.v1"] = Field(..., description="The payload type.")
    subject_id: str = Field(..., description="trooth:mcp:<host and path>.")
    endpoint: str = Field(..., description="The endpoint read.")
    read_at: str = Field(..., description="The reading's read_at. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    manifest_sha256: str = Field(..., description="The manifest hash.")
    tools: List[StatementTool] = Field(..., description="Each tool's hashes, sorted by name.")
    previous_manifest_sha256: Optional[str] = Field(..., description="The previous manifest hash, or null for the first reading.")
    reading_sha256: str = Field(..., description="SHA-256, hex, of the reading's RFC 8785 bytes.")
    reading_canonicalization: Literal["RFC8785"] = Field(..., description="How those bytes were made.")
    issued_at: str = Field(..., description="When the statement was signed. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    signer: McpStatementSigner = Field(..., description="The signing key, inside the signed bytes.")

class StatementTool(BaseModel):
    "A tool as the statement names it."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str = Field(..., description="The tool name.")
    description_sha256: str = Field(..., description="The description hash.")
    definition_sha256: str = Field(..., description="The definition hash.")

class McpStatementSigner(BaseModel):
    "The signing key."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    key_id: str = Field(..., description="The kid on https://api.trooth.co/public/keys.")
    issuer: Literal["trooth.co"] = Field(..., description="Always trooth.co.")

class McpToolsReading(BaseModel):
    "The tool list of an MCP server as Trooth read it with no credentials, each tool's description and definition hashed. Served at https://api.trooth.co/scan/mcp-tools/reading?endpoint=<url>. A statement naming the reading is signed and logged as an mcp_tools entry when the manifest changed. docs/EVIDENCE.md section 9 in trooth-cli is the normative text. A hash says what was listed, not that a tool does what its description says."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    format: Literal["trooth.mcp-tools.v1"] = Field(..., description="The format.")
    endpoint: str = Field(..., description="The MCP endpoint read (streamable HTTP).")
    subject_id: str = Field(..., description="trooth:mcp:<host and path>.")
    read_at: str = Field(..., description="When it was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    server: McpServer = Field(..., description="What the server said about itself in initialize.")
    tools: List[ToolHash] = Field(..., description="Every tool listed, sorted by name, at most 500.")
    manifest_sha256: str = Field(..., description="SHA-256, hex, of the RFC 8785 bytes of [{name, definition_sha256}] sorted by name.")
    previous: Optional[PreviousManifest] = Field(..., description="The manifest of the reading before this one, or null for the first.")
    changed: Optional[ManifestDiff] = Field(..., description="Tools added, removed or changed since the previous reading, or null for the first.")
    note: str = Field(..., description="What the reading is and is not.")
    last_checked: Optional[str] = Field(None, description="When Trooth last read the server and found this manifest. Served beside the reading; not part of the bytes it names.")
    signed: Optional[McpToolsSigned] = Field(None, description="The statement naming the reading, and its log receipt. Not part of the bytes it names.")

class McpServer(BaseModel):
    "The server's own description."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: Optional[str] = Field(..., description="serverInfo.name.")
    version: Optional[str] = Field(..., description="serverInfo.version.")
    protocol_version: Optional[str] = Field(..., description="The protocol version agreed.")

class ToolHash(BaseModel):
    "One tool as listed."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str = Field(..., description="The tool name.")
    title: Optional[str] = Field(..., description="The title, from the tool or its annotations.")
    description: str = Field(..., description="The description as listed (empty when there is none).")
    description_sha256: str = Field(..., description="SHA-256, hex, of the description's UTF-8 bytes.")
    definition_sha256: str = Field(..., description="SHA-256, hex, of the RFC 8785 bytes of the whole tool object as listed.")

class PreviousManifest(BaseModel):
    "The reading before."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    manifest_sha256: str = Field(..., description="Its manifest hash.")
    read_at: str = Field(..., description="When it was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")

class ManifestDiff(BaseModel):
    "Tool names by what happened to them."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    added: List[str] = Field(..., description="Tools new in this reading.")
    removed: List[str] = Field(..., description="Tools no longer listed.")
    changed: List[str] = Field(..., description="Tools whose definition hash changed.")

class McpToolsSigned(BaseModel):
    "The statement naming the reading."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    reading_sha256: str = Field(..., description="SHA-256, hex, of the RFC 8785 bytes of the reading without last_checked and signed.")
    statement: Optional[WitnessStatement] = Field(..., description="The signed envelope; its payload is an mcp-tools-statement.v1 document. Null when it could not be signed.")
    statement_id: Optional[str] = Field(..., description="trooth:statement:<sha256 of the payload>.")
    log: Optional[LogReceipt] = Field(..., description="The receipt of the statement as an mcp_tools entry, or null when it was not logged.")
    problem: Optional[str] = Field(..., description="What could not be done, or null.")
    logged_at_read: Optional[str] = Field(..., description="The read_at of the reading that was logged.")

class PublicRecordStatement(BaseModel):
    "The payload Trooth signs for a public record reading: it names the reading by the SHA-256 of its RFC 8785 bytes. Carried as the `payload` of a witness-statement envelope (RFC 8785, Ed25519) under `signed.statement` in a reading, and logged as a public_record entry. The signature says what Trooth read and when, not that what the sources say is true."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    statement: Literal["trooth.public-record.v1"] = Field(..., description="The payload type.")
    subject_id: str = Field(..., description="trooth:domain:<domain>.")
    domain: str = Field(..., description="The domain read.")
    read_at: str = Field(..., description="The reading's read_at. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    record_sha256: str = Field(..., description="SHA-256, hex, of the reading's RFC 8785 bytes without `signed`.")
    record_canonicalization: Literal["RFC8785"] = Field(..., description="How those bytes were made.")
    entity_id: Optional[str] = Field(..., description="The reading's entity id, or null.")
    bindings: List[BindingStatus] = Field(..., description="Each binding's id and status.")
    sources: int = Field(..., description="How many responses the reading read.")
    issued_at: str = Field(..., description="When the statement was signed. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    signer: StatementSigner = Field(..., description="The signing key, inside the signed bytes.")

class BindingStatus(BaseModel):
    "A binding as the statement names it."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str = Field(..., description="trooth:cik or trooth:lei id.")
    status: str = Field(..., description="The binding status.")

class StatementSigner(BaseModel):
    "The signing key."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    key_id: str = Field(..., description="The kid on https://api.trooth.co/public/keys.")
    issuer: Literal["trooth.co"] = Field(..., description="Always trooth.co.")

class PublicRecordReading(BaseModel):
    "What a company has published outside its own website, read from the authorities that hold it (SEC EDGAR, the GLEIF LEI registry, DNS, a Certificate Transparency monitor, the OFAC list, and since trooth 0.12.0 SAM.gov, the USPTO, four state registries, the FTC and RDAP), beside what its own site states, and the evidence tying each identifier to the domain. Served at https://api.trooth.co/scan/public-record/<domain>. Every fact carries the URL to read it again. Since trooth 0.11.0 each reading also carries `signed`: a statement naming the SHA-256 of the reading's RFC 8785 bytes (everything except `signed`), signed with Trooth's statement key and logged. Nothing in it grades, rates or ranks a company. docs/EVIDENCE.md in trooth-cli is the normative text."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    format: Literal["trooth.public-record.v1"] = Field(..., description="The format.")
    domain: str = Field(..., description="The domain read.")
    subject_id: str = Field(..., description="trooth:domain:<domain>.")
    read_at: str = Field(..., description="When Trooth read the sources. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    site: SiteRead = Field(..., description="What the company's own pages say about which legal entity it is.")
    bindings: List[EntityBinding] = Field(..., description="Each identifier found and the evidence for and against tying it to the domain.")
    sec: Optional[SecRecord] = Field(..., description="The SEC filer's record, or null when no filer was identified.")
    lei: Optional[LeiRecord] = Field(..., description="The LEI record, or null when none was identified.")
    dns: List[PublicFact] = Field(..., description="Mail-authentication records beyond SPF and DMARC, and DNSSEC.")
    entity: Optional[Entity] = Field(None, description="The legal entity the domain is tied to, when a binding is corroborated; null otherwise. Added in trooth 0.11.0.")
    certificates: Optional[Certificates] = Field(None, description="Unexpired certificates for the exact domain name in Certificate Transparency logs, as a CT monitor returned them; null when it did not answer. Added in trooth 0.11.0.")
    security_txt: Optional[SecurityTxt] = Field(None, description="The site's /.well-known/security.txt (RFC 9116), or null when there is none or the site opted out of being read. Added in trooth 0.11.0.")
    sanctions: Optional[Sanctions] = Field(None, description="Entries on the OFAC sanctions list with exactly the legal names above. A name match is not an identification. Null when the list could not be read or no name was found. Added in trooth 0.11.0.")
    sources: Optional[List[Source]] = Field(None, description="Every response read for this reading, with the SHA-256 of the bytes read; Trooth keeps the bytes under that hash so a disputed fact can be replayed. Added in trooth 0.11.0.")
    not_read: List[NotRead] = Field(..., description="Each source that was not read, or did not answer, and why. A source not read is never guessed at.")
    note: str = Field(..., description="What the reading is and is not, as a paragraph.")
    sam: Optional[SamReading] = Field(None, description="SAM.gov registrations and exclusions under the legal name, or null when SAM.gov was not read (not_read says why). A name match is not an identification. Added in trooth 0.12.0.")
    patents: Optional[PatentReading] = Field(None, description="Patent applications whose first applicant is the legal name, from the USPTO Open Data Portal, or null when it was not read. Added in trooth 0.12.0.")
    registries: Optional[List[RegistryEntry]] = Field(None, description="Exact-name entries in the state business registries that publish open data (New York, Colorado, Connecticut, Oregon). A name match is not an identification. Added in trooth 0.12.0.")
    merger_review: Optional[MergerReview] = Field(None, description="Hart-Scott-Rodino early termination notices the FTC published naming the legal name as a party, or null when they were not read. Added in trooth 0.12.0.")
    domain_registration: Optional[DomainRegistration] = Field(None, description="The domain's registration, from RDAP, or null when no RDAP service answered. Added in trooth 0.12.0.")
    changes: Optional[List[Change]] = Field(None, description="What the sources in this reading record as having changed (renames, acquisitions and dispositions, changes in control, previous legal names, parents, merger review, domain registration), newest first. Added in trooth 0.12.0.")
    subjects: Optional[List[NamedSubject]] = Field(None, description="Every subject this reading names, each with why: the domain, the entity, filer and LEI ids, jurisdictions, state registry entries, SAM.gov UEIs, and the code repositories, APIs and MCP servers the home page links to (docs/IDS.md). Added in trooth 0.12.0.")
    evidence_classes: Optional[List[EvidenceClass]] = Field(None, description="Each class of evidence in this reading with its stale-after rule, when it was observed and what it does not establish (docs/EVIDENCE.md section 10). Optional; added in trooth 0.13.0.")
    continuity: Optional[Continuity] = Field(None, description="What changed since the previous cached reading of the same domain (docs/EVIDENCE.md section 10). Optional; added in trooth 0.13.0.")
    proofs: Optional[List[Proof]] = Field(None, description="Each proof that binds two subjects, with its method and status (docs/EVIDENCE.md section 11): the domain to the company record (dns_txt, domain_email_code or identity_provider_sign_in, from Trooth's record of the claim or the challenge TXT), the domain to the company's own key (domain_signed_declaration, and dns_txt when the key pin matches), the domain to a code repository (repository_control). Optional; added in trooth 0.14.0.")
    declaration: Optional[DeclarationReading] = Field(None, description="The domain-signed declaration read at https://<domain>/.well-known/trooth.json (docs/DECLARATION.md), or null when it was not looked for. Only what checked is carried into subjects. Optional; added in trooth 0.14.0.")
    signed: Optional[Signed] = Field(None, description="The statement that names this reading, and its log receipt. Not part of the bytes it names. Added in trooth 0.11.0.")

class SamReading(BaseModel):
    "SAM.gov, read under one legal name with Trooth's key (the key is never in the record). Cached for 30 days per name, so read_at can be earlier than the reading's."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    source: str = Field(..., description="The SAM.gov API read.")
    read_at: str = Field(..., description="When SAM.gov was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    names_checked: List[str] = Field(..., description="The legal names searched.")
    registrations: List[SamRegistration] = Field(..., description="Entity registrations with exactly that legal name, at most 10.")
    exclusions: List[SamExclusion] = Field(..., description="Exclusion records with exactly that name, at most 20. A name match is not an identification.")

class SamRegistration(BaseModel):
    "A SAM.gov entity registration."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    uei: Optional[str] = Field(..., description="The Unique Entity ID.")
    cage: Optional[str] = Field(..., description="The CAGE code.")
    legal_name: str = Field(..., description="The legal business name registered.")
    status: Optional[str] = Field(..., description="The registration status.")
    expires: Optional[str] = Field(..., description="The registration expiration date.")
    purpose: Optional[str] = Field(..., description="The purpose of registration.")

class SamExclusion(BaseModel):
    "A SAM.gov exclusion record."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str = Field(..., description="The name excluded.")
    uei: Optional[str] = Field(..., description="The UEI on the record.")
    cage: Optional[str] = Field(..., description="The CAGE code on the record.")
    classification: Optional[str] = Field(..., description="Firm, Individual, Vessel or Special Entity Designation.")
    type: Optional[str] = Field(..., description="The exclusion type.")
    program: Optional[str] = Field(..., description="The exclusion program.")
    agency: Optional[str] = Field(..., description="The excluding agency.")
    active: Optional[str] = Field(..., description="The activation date.")
    terminates: Optional[str] = Field(..., description="The termination date, or Indefinite.")
    record_status: Optional[str] = Field(..., description="The record status.")

class PatentReading(BaseModel):
    "Patent applications from the USPTO Open Data Portal. Cached for 7 days per name."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    source: str = Field(..., description="The search API read.")
    read_at: str = Field(..., description="When it was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    applicant_names: List[str] = Field(..., description="The first-applicant names searched.")
    applications: int = Field(..., description="How many applications the search counted.")
    recent: List[PatentApplication] = Field(..., description="The newest applications, at most 5.")

class PatentApplication(BaseModel):
    "A patent application."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    application: str = Field(..., description="The application number.")
    title: Optional[str] = Field(..., description="The title of the invention.")
    filed: Optional[str] = Field(..., description="The filing date.")
    status: Optional[str] = Field(..., description="The application status.")
    patent: Optional[str] = Field(..., description="The patent number, once granted.")
    granted: Optional[str] = Field(..., description="The grant date.")

class RegistryEntry(BaseModel):
    "An entry in a state business registry with exactly the legal name."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    jurisdiction: str = Field(..., description="The registry's jurisdiction, ISO 3166-2.")
    registry: str = Field(..., description="The registry and dataset.")
    id: str = Field(..., description="The entity's number in that registry.")
    name: str = Field(..., description="The name as registered.")
    status: Optional[str] = Field(..., description="The status the registry gives (Active for the datasets of active entities only).")
    entity_type: Optional[str] = Field(..., description="The entity type.")
    formed: Optional[str] = Field(..., description="The formation or registration date in that state.")
    formation_jurisdiction: Optional[str] = Field(..., description="Where the entity was formed, as the registry writes it.")
    source: str = Field(..., description="The open-data URL for this entry.")

class MergerReview(BaseModel):
    "FTC early termination notices under the HSR Act, searched by words of the legal name and kept when a party has exactly that name. Cached for 7 days per name."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    source: str = Field(..., description="The FTC API read.")
    read_at: str = Field(..., description="When it was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    names_checked: List[str] = Field(..., description="The legal names searched.")
    notices: List[MergerNotice] = Field(..., description="Notices naming the company as a party, at most 20.")
    matched_in_search: int = Field(..., description="How many notices the word search returned before names were compared.")

class MergerNotice(BaseModel):
    "An early termination notice."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    transaction: str = Field(..., description="The HSR transaction number.")
    date: Optional[str] = Field(..., description="The date early termination was granted.")
    acquiring: Optional[str] = Field(..., description="The acquiring person.")
    acquired: Optional[str] = Field(..., description="The acquired person.")
    acquired_entities: List[str] = Field(..., description="The acquired entities named.")
    role: Literal["acquiring", "acquired"] = Field(..., description="The company's role in the notice.")
    url: str = Field(..., description="The notice on ftc.gov.")

class DomainRegistration(BaseModel):
    "A domain's registration from RDAP (RFC 9083)."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    source: str = Field(..., description="The RDAP URL read.")
    registrar: Optional[str] = Field(..., description="The registrar.")
    registered: Optional[str] = Field(..., description="The registration date.")
    changed: Optional[str] = Field(..., description="The last-changed date.")
    expires: Optional[str] = Field(..., description="The expiration date.")
    transferred: Optional[str] = Field(..., description="The last transfer date.")
    status: List[str] = Field(..., description="EPP status values.")

class Change(BaseModel):
    "A change a source records."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    kind: Literal["renamed", "previous_legal_name", "acquisition_or_disposition", "change_in_control", "merger_review", "parent", "domain_registered", "domain_transferred"] = Field(..., description="What changed.")
    date: Optional[str] = Field(..., description="When, as the source dates it; null when it gives no date.")
    detail: str = Field(..., description="The change in words.")
    source: str = Field(..., description="Where to read it.")

class NamedSubject(BaseModel):
    "A subject the reading names (docs/IDS.md)."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str = Field(..., description="The Trooth id.")
    kind: Literal["domain", "entity", "sec_filer", "lei", "jurisdiction", "state_registry", "sam_uei", "code_repository", "api", "mcp_server", "representative", "signing_authority", "company", "product", "person"] = Field(..., description="What it names. representative: a contact the site publishes in security.txt (a trooth:contact id); not a person authorized to act for the entity. signing_authority: the key that signed this reading's statement (a trooth:key id), named at signing. Since trooth 0.14.0: company: the company's Trooth record (a trooth:company id). product: a product named in the domain's signed declaration (trooth:product:<domain>/<id>); never inferred from a name match. person: the representative Trooth recorded at claim time (trooth:person:<16 hex>); no personal data in the id. signing_authority is also the company's own key (trooth:key:<domain>#<thumbprint>) from a declaration that checks. api from the declaration names the MCP manifest hash in basis. code_repository is marked repository_control when that proof is confirmed.")
    basis: str = Field(..., description="Why the reading names it.")

class Entity(BaseModel):
    "A legal entity, named by a Trooth id derived from its LEI or SEC CIK (docs/IDS.md)."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str = Field(..., description="trooth:entity:lei:<LEI> when the LEI binding is corroborated, otherwise trooth:entity:cik:<CIK>.")
    name: Optional[str] = Field(..., description="The legal name the registry holds.")
    identifiers: List[str] = Field(..., description="The corroborated identifiers (trooth:lei, trooth:cik).")
    basis: str = Field(..., description="Which bindings are corroborated.")

class Certificates(BaseModel):
    "Certificates for the exact domain name in Certificate Transparency logs."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    source: str = Field(..., description="The CT monitor URL read.")
    unexpired: int = Field(..., description="How many unexpired certificates the monitor returned.")
    issuers: List[str] = Field(..., description="The issuing authorities, at most 10.")
    newest_issued: Optional[str] = Field(..., description="The latest not-before time.")
    soonest_expiry: Optional[str] = Field(..., description="The earliest not-after time.")
    page_full: bool = Field(..., description="True when the monitor's first page was full, so there may be more.")

class SecurityTxt(BaseModel):
    "A security.txt file (RFC 9116)."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    url: str = Field(..., description="Where it was read.")
    contacts: List[str] = Field(..., description="Contact fields, at most 5.")
    expires: Optional[str] = Field(..., description="The Expires field.")
    expired: Optional[bool] = Field(..., description="Whether Expires was in the past when read; null when it does not parse.")
    policy: Optional[str] = Field(..., description="The Policy field.")
    canonical: List[str] = Field(..., description="Canonical fields.")
    signed: bool = Field(..., description="Whether the file is OpenPGP clear-signed. The signature is not checked.")

class Sanctions(BaseModel):
    "An exact-name check against a sanctions list."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    list: str = Field(..., description="The list and the part of it read.")
    source: str = Field(..., description="The list URL.")
    read_at: str = Field(..., description="When the list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    names_checked: List[str] = Field(..., description="The legal names checked.")
    matches: List[SanctionsEntry] = Field(..., description="Entries with exactly one of those names (case, punctuation and suffix spellings folded). A name match is not an identification.")

class SanctionsEntry(BaseModel):
    "A list entry."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    uid: str = Field(..., description="The entry number on the list.")
    name: str = Field(..., description="The name as listed.")
    programs: str = Field(..., description="The sanctions programs.")

class Source(BaseModel):
    "One response read."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    url: str = Field(..., description="The URL requested.")
    status: int = Field(..., description="The HTTP status.")
    sha256: str = Field(..., description="SHA-256 of the bytes read, hex.")
    bytes: int = Field(..., description="How many bytes were read.")
    complete: bool = Field(..., description="False when only the start of the document was read (a filing's first 256 KB).")
    fetched_at: str = Field(..., description="When it was requested. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")

class Signed(BaseModel):
    "The statement naming the reading, and its log receipt."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    record_sha256: str = Field(..., description="SHA-256, hex, of the RFC 8785 bytes of the reading without `signed` (finite numbers in ECMAScript shortest form).")
    record_canonicalization: Literal["RFC8785"] = Field(..., description="How those bytes were made.")
    statement: Optional[WitnessStatement] = Field(..., description="The signed envelope; its payload is a public-record-statement.v1 document. Null when the reading could not be signed.")
    statement_id: Optional[str] = Field(..., description="trooth:statement:<sha256 of the payload>.")
    log: Optional[LogReceipt] = Field(..., description="The receipt of the statement as a public_record entry of the witness statement log, or null when it was not logged.")
    problem: Optional[str] = Field(..., description="What could not be done (not signed, or signed and not logged), or null.")

class PublicFact(BaseModel):
    "One fact as its source published it, with the URL it was read from."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    key: str = Field(..., description="A stable key, source.field (for example sec.tickers, lei.jurisdiction, dns.mta_sts).")
    label: str = Field(..., description="The fact as words.")
    value: Union[str, float, bool, None, List[str]] = Field(..., description="The value as published: text, a number, true or false, a list of text, or null when the source states nothing.")
    source: str = Field(..., description="Where it was read: a URL, or dns:<name> <type> for a DNS record.")

class BindingEvidence(BaseModel):
    "One piece of evidence for or against a binding."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    kind: str = Field(..., description="For: filing_namespace_names_domain, registry_lists_domain, through_corroborated_filer (these tie the identifier to the domain), site_names_registry_name (a claim by the site), registries_agree, edgar_names_lei. Against: registry_lists_other_domain, registries_disagree, edgar_names_other_lei.")
    detail: str = Field(..., description="What was seen, as a sentence.")
    source: Optional[str] = Field(..., description="Where it was seen, or null when it follows from other evidence.")

class EntityBinding(BaseModel):
    "A link between the domain and a legal-entity identifier, with the evidence for and against it. Nothing is asserted beyond the evidence."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    identifier: Literal["cik", "lei"] = Field(..., description="cik (SEC Central Index Key) or lei (Legal Entity Identifier).")
    value: str = Field(..., description="The identifier: 10 digits for a CIK, 20 characters for an LEI.")
    id: str = Field(..., description="The stable id: trooth:cik:<10 digits> or trooth:lei:<LEI> (docs/IDS.md).")
    found_by: Literal["asked", "ticker", "site_legal_name", "edgar_lei_field", "registry_name_match"] = Field(..., description="How the identifier was found: asked (given by the requester), ticker, site_legal_name (the legal name the site states matched exactly one listed SEC filer), edgar_lei_field, registry_name_match (exact legal name and, when the SEC gives one, the jurisdiction).")
    status: Literal["corroborated", "claimed_by_site", "registries_only", "uncorroborated", "contradicted", "not_found"] = Field(..., description="corroborated: authoritative evidence ties it to the domain (the company's own filing or the registry record names the domain). claimed_by_site: the site names this entity, and nothing authoritative ties it. registries_only: registries agree with each other, nothing ties the domain. uncorroborated: no evidence either way. contradicted: authoritative evidence points elsewhere. not_found: the registry holds no such identifier.")
    proof_method: Optional[Literal["regulator_filing", "registry_record", "site_statement", "registry_name_match", "asked", "none", "dns_txt", "domain_signed_declaration", "identity_provider_sign_in", "domain_email_code", "repository_control"]] = Field(None, description="What ties the identifier to the domain, strongest first. regulator_filing: the company's 10-K XBRL namespace names the domain. registry_record: the LEI registry record lists the domain. site_statement: the site states the legal name; this is the site's claim. registry_name_match: a name match only; nothing ties the domain. asked: the caller supplied the identifier and nothing above ties it. none: no evidence ties it. Optional; added in trooth 0.13.0 (docs/EVIDENCE.md section 10). dns_txt: a TXT record in the domain's zone (Trooth's claim challenge at _trooth-challenge.<domain> with a value starting trooth-domain-challenge=, or the key pin trooth-key=<thumbprint> at _trooth-key.<domain>). domain_signed_declaration: a /.well-known/trooth.json that checks (docs/DECLARATION.md). identity_provider_sign_in: the publisher signed in through the company's identity provider at the domain (Google Workspace hosted domain or Microsoft Entra tenant), as Trooth recorded at claim time. domain_email_code: a code sent to a mailbox at the domain, as Trooth recorded at claim time. repository_control: the code host marks a domain of the organization as confirmed by the code host (GitHub is_verified). The five values after none were added in trooth 0.14.0.")
    for_: List[BindingEvidence] = Field(..., alias="for", description="Evidence for the binding.")
    against: List[BindingEvidence] = Field(..., description="Evidence against it.")

class Filing(BaseModel):
    "One SEC filing, as EDGAR lists it."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    form: str = Field(..., description="The form type (10-K, 10-Q, 8-K, DEF 14A, 20-F ...).")
    filed: str = Field(..., description="The filing date, YYYY-MM-DD.")
    report_date: Optional[str] = Field(..., description="The period or event date, when EDGAR gives one.")
    items: List[str] = Field(..., description="For an 8-K, the item numbers it reports (for example 1.05, 4.01).")
    description: Optional[str] = Field(..., description="EDGAR's description of the primary document.")
    url: str = Field(..., description="The primary document on www.sec.gov.")

class FinancialFact(BaseModel):
    "A value the company filed in XBRL, as it filed it: the latest annual (10-K, full fiscal year) value of the concept."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    tag: str = Field(..., description="The XBRL concept, taxonomy:Name.")
    label: str = Field(..., description="The concept as words.")
    value: float = Field(..., description="The value as filed.")
    unit: str = Field(..., description="The unit (USD).")
    period_start: Optional[str] = Field(..., description="The period start for a flow such as revenue; null for a balance such as assets.")
    period_end: str = Field(..., description="The period end.")
    form: str = Field(..., description="The form the value was filed in.")
    filed: str = Field(..., description="The filing date.")
    accession: str = Field(..., description="The accession number of that filing.")
    source: str = Field(..., description="The data.sec.gov URL the value was read from.")

class SiteRead(BaseModel):
    "The legal names the company's pages state in copyright notices."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    legal_names: List[SiteName] = Field(..., description="Each legal name stated, with the page.")
    read: bool = Field(..., description="Whether any page of the site could be read.")
    reason: Optional[str] = Field(..., description="Why no name was found, or why the site was not read (for example its robots.txt opts out).")
    links: Optional[List[SiteLink]] = Field(None, description="Pages the home page links to on the company's own domain: investor relations, trust center, security, status, sustainability. Linked, not read. Added in trooth 0.11.0.")

class SiteLink(BaseModel):
    "A page the home page links to."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    kind: Literal["investor_relations", "trust_center", "security", "status", "sustainability"] = Field(..., description="What the page is.")
    url: str = Field(..., description="The link, without query or fragment.")

class SiteName(BaseModel):
    "A legal name a page states."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str = Field(..., description="The name as written.")
    source: str = Field(..., description="The page.")

class SecRecord(BaseModel):
    "The SEC filer's registration facts, filings and annual XBRL values."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    cik: str = Field(..., description="The Central Index Key, 10 digits.")
    facts: List[PublicFact] = Field(..., description="Registration facts on file with the SEC.")
    latest: Dict[str, Filing] = Field(..., description="The latest filing of each key form type, keyed by form.")
    events: List[Filing] = Field(..., description="8-K filings of the last two years, newest first, at most 50.")
    events_cover_since: Optional[str] = Field(..., description="The earliest date the events cover.")
    cybersecurity_incidents: List[Filing] = Field(..., description="8-K filings reporting Item 1.05, a material cybersecurity incident.")
    auditor_changes: List[Filing] = Field(..., description="8-K filings reporting Item 4.01, a change of certifying accountant.")
    non_reliance: List[Filing] = Field(..., description="8-K filings reporting Item 4.02, non-reliance on financial statements issued before.")
    insider_forms_last_90_days: int = Field(..., description="Forms 3, 4 and 5 filed in the last 90 days.")
    financials: List[FinancialFact] = Field(..., description="Annual values as filed.")

class LeiRecord(BaseModel):
    "The Legal Entity Identifier record."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    lei: str = Field(..., description="The LEI.")
    facts: List[PublicFact] = Field(..., description="The record's facts.")
    direct_parent: Optional[Parent] = Field(..., description="The direct parent the record reports, or null.")
    ultimate_parent: Optional[Parent] = Field(..., description="The ultimate parent the record reports, or null.")

class Parent(BaseModel):
    "A parent entity."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    lei: str = Field(..., description="The parent's LEI.")
    name: Optional[str] = Field(..., description="Its legal name.")

class NotRead(BaseModel):
    "A source not read."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    source: str = Field(..., description="The source.")
    reason: str = Field(..., description="Why.")

class EvidenceClass(BaseModel):
    "One class of evidence in the reading, kept apart from the others, with its own freshness rule and a line saying what it does not establish."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    class_: Literal["regulator_filing", "registry_record", "sanctions_list", "procurement_exclusion", "domain_registration", "dns_configuration", "certificate_transparency", "site_publication", "patent_record", "merger_review", "domain_declaration", "trooth_claim_record"] = Field(..., alias="class", description="The class of evidence. Default stale-after days: regulator_filing 90, registry_record 365, sanctions_list 7, procurement_exclusion 7, domain_registration 30, dns_configuration 2, certificate_transparency 7, site_publication 30, patent_record 90, merger_review 30. Since trooth 0.14.0: domain_declaration 30 (a key the site publishes shows who controlled the site's content when Trooth read it; it does not establish the legal entity or a person's authority to act for it), trooth_claim_record 365 (domain control at claim time; it does not establish that the person may act for the legal entity).")
    sections: List[str] = Field(..., description="The sections of this record that hold this class of evidence.")
    stale_after_days: int = Field(..., description="After this many days from observed_at a reader should take the evidence as stale and read again.")
    does_not_establish: str = Field(..., description="What this class of evidence does not show, in one sentence.")
    read: bool = Field(..., description="Whether this reading read any of the sections.")
    observed_at: Optional[str] = Field(..., description="When the evidence was observed: the reading's read_at, or the source's own earlier read time when a cached answer was used. Null when not read.")
    stale_after: Optional[str] = Field(..., description="observed_at plus stale_after_days, as an ISO 8601 time. Null when not read.")

class ContinuityEvent(BaseModel):
    "One difference between this reading and the previous reading of the same domain."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    kind: Literal["entity_changed", "entity_appeared", "entity_disappeared", "renamed", "parent_changed", "registrar_changed", "domain_transferred", "unchanged", "declaration_appeared", "declaration_key_changed", "declaration_disappeared"] = Field(..., description="What differs. entity_changed: the domain now ties to a different legal entity. entity_appeared: it now ties to one and did not before. entity_disappeared: it tied to one and now ties to none. renamed: the same entity under a new name. parent_changed: the LEI record names a different direct or ultimate parent. registrar_changed: RDAP names a different registrar. domain_transferred: RDAP records a transfer after the previous reading. unchanged: none of these. Since trooth 0.14.0: declaration_appeared: a declaration that checks is published and the previous reading had none. declaration_key_changed: the declaration's keys differ from the previous reading's. declaration_disappeared: the previous reading had a declaration that checked and this one does not.")
    detail: str = Field(..., description="The difference in words, naming both readings' values.")

class ContinuityPrevious(BaseModel):
    "The previous cached reading of the same domain this reading was compared with."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    read_at: str = Field(..., description="When the previous reading was taken.")
    record_sha256: str = Field(..., description="Lowercase hex SHA-256 of the previous record as it was cached.")

class Continuity(BaseModel):
    "This reading compared with the previous cached reading of the same domain. A changed entity is never merged: the new reading carries only what it read now, and the event names both."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    previous: Optional[ContinuityPrevious] = Field(..., description="The previous reading compared with; null when there is none.")
    events: List[ContinuityEvent] = Field(..., description="What differs; empty when there is no previous reading, and a single unchanged event when nothing listed differs.")

class Proof(BaseModel):
    "One proof binding two subjects."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str = Field(..., description="<proof kind>:<n>, unique in the reading.")
    binds: List[str] = Field(..., description="The two subject ids the proof binds, the domain first.")
    proof_method: Literal["regulator_filing", "registry_record", "site_statement", "registry_name_match", "asked", "none", "dns_txt", "domain_signed_declaration", "identity_provider_sign_in", "domain_email_code", "repository_control"] = Field(..., description="How the binding was shown (the same values as bindings[].proof_method).")
    status: Literal["confirmed", "claimed", "not_found", "not_read"] = Field(..., description="confirmed: the proof holds as read. claimed: asserted, and nothing read confirms it. not_found: looked for and not there. not_read: the source could not be read (a 403 or 404 from a code host is not read, never absent).")
    detail: str = Field(..., description="What was read, in words.")
    source: str = Field(..., description="The URL read, or \"trooth record\" for Trooth's own record of the claim.")
    observed_at: Optional[str] = Field(..., description="When the proof was observed: the reading's read_at, or for Trooth's record of the claim, when the claim was confirmed. Null when not read.")

class DeclarationReading(BaseModel):
    "The domain-signed declaration as this reading found it."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    url: str = Field(..., description="https://<domain>/.well-known/trooth.json.")
    status: Literal["checked", "invalid", "expired", "absent", "not_read"] = Field(..., description="checked: every rule in docs/DECLARATION.md holds. invalid: a rule fails (reason says which). expired: it checks but expires_at has passed. absent: the site answers 404 or 410. not_read: the site could not be read.")
    reason: Optional[str] = Field(..., description="Why, in words.")
    sha256: Optional[str] = Field(..., description="Lowercase hex SHA-256 of the bytes served; null when nothing was read.")
    issued_at: Optional[str] = Field(..., description="The declaration's issued_at.")
    expires_at: Optional[str] = Field(..., description="The declaration's expires_at.")
    keys: List[str] = Field(..., description="The kids of the keys it publishes (<domain>#<thumbprint>).")
    key_pinned_by_dns: bool = Field(..., description="Whether the TXT record at _trooth-key.<domain> names one of the keys.")
    products: List[DeclaredProduct] = Field(..., description="The products it names, when it checks; empty otherwise.")
    apis: List[DeclaredApi] = Field(..., description="The APIs it names, when it checks; empty otherwise.")
    repositories: List[str] = Field(..., description="The repositories it names, when it checks; empty otherwise.")

class VerificationBundle(BaseModel):
    "Everything needed to check one witness statement with no network: the statement, its evidence manifest, the key list as read, and the exact mapping bytes. Written by `trooth verify --save-bundle`; read by `trooth verify --bundle` and the SDKs. A bundle is only as fresh as its key list."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    bundle: Literal["trooth.verification-bundle.v1"] = Field(..., description="The bundle format.")
    created_at: str = Field(..., description="When the bundle was written. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    domain: Optional[str] = Field(..., description="The domain the bundle was saved for. A reader may ask about another; a statement for a different domain is a mismatch.")
    statement: WitnessStatement = Field(..., description="The signed envelope, exactly as published.")
    manifest: Optional[EvidenceManifest] = Field(..., description="The evidence manifest, or null when none was saved.")
    keys: BundleKeys = Field(..., description="The key list as read when the bundle was written.")
    mapping: Optional[BundleMapping] = Field(..., description="The exact mapping bytes, or null when none were saved.")
    log: Optional[BundleLog] = Field(None, description="What the witness statement log answered when the bundle was written: the log key used, the receipt or null, and every correction. Absent in a bundle written before the log, or when the log was not read.")

class BundleLog(BaseModel):
    "The log answer, carried so the log part can be checked offline too."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    vkey: str = Field(..., description="The log verifier key the receipt was checked against, as a signed-note key (name+hash+key). A pinned key, when the checker has one, replaces it.")
    receipt: Optional[LogReceipt] = Field(..., description="The receipt for the statement, or null when the log held no entry for it.")
    corrections: List[LoggedCorrection] = Field(..., description="Every logged correction naming this statement, each with its own receipt.")

class LoggedCorrection(BaseModel):
    "A correction envelope and its receipt."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    statement: WitnessStatement = Field(..., description="The correction envelope: its payload is a trooth.correction.v1 document in RFC 8785 bytes.")
    receipt: LogReceipt = Field(..., description="The receipt for the correction.")

class BundleKeys(BaseModel):
    "The key list as read."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    keys: List[PublicKey] = Field(..., description="The keys array of the key list.")
    list_read_at: Optional[str] = Field(..., description="When the key list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    source: Optional[str] = Field(..., description="Where it was read from: a URL or a file path.")

class BundleMapping(BaseModel):
    "The mapping document, byte for byte."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    url: Optional[str] = Field(..., description="Where the bytes were read from.")
    digest: str = Field(..., description="The digest of the carried bytes, for display. A checker hashes the bytes itself and compares with the signed digest.")
    bytes_base64: str = Field(..., description="The exact mapping bytes, standard base64.")

class VerifyResult(BaseModel):
    "The JSON document `trooth verify --json` writes, and the shape the SDKs return. The verdict is the only conclusion; everything else says how it was reached."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    domain: Optional[str] = Field(..., description="The domain asked about, or the signed domain when none was asked.")
    verdict: Literal["checked", "checked_v1", "partially_checked", "signature_not_trusted", "mismatch", "superseded"] = Field(..., description="checked: v2 or v3, everything bound and matching. checked_v1: a v1 statement that checks. partially_checked: a mapping or manifest was not supplied. signature_not_trusted: malformed, invalid or untrusted key. mismatch: trusted, but a count, the domain, the mapping, the manifest or a log receipt disagrees. superseded: everything held, and a correction Trooth signed and logged withdraws or replaces the statement.")
    version: Literal["v1", "v2", "v3", "unknown"] = Field(..., description="The statement version, or unknown.")
    read_at: Optional[str] = Field(None, description="The read_at the payload carries. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    reading_id: Optional[str] = Field(None, description="The reading id the payload carries.")
    statement_id: Optional[str] = Field(None, description="trooth:statement: plus the hex SHA-256 of the exact payload bytes (docs/IDS.md).")
    signature: Literal["valid", "invalid", "malformed"] = Field(..., description="valid, invalid or malformed.")
    key: KeyTrust = Field(..., description="The signing key and whether it is trusted at read_at.")
    subject: Subject = Field(..., description="The signed domain against the domain asked about.")
    binding: Binding = Field(..., description="The mapping and manifest against their signed digests.")
    counts: CountCheck = Field(..., description="Whether the signed counts agree with the signed checks.")
    log: Optional[LogCheck] = Field(None, description="The witness statement log part of the check. Absent when the log was not asked (offline from saved files, --no-log) or the signature was not trusted.")
    assurance: str = Field(..., description="What a valid signature of this version shows and does not show, in words.")
    keys_read_at: Optional[str] = Field(None, description="When the key list used was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    sources: Optional[Dict[str, Optional[str]]] = Field(None, description="Where each input came from: a URL, a file path, or null when not supplied.")

class KeyTrust(BaseModel):
    "The key decision."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    kid: str = Field(..., description="The key id the envelope names.")
    state: Literal["active", "retired", "compromised", "revoked_unrecorded", "unknown"] = Field(..., description="The lifecycle state found on the key list.")
    trusted: bool = Field(..., description="Whether a valid signature from this key at this time is relied on.")
    reason: str = Field(..., description="Why, in words.")

class Subject(BaseModel):
    "The subject decision."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    signed: Optional[str] = Field(..., description="The domain in the signed payload.")
    asked: Optional[str] = Field(..., description="The domain asked about.")
    status: Literal["match", "mismatch", "not_checked"] = Field(..., description="match, mismatch, or not_checked (no domain given, or the signature was not trusted).")

class Binding(BaseModel):
    "The binding decision."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: Literal["bound", "partially_checked", "mismatch", "absent", "unchecked"] = Field(..., description="bound, partially_checked, mismatch, absent (v1 binds neither) or unchecked (signature not trusted).")
    mapping: Literal["match", "mismatch", "not_supplied", "absent"] = Field(..., description="The mapping result.")
    manifest: Literal["match", "mismatch", "not_supplied", "absent"] = Field(..., description="The manifest result.")

class LogCheck(BaseModel):
    "What the log showed about the statement."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: Literal["included", "not_logged", "unavailable", "checkpoint_invalid", "proof_invalid"] = Field(..., description="included: the receipt checks against a checkpoint signed by the log key. not_logged: the log holds no entry for it (reported, not a failure in this version). unavailable: the log could not be read. checkpoint_invalid: the checkpoint is not signed by the log key or names another log. proof_invalid: the receipt does not take this statement to the signed root.")
    index: Optional[int] = Field(..., description="The entry index the receipt names, or null.")
    tree_size: Optional[int] = Field(..., description="The signed tree size the receipt is against, or null.")
    reason: Optional[str] = Field(..., description="Why, in words.")
    corrections: List[CorrectionCheck] = Field(..., description="Each correction the log returned and whether it checked.")
    superseded_by: Optional[str] = Field(..., description="The statement id of the first correction that checked, or null.")
    vkey_source: Optional[str] = Field(None, description="Where the log key came from: pinned in this release, --log-vkey, carried in a bundle, or served by the log.")

class CorrectionCheck(BaseModel):
    "One correction and whether it is relied on."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    valid: bool = Field(..., description="True when it is signed by a trusted key, in RFC 8785 bytes, names this statement, and is included in the log.")
    correction_statement_id: Optional[str] = Field(..., description="The statement id of the correction itself.")
    code: Optional[str] = Field(..., description="The reason code it carries.")
    effect: Optional[str] = Field(..., description="withdrawn or replaced.")
    replacement: Optional[str] = Field(..., description="The replacing statement id, for replaced.")
    issued_at: Optional[str] = Field(..., description="When Trooth issued it, as Trooth asserts. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    reason: Optional[str] = Field(..., description="Why it is or is not relied on, in words.")

class CountCheck(BaseModel):
    "The count decision."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    identities_hold: bool = Field(..., description="True when every identity holds.")
    problems: List[str] = Field(..., description="Each identity that does not hold, in words.")

class WitnessPayloadV1(BaseModel):
    "The JSON a trooth.witness-statement.v1 payload holds. v1 binds the outcomes and counts only: no mapping, manifest, evaluator or subject scope."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    statement: Literal["trooth.witness-statement.v1"] = Field(..., description="The statement version.")
    reading_id: str = Field(..., description="The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).")
    domain: str = Field(..., description="The domain the reading was taken of: lowercase, no trailing dot.")
    read_at: str = Field(..., description="When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    checks: List[CheckV1] = Field(..., description="Every check in the reading.")
    counts: CountsV1 = Field(..., description="The two counts, which must agree with the checks.")

class CheckV1(BaseModel):
    "One check in a v1 reading. v1 carries no reason."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str = Field(..., description="The check id.")
    category: str = Field(..., description="The check category.")
    kind: str = Field(..., description="probe or attest.")
    outcome: Literal["as expected", "not as expected", "not read"] = Field(..., description="One of three outcomes.")

class CountsV1(BaseModel):
    "The two counts a v1 payload carries."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    read: int = Field(..., description="Checks whose outcome is not `not read`.")
    as_expected: int = Field(..., description="Checks whose outcome is `as expected`.")

class WitnessPayloadV2(BaseModel):
    "The JSON a trooth.witness-statement.v2 payload holds. Its members are signed in exactly this order with no whitespace. It binds the check mapping, the evaluator, the subject scope and the evidence manifest."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    statement: Literal["trooth.witness-statement.v2"] = Field(..., description="The statement version.")
    reading_id: str = Field(..., description="The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).")
    domain: str = Field(..., description="The domain the reading was taken of: lowercase, no trailing dot.")
    read_at: str = Field(..., description="When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    subject_scope: SubjectScope = Field(..., description="What the reading covered.")
    methodology: Methodology = Field(..., description="The check mapping, bound by digest.")
    evaluator: Evaluator = Field(..., description="The software that took the reading.")
    evidence_manifest: EvidenceManifestRef = Field(..., description="The evidence manifest, bound by digest.")
    checks: List[Check] = Field(..., description="Every check in the reading.")
    counts: Counts = Field(..., description="Counts that must agree with the checks.")

class Check(BaseModel):
    "One check in the reading and its outcome."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str = Field(..., description="The check id in the check mapping the payload names (for example S1, L2).")
    category: str = Field(..., description="The check category in the mapping (for example security, legal, ai, ip, business).")
    kind: str = Field(..., description="How the check is taken: `probe` reads the public surface; `attest` reads something the company published about itself.")
    outcome: Literal["as expected", "not as expected", "not read"] = Field(..., description="One of three outcomes. There is no fourth value and no score.")
    reason: Optional[CheckReason] = Field(..., description="Null when the outcome is `as expected`; otherwise why.")

class CheckReason(BaseModel):
    "Why a check is not `as expected`. Present on every check whose outcome is `not read` or `not as expected`."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    code: Literal["source_unavailable", "timeout", "evaluator_limitation", "carried_from_earlier_reading", "check_misconfigured", "contrary_observation", "expected_item_absent"] = Field(..., description="The reason code. source_unavailable, timeout, evaluator_limitation, carried_from_earlier_reading and check_misconfigured go with `not read`; contrary_observation and expected_item_absent go with `not as expected`.")
    version: Literal["trooth.check-explanations.v1"] = Field(..., description="The version of the reason vocabulary.")
    source_ref: Optional[str] = Field(..., description="The public source the reason refers to, or null. Always null when `withheld` is true.")
    withheld: bool = Field(..., description="True when the source behind this reason is not published (for example a private document); only a commitment to it is in the evidence manifest.")
    withheld_reason: Optional[str] = Field(..., description="Why the source is withheld. Required, non-empty, when `withheld` is true; otherwise null.")

class Counts(BaseModel):
    "Counts that MUST agree with the checks: read + not_read = in_reading; as_expected + not_as_expected = read; in_reading = the number of checks. They are reported apart and never added into one number."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    read: int = Field(..., description="Checks whose outcome is not `not read`.")
    as_expected: int = Field(..., description="Checks whose outcome is `as expected`.")
    not_as_expected: int = Field(..., description="Checks whose outcome is `not as expected`.")
    not_read: int = Field(..., description="Checks whose outcome is `not read`.")
    in_reading: int = Field(..., description="All checks in the reading.")

class SubjectScope(BaseModel):
    "What the reading covered."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    domain: str = Field(..., description="The domain read. Equals the payload domain.")
    surface: str = Field(..., description="Which surface was read. `public`: only what anyone can fetch.")
    checks_in_scope: int = Field(..., description="The number of checks in scope. Equals the number of checks listed.")

class Methodology(BaseModel):
    "The exact check mapping the reading used, bound by digest."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    standard: str = Field(..., description="The name of the standard the mapping belongs to.")
    mapping_version: str = Field(..., description="The mapping version.")
    mapping_url: str = Field(..., description="Where the exact mapping bytes are served. Immutable versions live under https://trooth.co/standard/check-mapping/.")
    mapping_digest: str = Field(..., description="`sha256:` plus the lowercase hex SHA-256 of the exact mapping bytes.")

class Evaluator(BaseModel):
    "The software that took the reading."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str = Field(..., description="The evaluator name.")
    version: str = Field(..., description="The evaluator version.")

class EvidenceManifestRef(BaseModel):
    "The evidence manifest the reading binds, by digest."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    digest: str = Field(..., description="`sha256:` plus the hex SHA-256 of the canonical manifest bytes (evidence-manifest.schema.json).")
    entries: int = Field(..., description="The number of manifest entries.")
    canonicalization: str = Field(..., description="How the manifest bytes are formed: entries sorted by check_id, keys check_id then source or commitment, no whitespace, UTF-8.")

class WitnessPayloadV3(BaseModel):
    "The JSON a trooth.witness-statement.v3 payload holds: the v2 content plus subject_id and signer, serialized as RFC 8785 (JCS). Every number is an integer between -(2^53 - 1) and 2^53 - 1, so every implementation produces the same bytes."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    checks: List[Check] = Field(..., description="Every check in the reading.")
    counts: Counts = Field(..., description="Counts that must agree with the checks.")
    domain: str = Field(..., description="The domain the reading was taken of: lowercase, no trailing dot.")
    evaluator: Evaluator = Field(..., description="The software that took the reading.")
    evidence_manifest: EvidenceManifestRef = Field(..., description="The evidence manifest, bound by digest.")
    methodology: Methodology = Field(..., description="The check mapping, bound by digest.")
    read_at: str = Field(..., description="When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).")
    reading_id: str = Field(..., description="The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).")
    signer: Signer = Field(..., description="The signing key, inside the signed bytes.")
    statement: Literal["trooth.witness-statement.v3"] = Field(..., description="The statement version.")
    subject_id: str = Field(..., description="The subject by its stable id, trooth:domain:<domain> (docs/IDS.md). MUST name the payload domain.")
    subject_scope: SubjectScope = Field(..., description="What the reading covered.")

class Signer(BaseModel):
    "The signing key, named inside the signed bytes so the envelope cannot point at another key."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    key_id: str = Field(..., description="The kid of the signing key. MUST equal the envelope key_id.")
    issuer: Literal["trooth.co"] = Field(..., description="Who signs: trooth.co.")

class WitnessStatement(BaseModel):
    "The signed envelope Trooth publishes as `witnessStatement` on a record. The signature covers the exact UTF-8 bytes of `payload`, nothing else. How to check it: docs/VERIFY.md in github.com/troothllc/trooth-cli."

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    payload: str = Field(..., description="The signing input: the exact JSON text that was signed. Parse it to read it; never re-serialize it to check it. Its `statement` field names the version (witness-payload.v1, v2 or v3).")
    signature: str = Field(..., description="The Ed25519 signature over the payload bytes: `ed25519:` followed by standard base64 of the 64 signature bytes.")
    key_id: str = Field(..., description="The `kid` of the signing key on https://api.trooth.co/public/keys. A v3 payload names the same key inside the signed bytes, at signer.key_id.")
    alg: Literal["Ed25519"] = Field(..., description="The signature algorithm. Always Ed25519 (RFC 8032, pure EdDSA).")
    canonicalization: Literal["json-fixed-key-order-no-whitespace-utf8", "RFC8785"] = Field(..., description="How the payload bytes were produced. `json-fixed-key-order-no-whitespace-utf8` for v1 and v2; `RFC8785` (JSON Canonicalization Scheme, integers only) for v3, where the payload MUST equal the canonical form of the JSON it holds.")

EvidenceManifest = List[ManifestEntry]
"""The evidence manifest a v2 or v3 statement binds by digest, published beside the statement as `witnessEvidenceManifest`. Canonical bytes: entries sorted by check_id, each as {"check_id":..,"source":..} or {"check_id":..,"commitment":..}, no whitespace, UTF-8."""

GuardDecideOutput = Union[GuardDecision, GuardNotCovered]
"""The one JSON document `trooth guard decide --json` prints on stdout when it decides or declines to: a GuardDecision when the policy covers the tool (exit 0 allow, 20 hold, 21 deny), or a GuardNotCovered when it does not (exit 0). A usage error prints the CLI's error document instead ({"ok": false, "error": "...", "exit": 2}), as every command does."""


CorrectionPayload.model_rebuild()
CorrectionReason.model_rebuild()
DomainDeclaration.model_rebuild()
DeclarationKey.model_rebuild()
DeclaredProduct.model_rebuild()
DeclaredMcp.model_rebuild()
DeclaredApi.model_rebuild()
DeclarationSignature.model_rebuild()
ManifestEntry.model_rebuild()
GuardDecision.model_rebuild()
GuardNotCovered.model_rebuild()
GuardReason.model_rebuild()
GuardPolicyRef.model_rebuild()
GuardEvidence.model_rebuild()
GuardPolicy.model_rebuild()
GuardAppliesTo.model_rebuild()
GuardHttpTarget.model_rebuild()
GuardLogRequirement.model_rebuild()
GuardRule.model_rebuild()
GuardClaimRequire.model_rebuild()
GuardSignatureRequire.model_rebuild()
GuardDestinations.model_rebuild()
KeyList.model_rebuild()
PublicKey.model_rebuild()
KeyEvent.model_rebuild()
LogReceipt.model_rebuild()
McpToolsStatement.model_rebuild()
StatementTool.model_rebuild()
McpStatementSigner.model_rebuild()
McpToolsReading.model_rebuild()
McpServer.model_rebuild()
ToolHash.model_rebuild()
PreviousManifest.model_rebuild()
ManifestDiff.model_rebuild()
McpToolsSigned.model_rebuild()
PublicRecordStatement.model_rebuild()
BindingStatus.model_rebuild()
StatementSigner.model_rebuild()
PublicRecordReading.model_rebuild()
SamReading.model_rebuild()
SamRegistration.model_rebuild()
SamExclusion.model_rebuild()
PatentReading.model_rebuild()
PatentApplication.model_rebuild()
RegistryEntry.model_rebuild()
MergerReview.model_rebuild()
MergerNotice.model_rebuild()
DomainRegistration.model_rebuild()
Change.model_rebuild()
NamedSubject.model_rebuild()
Entity.model_rebuild()
Certificates.model_rebuild()
SecurityTxt.model_rebuild()
Sanctions.model_rebuild()
SanctionsEntry.model_rebuild()
Source.model_rebuild()
Signed.model_rebuild()
PublicFact.model_rebuild()
BindingEvidence.model_rebuild()
EntityBinding.model_rebuild()
Filing.model_rebuild()
FinancialFact.model_rebuild()
SiteRead.model_rebuild()
SiteLink.model_rebuild()
SiteName.model_rebuild()
SecRecord.model_rebuild()
LeiRecord.model_rebuild()
Parent.model_rebuild()
NotRead.model_rebuild()
EvidenceClass.model_rebuild()
ContinuityEvent.model_rebuild()
ContinuityPrevious.model_rebuild()
Continuity.model_rebuild()
Proof.model_rebuild()
DeclarationReading.model_rebuild()
VerificationBundle.model_rebuild()
BundleLog.model_rebuild()
LoggedCorrection.model_rebuild()
BundleKeys.model_rebuild()
BundleMapping.model_rebuild()
VerifyResult.model_rebuild()
KeyTrust.model_rebuild()
Subject.model_rebuild()
Binding.model_rebuild()
LogCheck.model_rebuild()
CorrectionCheck.model_rebuild()
CountCheck.model_rebuild()
WitnessPayloadV1.model_rebuild()
CheckV1.model_rebuild()
CountsV1.model_rebuild()
WitnessPayloadV2.model_rebuild()
Check.model_rebuild()
CheckReason.model_rebuild()
Counts.model_rebuild()
SubjectScope.model_rebuild()
Methodology.model_rebuild()
Evaluator.model_rebuild()
EvidenceManifestRef.model_rebuild()
WitnessPayloadV3.model_rebuild()
Signer.model_rebuild()
WitnessStatement.model_rebuild()
