// GENERATED by scripts/gen-types.mjs from schemas/ in github.com/troothllc/trooth-cli.
// Do not edit by hand: change the schema and run `node scripts/gen-types.mjs`.

/** The evidence manifest a v2 or v3 statement binds by digest, published beside the statement as `witnessEvidenceManifest`. Canonical bytes: entries sorted by check_id, each as {"check_id":..,"source":..} or {"check_id":..,"commitment":..}, no whitespace, UTF-8. */
export type EvidenceManifest = ManifestEntry[];

/** One check and the evidence behind it: a public `source`, or a `commitment` to a private one. Exactly one of the two. */
export interface ManifestEntry {
  /** The check id. Unique in the manifest. */
  check_id: string;
  /** The public URL the check read. */
  source?: string;
  /** `sha256:` plus the hex SHA-256 of salt, a newline byte and the private reference. Only its holder can open it. */
  commitment?: string;
}

/** The body of https://api.trooth.co/public/keys, or a saved copy of it. Save it with the time you read it: a saved list cannot show a compromise announced later. */
export interface KeyList {
  /** Every key, current and past. */
  keys: PublicKey[];
  /** When the list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  list_read_at?: string | null;
  /** The kid of the key currently used for new statements. */
  active_kid?: string | null;
  /** A note from the key service. */
  note?: string | null;
}

/** One published key and its lifecycle. Only `kid`, `alg`, `encoding`, `public_key`, `status` and the three lifecycle times decide trust (docs/VERIFY.md section 3). */
export interface PublicKey {
  /** The key id a statement names in key_id. */
  kid: string;
  /** Always Ed25519. */
  alg: "Ed25519";
  /** How public_key is written: hex or base64. */
  encoding?: "hex" | "base64";
  /** The 32-byte Ed25519 public key, in `encoding`. */
  public_key: string;
  /** active, retired, revoked or compromised. */
  status: "active" | "retired" | "revoked" | "compromised";
  /** The same lifecycle state as written by the key service. */
  state?: string;
  /** When the key was retired. Statements carrying a read_at strictly before this stay trusted. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  retired_at?: string | null;
  /** When the key was found compromised. Nothing signed by it is relied on. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  compromised_at?: string | null;
  /** When the key was revoked. A revocation with no compromise recorded is treated as a compromise. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  revoked_at?: string | null;
  /** When the key was created, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  created_at?: string | null;
  /** When the key was first used, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  activated_at?: string | null;
  /** When the key first appeared on the list. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  first_listed_at?: string | null;
  /** A short fingerprint of the key, for display. */
  fingerprint?: string;
  /** What the key is for, as a short label. */
  purpose?: string;
  /** What the key signs, in words. */
  signs?: string;
  /** Lifecycle events, oldest first. */
  events?: KeyEvent[];
}

/** One lifecycle event of a key. */
export interface KeyEvent {
  /** What happened (for example first_listed, retired, compromised). */
  event: string;
  /** When. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  at: string;
  /** A note, or null. */
  note?: string | null;
}

/** Everything needed to check one witness statement with no network: the statement, its evidence manifest, the key list as read, and the exact mapping bytes. Written by `trooth verify --save-bundle`; read by `trooth verify --bundle` and the SDKs. A bundle is only as fresh as its key list. */
export interface VerificationBundle {
  /** The bundle format. */
  bundle: "trooth.verification-bundle.v1";
  /** When the bundle was written. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  created_at: string;
  /** The domain the bundle was saved for. A reader may ask about another; a statement for a different domain is a mismatch. */
  domain: string | null;
  /** The signed envelope, exactly as published. */
  statement: WitnessStatement;
  /** The evidence manifest, or null when none was saved. */
  manifest: EvidenceManifest | null;
  /** The key list as read when the bundle was written. */
  keys: BundleKeys;
  /** The exact mapping bytes, or null when none were saved. */
  mapping: BundleMapping | null;
}

/** The key list as read. */
export interface BundleKeys {
  /** The keys array of the key list. */
  keys: PublicKey[];
  /** When the key list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  list_read_at: string | null;
  /** Where it was read from: a URL or a file path. */
  source: string | null;
}

/** The mapping document, byte for byte. */
export interface BundleMapping {
  /** Where the bytes were read from. */
  url: string | null;
  /** The digest of the carried bytes, for display. A checker hashes the bytes itself and compares with the signed digest. */
  digest: string;
  /** The exact mapping bytes, standard base64. */
  bytes_base64: string;
}

/** The JSON document `trooth verify --json` writes, and the shape the SDKs return. The verdict is the only conclusion; everything else says how it was reached. */
export interface VerifyResult {
  /** The domain asked about, or the signed domain when none was asked. */
  domain: string | null;
  /** checked: v2 or v3, everything bound and matching. checked_v1: a v1 statement that checks. partially_checked: a mapping or manifest was not supplied. signature_not_trusted: malformed, invalid or untrusted key. mismatch: trusted, but a count, the domain, the mapping or the manifest disagrees. */
  verdict: "checked" | "checked_v1" | "partially_checked" | "signature_not_trusted" | "mismatch";
  /** The statement version, or unknown. */
  version: "v1" | "v2" | "v3" | "unknown";
  /** The read_at the payload carries. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  read_at?: string | null;
  /** The reading id the payload carries. */
  reading_id?: string | null;
  /** trooth:statement: plus the hex SHA-256 of the exact payload bytes (docs/IDS.md). */
  statement_id?: string | null;
  /** valid, invalid or malformed. */
  signature: "valid" | "invalid" | "malformed";
  /** The signing key and whether it is trusted at read_at. */
  key: KeyTrust;
  /** The signed domain against the domain asked about. */
  subject: Subject;
  /** The mapping and manifest against their signed digests. */
  binding: Binding;
  /** Whether the signed counts agree with the signed checks. */
  counts: CountCheck;
  /** What a valid signature of this version shows and does not show, in words. */
  assurance: string;
  /** When the key list used was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  keys_read_at?: string | null;
  /** Where each input came from: a URL, a file path, or null when not supplied. */
  sources?: Record<string, string | null>;
}

/** The key decision. */
export interface KeyTrust {
  /** The key id the envelope names. */
  kid: string;
  /** The lifecycle state found on the key list. */
  state: "active" | "retired" | "compromised" | "revoked_unrecorded" | "unknown";
  /** Whether a valid signature from this key at this time is relied on. */
  trusted: boolean;
  /** Why, in words. */
  reason: string;
}

/** The subject decision. */
export interface Subject {
  /** The domain in the signed payload. */
  signed: string | null;
  /** The domain asked about. */
  asked: string | null;
  /** match, mismatch, or not_checked (no domain given, or the signature was not trusted). */
  status: "match" | "mismatch" | "not_checked";
}

/** The binding decision. */
export interface Binding {
  /** bound, partially_checked, mismatch, absent (v1 binds neither) or unchecked (signature not trusted). */
  status: "bound" | "partially_checked" | "mismatch" | "absent" | "unchecked";
  /** The mapping result. */
  mapping: "match" | "mismatch" | "not_supplied" | "absent";
  /** The manifest result. */
  manifest: "match" | "mismatch" | "not_supplied" | "absent";
}

/** The count decision. */
export interface CountCheck {
  /** True when every identity holds. */
  identities_hold: boolean;
  /** Each identity that does not hold, in words. */
  problems: string[];
}

/** The JSON a trooth.witness-statement.v1 payload holds. v1 binds the outcomes and counts only: no mapping, manifest, evaluator or subject scope. */
export interface WitnessPayloadV1 {
  /** The statement version. */
  statement: "trooth.witness-statement.v1";
  /** The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md). */
  reading_id: string;
  /** The domain the reading was taken of: lowercase, no trailing dot. */
  domain: string;
  /** When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  read_at: string;
  /** Every check in the reading. */
  checks: CheckV1[];
  /** The two counts, which must agree with the checks. */
  counts: CountsV1;
}

/** One check in a v1 reading. v1 carries no reason. */
export interface CheckV1 {
  /** The check id. */
  id: string;
  /** The check category. */
  category: string;
  /** probe or attest. */
  kind: string;
  /** One of three outcomes. */
  outcome: "as expected" | "not as expected" | "not read";
}

/** The two counts a v1 payload carries. */
export interface CountsV1 {
  /** Checks whose outcome is not `not read`. */
  read: number;
  /** Checks whose outcome is `as expected`. */
  as_expected: number;
}

/** The JSON a trooth.witness-statement.v2 payload holds. Its members are signed in exactly this order with no whitespace. It binds the check mapping, the evaluator, the subject scope and the evidence manifest. */
export interface WitnessPayloadV2 {
  /** The statement version. */
  statement: "trooth.witness-statement.v2";
  /** The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md). */
  reading_id: string;
  /** The domain the reading was taken of: lowercase, no trailing dot. */
  domain: string;
  /** When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  read_at: string;
  /** What the reading covered. */
  subject_scope: SubjectScope;
  /** The check mapping, bound by digest. */
  methodology: Methodology;
  /** The software that took the reading. */
  evaluator: Evaluator;
  /** The evidence manifest, bound by digest. */
  evidence_manifest: EvidenceManifestRef;
  /** Every check in the reading. */
  checks: Check[];
  /** Counts that must agree with the checks. */
  counts: Counts;
}

/** One check in the reading and its outcome. */
export interface Check {
  /** The check id in the check mapping the payload names (for example S1, L2). */
  id: string;
  /** The check category in the mapping (for example security, legal, ai, ip, business). */
  category: string;
  /** How the check is taken: `probe` reads the public surface; `attest` reads something the company published about itself. */
  kind: string;
  /** One of three outcomes. There is no fourth value and no score. */
  outcome: "as expected" | "not as expected" | "not read";
  /** Null when the outcome is `as expected`; otherwise why. */
  reason: CheckReason | null;
}

/** Why a check is not `as expected`. Present on every check whose outcome is `not read` or `not as expected`. */
export interface CheckReason {
  /** The reason code. source_unavailable, timeout, evaluator_limitation, carried_from_earlier_reading and check_misconfigured go with `not read`; contrary_observation and expected_item_absent go with `not as expected`. */
  code: "source_unavailable" | "timeout" | "evaluator_limitation" | "carried_from_earlier_reading" | "check_misconfigured" | "contrary_observation" | "expected_item_absent";
  /** The version of the reason vocabulary. */
  version: "trooth.check-explanations.v1";
  /** The public source the reason refers to, or null. Always null when `withheld` is true. */
  source_ref: string | null;
  /** True when the source behind this reason is not published (for example a private document); only a commitment to it is in the evidence manifest. */
  withheld: boolean;
  /** Why the source is withheld. Required, non-empty, when `withheld` is true; otherwise null. */
  withheld_reason: string | null;
}

/** Counts that MUST agree with the checks: read + not_read = in_reading; as_expected + not_as_expected = read; in_reading = the number of checks. They are reported apart and never added into one number. */
export interface Counts {
  /** Checks whose outcome is not `not read`. */
  read: number;
  /** Checks whose outcome is `as expected`. */
  as_expected: number;
  /** Checks whose outcome is `not as expected`. */
  not_as_expected: number;
  /** Checks whose outcome is `not read`. */
  not_read: number;
  /** All checks in the reading. */
  in_reading: number;
}

/** What the reading covered. */
export interface SubjectScope {
  /** The domain read. Equals the payload domain. */
  domain: string;
  /** Which surface was read. `public`: only what anyone can fetch. */
  surface: string;
  /** The number of checks in scope. Equals the number of checks listed. */
  checks_in_scope: number;
}

/** The exact check mapping the reading used, bound by digest. */
export interface Methodology {
  /** The name of the standard the mapping belongs to. */
  standard: string;
  /** The mapping version. */
  mapping_version: string;
  /** Where the exact mapping bytes are served. Immutable versions live under https://trooth.co/standard/check-mapping/. */
  mapping_url: string;
  /** `sha256:` plus the lowercase hex SHA-256 of the exact mapping bytes. */
  mapping_digest: string;
}

/** The software that took the reading. */
export interface Evaluator {
  /** The evaluator name. */
  name: string;
  /** The evaluator version. */
  version: string;
}

/** The evidence manifest the reading binds, by digest. */
export interface EvidenceManifestRef {
  /** `sha256:` plus the hex SHA-256 of the canonical manifest bytes (evidence-manifest.schema.json). */
  digest: string;
  /** The number of manifest entries. */
  entries: number;
  /** How the manifest bytes are formed: entries sorted by check_id, keys check_id then source or commitment, no whitespace, UTF-8. */
  canonicalization: string;
}

/** The JSON a trooth.witness-statement.v3 payload holds: the v2 content plus subject_id and signer, serialized as RFC 8785 (JCS). Every number is an integer between -(2^53 - 1) and 2^53 - 1, so every implementation produces the same bytes. */
export interface WitnessPayloadV3 {
  /** Every check in the reading. */
  checks: Check[];
  /** Counts that must agree with the checks. */
  counts: Counts;
  /** The domain the reading was taken of: lowercase, no trailing dot. */
  domain: string;
  /** The software that took the reading. */
  evaluator: Evaluator;
  /** The evidence manifest, bound by digest. */
  evidence_manifest: EvidenceManifestRef;
  /** The check mapping, bound by digest. */
  methodology: Methodology;
  /** When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  read_at: string;
  /** The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md). */
  reading_id: string;
  /** The signing key, inside the signed bytes. */
  signer: Signer;
  /** The statement version. */
  statement: "trooth.witness-statement.v3";
  /** The subject by its stable id, trooth:domain:<domain> (docs/IDS.md). MUST name the payload domain. */
  subject_id: string;
  /** What the reading covered. */
  subject_scope: SubjectScope;
}

/** The signing key, named inside the signed bytes so the envelope cannot point at another key. */
export interface Signer {
  /** The kid of the signing key. MUST equal the envelope key_id. */
  key_id: string;
  /** Who signs: trooth.co. */
  issuer: "trooth.co";
}

/** The signed envelope Trooth publishes as `witnessStatement` on a record. The signature covers the exact UTF-8 bytes of `payload`, nothing else. How to check it: docs/VERIFY.md in github.com/troothllc/trooth-cli. */
export interface WitnessStatement {
  /** The signing input: the exact JSON text that was signed. Parse it to read it; never re-serialize it to check it. Its `statement` field names the version (witness-payload.v1, v2 or v3). */
  payload: string;
  /** The Ed25519 signature over the payload bytes: `ed25519:` followed by standard base64 of the 64 signature bytes. */
  signature: string;
  /** The `kid` of the signing key on https://api.trooth.co/public/keys. A v3 payload names the same key inside the signed bytes, at signer.key_id. */
  key_id: string;
  /** The signature algorithm. Always Ed25519 (RFC 8032, pure EdDSA). */
  alg: "Ed25519";
  /** How the payload bytes were produced. `json-fixed-key-order-no-whitespace-utf8` for v1 and v2; `RFC8785` (JSON Canonicalization Scheme, integers only) for v3, where the payload MUST equal the canonical form of the JSON it holds. */
  canonicalization: "json-fixed-key-order-no-whitespace-utf8" | "RFC8785";
}
