// GENERATED by scripts/gen-types.mjs from schemas/ in github.com/troothllc/trooth-cli.
// Do not edit by hand: change the schema and run `node scripts/gen-types.mjs`.

/** The JSON a trooth.correction.v1 payload holds: Trooth withdrawing or replacing a statement it signed. Signed like a v3 statement (RFC 8785 bytes, Ed25519, the signer inside the signed bytes) and entered in the witness statement log. The statement it corrects stays in the log; nothing is deleted. */
export interface CorrectionPayload {
  /** The payload type. */
  statement: "trooth.correction.v1";
  /** An identifier for this correction, unique in the log. */
  correction_id: string;
  /** The statement id this correction withdraws or replaces. It must already be in the log. */
  supersedes: string;
  /** The subject of the statement it corrects. */
  subject_id: string;
  /** withdrawn: no statement takes its place. replaced: the replacement statement does. */
  effect: "withdrawn" | "replaced";
  /** The replacing statement id, which must already be in the log; null for withdrawn. */
  replacement: string | null;
  /** Why. */
  reason: CorrectionReason;
  /** When Trooth issued it, as Trooth asserts. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  issued_at: string;
  /** The signing key, inside the signed bytes. */
  signer: Signer;
}

/** The reason for a correction. */
export interface CorrectionReason {
  /** evaluator_defect: the evaluator read wrongly. mapping_defect: the check mapping was wrong. source_misread: a source was misread. signing_key_compromised: the key that signed it is compromised. dispute_upheld: a dispute about the reading was upheld. withdrawn_by_trooth: withdrawn for another stated reason. */
  code: "evaluator_defect" | "mapping_defect" | "source_misread" | "signing_key_compromised" | "dispute_upheld" | "withdrawn_by_trooth";
  /** The reason in words, 10 to 1000 characters. */
  explanation: string;
}

/** The evidence manifest a v2 or v3 statement binds by digest, published beside the statement as `witnessEvidenceManifest`. Canonical bytes: entries sorted by check_id, each as {"check_id":..,"source":..} or {"check_id":..,"commitment":..}, no whitespace, UTF-8. */
export type EvidenceManifest = ManifestEntry[];

/** One check and the evidence behind it: a public `source`, or a `commitment` to a private one. Exactly one of the two. */
export interface ManifestEntry {
  /** The check id. Unique in the manifest. */
  check_id: string;
  /** The public URL the check read. */
  source?: string;
  /** `sha256:` plus the hex SHA-256 of salt, a newline byte and the private reference. Only its holder can open it. */
  commitment?: string;
}

/** The body of https://api.trooth.co/public/keys, or a saved copy of it. Save it with the time you read it: a saved list cannot show a compromise announced later. */
export interface KeyList {
  /** Every key, current and past. */
  keys: PublicKey[];
  /** When the list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  list_read_at?: string | null;
  /** The kid of the key currently used for new statements. */
  active_kid?: string | null;
  /** A note from the key service. */
  note?: string | null;
}

/** One published key and its lifecycle. Only `kid`, `alg`, `encoding`, `public_key`, `status` and the three lifecycle times decide trust (docs/VERIFY.md section 3). */
export interface PublicKey {
  /** The key id a statement names in key_id. */
  kid: string;
  /** Always Ed25519. */
  alg: "Ed25519";
  /** How public_key is written: hex or base64. */
  encoding?: "hex" | "base64";
  /** The 32-byte Ed25519 public key, in `encoding`. */
  public_key: string;
  /** active, retired, revoked or compromised. */
  status: "active" | "retired" | "revoked" | "compromised";
  /** The same lifecycle state as written by the key service. */
  state?: string;
  /** When the key was retired. Statements carrying a read_at strictly before this stay trusted. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  retired_at?: string | null;
  /** When the key was found compromised. Nothing signed by it is relied on. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  compromised_at?: string | null;
  /** When the key was revoked. A revocation with no compromise recorded is treated as a compromise. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  revoked_at?: string | null;
  /** When the key was created, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  created_at?: string | null;
  /** When the key was first used, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  activated_at?: string | null;
  /** When the key first appeared on the list. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  first_listed_at?: string | null;
  /** A short fingerprint of the key, for display. */
  fingerprint?: string;
  /** What the key is for, as a short label. */
  purpose?: string;
  /** What the key signs, in words. */
  signs?: string;
  /** Lifecycle events, oldest first. */
  events?: KeyEvent[];
}

/** One lifecycle event of a key. */
export interface KeyEvent {
  /** What happened (for example first_listed, retired, compromised). */
  event: string;
  /** When. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  at: string;
  /** A note, or null. */
  note?: string | null;
}

/** A receipt from Trooth's witness statement log (docs/LOG.md): the entry index, a checkpoint signed by the log key, and an RFC 9162 inclusion proof from the entry to the checkpoint root. The entry is RFC 8785 JSON of {kind, statement}; its leaf hash is SHA-256(0x00 || entry). */
export interface LogReceipt {
  /** The log origin, which the checkpoint must also name. */
  log: "trooth.co/witness-log/v1";
  /** The zero-based entry index. */
  index: number;
  /** The size of the signed tree the proof is against. Equals the checkpoint size. */
  tree_size: number;
  /** Standard base64 of the 32-byte root at tree_size. Equals the checkpoint root. */
  root_hash: string;
  /** The RFC 9162 audit path, leaf to root, each a 32-byte hash in standard base64. */
  inclusion_proof: string[];
  /** A C2SP checkpoint (origin, size, base64 root, each on its own line) followed by a blank line and C2SP signed-note signature lines; the log key's line is an em dash, the key name and base64 of the 4-byte key hash and the 64-byte Ed25519 signature. */
  checkpoint: string;
}

/** What a company has published outside its own website, read from the authorities that hold it (SEC EDGAR, the GLEIF LEI registry, DNS), beside the legal name its own site states, and the evidence tying each identifier to the domain. Served at https://api.trooth.co/scan/public-record/<domain>. Not signed: every fact carries the URL to read it again. Nothing in it grades, rates or ranks a company. docs/EVIDENCE.md in trooth-cli is the normative text. */
export interface PublicRecordReading {
  /** The format. */
  format: "trooth.public-record.v1";
  /** The domain read. */
  domain: string;
  /** trooth:domain:<domain>. */
  subject_id: string;
  /** When Trooth read the sources. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  read_at: string;
  /** What the company's own pages say about which legal entity it is. */
  site: SiteRead;
  /** Each identifier found and the evidence for and against tying it to the domain. */
  bindings: EntityBinding[];
  /** The SEC filer's record, or null when no filer was identified. */
  sec: SecRecord | null;
  /** The LEI record, or null when none was identified. */
  lei: LeiRecord | null;
  /** Mail-authentication records beyond SPF and DMARC, and DNSSEC. */
  dns: PublicFact[];
  /** Each source that was not read, or did not answer, and why. A source not read is never guessed at. */
  not_read: NotRead[];
  /** What the reading is and is not, as a paragraph. */
  note: string;
}

/** One fact as its source published it, with the URL it was read from. */
export interface PublicFact {
  /** A stable key, source.field (for example sec.tickers, lei.jurisdiction, dns.mta_sts). */
  key: string;
  /** The fact as words. */
  label: string;
  /** The value as published: text, a number, true or false, a list of text, or null when the source states nothing. */
  value: string | number | boolean | null | string[];
  /** Where it was read: a URL, or dns:<name> <type> for a DNS record. */
  source: string;
}

/** One piece of evidence for or against a binding. */
export interface BindingEvidence {
  /** For: filing_namespace_names_domain, registry_lists_domain, through_corroborated_filer (these tie the identifier to the domain), site_names_registry_name (a claim by the site), registries_agree, edgar_names_lei. Against: registry_lists_other_domain, registries_disagree, edgar_names_other_lei. */
  kind: string;
  /** What was seen, as a sentence. */
  detail: string;
  /** Where it was seen, or null when it follows from other evidence. */
  source: string | null;
}

/** A link between the domain and a legal-entity identifier, with the evidence for and against it. Nothing is asserted beyond the evidence. */
export interface EntityBinding {
  /** cik (SEC Central Index Key) or lei (Legal Entity Identifier). */
  identifier: "cik" | "lei";
  /** The identifier: 10 digits for a CIK, 20 characters for an LEI. */
  value: string;
  /** The stable id: trooth:cik:<10 digits> or trooth:lei:<LEI> (docs/IDS.md). */
  id: string;
  /** How the identifier was found: asked (given by the requester), ticker, site_legal_name (the legal name the site states matched exactly one listed SEC filer), edgar_lei_field, registry_name_match (exact legal name and, when the SEC gives one, the jurisdiction). */
  found_by: "asked" | "ticker" | "site_legal_name" | "edgar_lei_field" | "registry_name_match";
  /** corroborated: authoritative evidence ties it to the domain (the company's own filing or the registry record names the domain). claimed_by_site: the site names this entity, and nothing authoritative ties it. registries_only: registries agree with each other, nothing ties the domain. uncorroborated: no evidence either way. contradicted: authoritative evidence points elsewhere. not_found: the registry holds no such identifier. */
  status: "corroborated" | "claimed_by_site" | "registries_only" | "uncorroborated" | "contradicted" | "not_found";
  /** Evidence for the binding. */
  for: BindingEvidence[];
  /** Evidence against it. */
  against: BindingEvidence[];
}

/** One SEC filing, as EDGAR lists it. */
export interface Filing {
  /** The form type (10-K, 10-Q, 8-K, DEF 14A, 20-F ...). */
  form: string;
  /** The filing date, YYYY-MM-DD. */
  filed: string;
  /** The period or event date, when EDGAR gives one. */
  report_date: string | null;
  /** For an 8-K, the item numbers it reports (for example 1.05, 4.01). */
  items: string[];
  /** EDGAR's description of the primary document. */
  description: string | null;
  /** The primary document on www.sec.gov. */
  url: string;
}

/** A value the company filed in XBRL, as it filed it: the latest annual (10-K, full fiscal year) value of the concept. */
export interface FinancialFact {
  /** The XBRL concept, taxonomy:Name. */
  tag: string;
  /** The concept as words. */
  label: string;
  /** The value as filed. */
  value: number;
  /** The unit (USD). */
  unit: string;
  /** The period start for a flow such as revenue; null for a balance such as assets. */
  period_start: string | null;
  /** The period end. */
  period_end: string;
  /** The form the value was filed in. */
  form: string;
  /** The filing date. */
  filed: string;
  /** The accession number of that filing. */
  accession: string;
  /** The data.sec.gov URL the value was read from. */
  source: string;
}

/** The legal names the company's pages state in copyright notices. */
export interface SiteRead {
  /** Each legal name stated, with the page. */
  legal_names: SiteName[];
  /** Whether any page of the site could be read. */
  read: boolean;
  /** Why no name was found, or why the site was not read (for example its robots.txt opts out). */
  reason: string | null;
}

/** A legal name a page states. */
export interface SiteName {
  /** The name as written. */
  name: string;
  /** The page. */
  source: string;
}

/** The SEC filer's registration facts, filings and annual XBRL values. */
export interface SecRecord {
  /** The Central Index Key, 10 digits. */
  cik: string;
  /** Registration facts on file with the SEC. */
  facts: PublicFact[];
  /** The latest filing of each key form type, keyed by form. */
  latest: Record<string, Filing>;
  /** 8-K filings of the last two years, newest first, at most 50. */
  events: Filing[];
  /** The earliest date the events cover. */
  events_cover_since: string | null;
  /** 8-K filings reporting Item 1.05, a material cybersecurity incident. */
  cybersecurity_incidents: Filing[];
  /** 8-K filings reporting Item 4.01, a change of certifying accountant. */
  auditor_changes: Filing[];
  /** 8-K filings reporting Item 4.02, non-reliance on financial statements issued before. */
  non_reliance: Filing[];
  /** Forms 3, 4 and 5 filed in the last 90 days. */
  insider_forms_last_90_days: number;
  /** Annual values as filed. */
  financials: FinancialFact[];
}

/** The Legal Entity Identifier record. */
export interface LeiRecord {
  /** The LEI. */
  lei: string;
  /** The record's facts. */
  facts: PublicFact[];
  /** The direct parent the record reports, or null. */
  direct_parent: Parent | null;
  /** The ultimate parent the record reports, or null. */
  ultimate_parent: Parent | null;
}

/** A parent entity. */
export interface Parent {
  /** The parent's LEI. */
  lei: string;
  /** Its legal name. */
  name: string | null;
}

/** A source not read. */
export interface NotRead {
  /** The source. */
  source: string;
  /** Why. */
  reason: string;
}

/** Everything needed to check one witness statement with no network: the statement, its evidence manifest, the key list as read, and the exact mapping bytes. Written by `trooth verify --save-bundle`; read by `trooth verify --bundle` and the SDKs. A bundle is only as fresh as its key list. */
export interface VerificationBundle {
  /** The bundle format. */
  bundle: "trooth.verification-bundle.v1";
  /** When the bundle was written. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  created_at: string;
  /** The domain the bundle was saved for. A reader may ask about another; a statement for a different domain is a mismatch. */
  domain: string | null;
  /** The signed envelope, exactly as published. */
  statement: WitnessStatement;
  /** The evidence manifest, or null when none was saved. */
  manifest: EvidenceManifest | null;
  /** The key list as read when the bundle was written. */
  keys: BundleKeys;
  /** The exact mapping bytes, or null when none were saved. */
  mapping: BundleMapping | null;
  /** What the witness statement log answered when the bundle was written: the log key used, the receipt or null, and every correction. Absent in a bundle written before the log, or when the log was not read. */
  log?: BundleLog;
}

/** The log answer, carried so the log part can be checked offline too. */
export interface BundleLog {
  /** The log verifier key the receipt was checked against, as a signed-note key (name+hash+key). A pinned key, when the checker has one, replaces it. */
  vkey: string;
  /** The receipt for the statement, or null when the log held no entry for it. */
  receipt: LogReceipt | null;
  /** Every logged correction naming this statement, each with its own receipt. */
  corrections: LoggedCorrection[];
}

/** A correction envelope and its receipt. */
export interface LoggedCorrection {
  /** The correction envelope: its payload is a trooth.correction.v1 document in RFC 8785 bytes. */
  statement: WitnessStatement;
  /** The receipt for the correction. */
  receipt: LogReceipt;
}

/** The key list as read. */
export interface BundleKeys {
  /** The keys array of the key list. */
  keys: PublicKey[];
  /** When the key list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  list_read_at: string | null;
  /** Where it was read from: a URL or a file path. */
  source: string | null;
}

/** The mapping document, byte for byte. */
export interface BundleMapping {
  /** Where the bytes were read from. */
  url: string | null;
  /** The digest of the carried bytes, for display. A checker hashes the bytes itself and compares with the signed digest. */
  digest: string;
  /** The exact mapping bytes, standard base64. */
  bytes_base64: string;
}

/** The JSON document `trooth verify --json` writes, and the shape the SDKs return. The verdict is the only conclusion; everything else says how it was reached. */
export interface VerifyResult {
  /** The domain asked about, or the signed domain when none was asked. */
  domain: string | null;
  /** checked: v2 or v3, everything bound and matching. checked_v1: a v1 statement that checks. partially_checked: a mapping or manifest was not supplied. signature_not_trusted: malformed, invalid or untrusted key. mismatch: trusted, but a count, the domain, the mapping, the manifest or a log receipt disagrees. superseded: everything held, and a correction Trooth signed and logged withdraws or replaces the statement. */
  verdict: "checked" | "checked_v1" | "partially_checked" | "signature_not_trusted" | "mismatch" | "superseded";
  /** The statement version, or unknown. */
  version: "v1" | "v2" | "v3" | "unknown";
  /** The read_at the payload carries. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  read_at?: string | null;
  /** The reading id the payload carries. */
  reading_id?: string | null;
  /** trooth:statement: plus the hex SHA-256 of the exact payload bytes (docs/IDS.md). */
  statement_id?: string | null;
  /** valid, invalid or malformed. */
  signature: "valid" | "invalid" | "malformed";
  /** The signing key and whether it is trusted at read_at. */
  key: KeyTrust;
  /** The signed domain against the domain asked about. */
  subject: Subject;
  /** The mapping and manifest against their signed digests. */
  binding: Binding;
  /** Whether the signed counts agree with the signed checks. */
  counts: CountCheck;
  /** The witness statement log part of the check. Absent when the log was not asked (offline from saved files, --no-log) or the signature was not trusted. */
  log?: LogCheck;
  /** What a valid signature of this version shows and does not show, in words. */
  assurance: string;
  /** When the key list used was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  keys_read_at?: string | null;
  /** Where each input came from: a URL, a file path, or null when not supplied. */
  sources?: Record<string, string | null>;
}

/** The key decision. */
export interface KeyTrust {
  /** The key id the envelope names. */
  kid: string;
  /** The lifecycle state found on the key list. */
  state: "active" | "retired" | "compromised" | "revoked_unrecorded" | "unknown";
  /** Whether a valid signature from this key at this time is relied on. */
  trusted: boolean;
  /** Why, in words. */
  reason: string;
}

/** The subject decision. */
export interface Subject {
  /** The domain in the signed payload. */
  signed: string | null;
  /** The domain asked about. */
  asked: string | null;
  /** match, mismatch, or not_checked (no domain given, or the signature was not trusted). */
  status: "match" | "mismatch" | "not_checked";
}

/** The binding decision. */
export interface Binding {
  /** bound, partially_checked, mismatch, absent (v1 binds neither) or unchecked (signature not trusted). */
  status: "bound" | "partially_checked" | "mismatch" | "absent" | "unchecked";
  /** The mapping result. */
  mapping: "match" | "mismatch" | "not_supplied" | "absent";
  /** The manifest result. */
  manifest: "match" | "mismatch" | "not_supplied" | "absent";
}

/** What the log showed about the statement. */
export interface LogCheck {
  /** included: the receipt checks against a checkpoint signed by the log key. not_logged: the log holds no entry for it (reported, not a failure in this version). unavailable: the log could not be read. checkpoint_invalid: the checkpoint is not signed by the log key or names another log. proof_invalid: the receipt does not take this statement to the signed root. */
  status: "included" | "not_logged" | "unavailable" | "checkpoint_invalid" | "proof_invalid";
  /** The entry index the receipt names, or null. */
  index: number | null;
  /** The signed tree size the receipt is against, or null. */
  tree_size: number | null;
  /** Why, in words. */
  reason: string | null;
  /** Each correction the log returned and whether it checked. */
  corrections: CorrectionCheck[];
  /** The statement id of the first correction that checked, or null. */
  superseded_by: string | null;
  /** Where the log key came from: pinned in this release, --log-vkey, carried in a bundle, or served by the log. */
  vkey_source?: string | null;
}

/** One correction and whether it is relied on. */
export interface CorrectionCheck {
  /** True when it is signed by a trusted key, in RFC 8785 bytes, names this statement, and is included in the log. */
  valid: boolean;
  /** The statement id of the correction itself. */
  correction_statement_id: string | null;
  /** The reason code it carries. */
  code: string | null;
  /** withdrawn or replaced. */
  effect: string | null;
  /** The replacing statement id, for replaced. */
  replacement: string | null;
  /** When Trooth issued it, as Trooth asserts. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  issued_at: string | null;
  /** Why it is or is not relied on, in words. */
  reason: string | null;
}

/** The count decision. */
export interface CountCheck {
  /** True when every identity holds. */
  identities_hold: boolean;
  /** Each identity that does not hold, in words. */
  problems: string[];
}

/** The JSON a trooth.witness-statement.v1 payload holds. v1 binds the outcomes and counts only: no mapping, manifest, evaluator or subject scope. */
export interface WitnessPayloadV1 {
  /** The statement version. */
  statement: "trooth.witness-statement.v1";
  /** The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md). */
  reading_id: string;
  /** The domain the reading was taken of: lowercase, no trailing dot. */
  domain: string;
  /** When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  read_at: string;
  /** Every check in the reading. */
  checks: CheckV1[];
  /** The two counts, which must agree with the checks. */
  counts: CountsV1;
}

/** One check in a v1 reading. v1 carries no reason. */
export interface CheckV1 {
  /** The check id. */
  id: string;
  /** The check category. */
  category: string;
  /** probe or attest. */
  kind: string;
  /** One of three outcomes. */
  outcome: "as expected" | "not as expected" | "not read";
}

/** The two counts a v1 payload carries. */
export interface CountsV1 {
  /** Checks whose outcome is not `not read`. */
  read: number;
  /** Checks whose outcome is `as expected`. */
  as_expected: number;
}

/** The JSON a trooth.witness-statement.v2 payload holds. Its members are signed in exactly this order with no whitespace. It binds the check mapping, the evaluator, the subject scope and the evidence manifest. */
export interface WitnessPayloadV2 {
  /** The statement version. */
  statement: "trooth.witness-statement.v2";
  /** The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md). */
  reading_id: string;
  /** The domain the reading was taken of: lowercase, no trailing dot. */
  domain: string;
  /** When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  read_at: string;
  /** What the reading covered. */
  subject_scope: SubjectScope;
  /** The check mapping, bound by digest. */
  methodology: Methodology;
  /** The software that took the reading. */
  evaluator: Evaluator;
  /** The evidence manifest, bound by digest. */
  evidence_manifest: EvidenceManifestRef;
  /** Every check in the reading. */
  checks: Check[];
  /** Counts that must agree with the checks. */
  counts: Counts;
}

/** One check in the reading and its outcome. */
export interface Check {
  /** The check id in the check mapping the payload names (for example S1, L2). */
  id: string;
  /** The check category in the mapping (for example security, legal, ai, ip, business). */
  category: string;
  /** How the check is taken: `probe` reads the public surface; `attest` reads something the company published about itself. */
  kind: string;
  /** One of three outcomes. There is no fourth value and no score. */
  outcome: "as expected" | "not as expected" | "not read";
  /** Null when the outcome is `as expected`; otherwise why. */
  reason: CheckReason | null;
}

/** Why a check is not `as expected`. Present on every check whose outcome is `not read` or `not as expected`. */
export interface CheckReason {
  /** The reason code. source_unavailable, timeout, evaluator_limitation, carried_from_earlier_reading and check_misconfigured go with `not read`; contrary_observation and expected_item_absent go with `not as expected`. */
  code: "source_unavailable" | "timeout" | "evaluator_limitation" | "carried_from_earlier_reading" | "check_misconfigured" | "contrary_observation" | "expected_item_absent";
  /** The version of the reason vocabulary. */
  version: "trooth.check-explanations.v1";
  /** The public source the reason refers to, or null. Always null when `withheld` is true. */
  source_ref: string | null;
  /** True when the source behind this reason is not published (for example a private document); only a commitment to it is in the evidence manifest. */
  withheld: boolean;
  /** Why the source is withheld. Required, non-empty, when `withheld` is true; otherwise null. */
  withheld_reason: string | null;
}

/** Counts that MUST agree with the checks: read + not_read = in_reading; as_expected + not_as_expected = read; in_reading = the number of checks. They are reported apart and never added into one number. */
export interface Counts {
  /** Checks whose outcome is not `not read`. */
  read: number;
  /** Checks whose outcome is `as expected`. */
  as_expected: number;
  /** Checks whose outcome is `not as expected`. */
  not_as_expected: number;
  /** Checks whose outcome is `not read`. */
  not_read: number;
  /** All checks in the reading. */
  in_reading: number;
}

/** What the reading covered. */
export interface SubjectScope {
  /** The domain read. Equals the payload domain. */
  domain: string;
  /** Which surface was read. `public`: only what anyone can fetch. */
  surface: string;
  /** The number of checks in scope. Equals the number of checks listed. */
  checks_in_scope: number;
}

/** The exact check mapping the reading used, bound by digest. */
export interface Methodology {
  /** The name of the standard the mapping belongs to. */
  standard: string;
  /** The mapping version. */
  mapping_version: string;
  /** Where the exact mapping bytes are served. Immutable versions live under https://trooth.co/standard/check-mapping/. */
  mapping_url: string;
  /** `sha256:` plus the lowercase hex SHA-256 of the exact mapping bytes. */
  mapping_digest: string;
}

/** The software that took the reading. */
export interface Evaluator {
  /** The evaluator name. */
  name: string;
  /** The evaluator version. */
  version: string;
}

/** The evidence manifest the reading binds, by digest. */
export interface EvidenceManifestRef {
  /** `sha256:` plus the hex SHA-256 of the canonical manifest bytes (evidence-manifest.schema.json). */
  digest: string;
  /** The number of manifest entries. */
  entries: number;
  /** How the manifest bytes are formed: entries sorted by check_id, keys check_id then source or commitment, no whitespace, UTF-8. */
  canonicalization: string;
}

/** The JSON a trooth.witness-statement.v3 payload holds: the v2 content plus subject_id and signer, serialized as RFC 8785 (JCS). Every number is an integer between -(2^53 - 1) and 2^53 - 1, so every implementation produces the same bytes. */
export interface WitnessPayloadV3 {
  /** Every check in the reading. */
  checks: Check[];
  /** Counts that must agree with the checks. */
  counts: Counts;
  /** The domain the reading was taken of: lowercase, no trailing dot. */
  domain: string;
  /** The software that took the reading. */
  evaluator: Evaluator;
  /** The evidence manifest, bound by digest. */
  evidence_manifest: EvidenceManifestRef;
  /** The check mapping, bound by digest. */
  methodology: Methodology;
  /** When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z). */
  read_at: string;
  /** The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md). */
  reading_id: string;
  /** The signing key, inside the signed bytes. */
  signer: Signer;
  /** The statement version. */
  statement: "trooth.witness-statement.v3";
  /** The subject by its stable id, trooth:domain:<domain> (docs/IDS.md). MUST name the payload domain. */
  subject_id: string;
  /** What the reading covered. */
  subject_scope: SubjectScope;
}

/** The signing key, named inside the signed bytes so the envelope cannot point at another key. */
export interface Signer {
  /** The kid of the signing key. MUST equal the envelope key_id. */
  key_id: string;
  /** Who signs: trooth.co. */
  issuer: "trooth.co";
}

/** The signed envelope Trooth publishes as `witnessStatement` on a record. The signature covers the exact UTF-8 bytes of `payload`, nothing else. How to check it: docs/VERIFY.md in github.com/troothllc/trooth-cli. */
export interface WitnessStatement {
  /** The signing input: the exact JSON text that was signed. Parse it to read it; never re-serialize it to check it. Its `statement` field names the version (witness-payload.v1, v2 or v3). */
  payload: string;
  /** The Ed25519 signature over the payload bytes: `ed25519:` followed by standard base64 of the 64 signature bytes. */
  signature: string;
  /** The `kid` of the signing key on https://api.trooth.co/public/keys. A v3 payload names the same key inside the signed bytes, at signer.key_id. */
  key_id: string;
  /** The signature algorithm. Always Ed25519 (RFC 8032, pure EdDSA). */
  alg: "Ed25519";
  /** How the payload bytes were produced. `json-fixed-key-order-no-whitespace-utf8` for v1 and v2; `RFC8785` (JSON Canonicalization Scheme, integers only) for v3, where the payload MUST equal the canonical form of the JSON it holds. */
  canonicalization: "json-fixed-key-order-no-whitespace-utf8" | "RFC8785";
}
