// GENERATED by scripts/gen-types.mjs from schemas/ in github.com/troothllc/trooth-cli.
// Do not edit by hand: change the schema and run `node scripts/gen-types.mjs`.

package trooth

// CorrectionPayload: The JSON a trooth.correction.v1 payload holds: Trooth withdrawing or replacing a statement it signed. Signed like a v3 statement (RFC 8785 bytes, Ed25519, the signer inside the signed bytes) and entered in the witness statement log. The statement it corrects stays in the log; nothing is deleted.
type CorrectionPayload struct {
	// The payload type. One of: trooth.correction.v1.
	Statement string `json:"statement"`
	// An identifier for this correction, unique in the log.
	CorrectionID string `json:"correction_id"`
	// The statement id this correction withdraws or replaces. It must already be in the log.
	Supersedes string `json:"supersedes"`
	// The subject of the statement it corrects.
	SubjectID string `json:"subject_id"`
	// withdrawn: no statement takes its place. replaced: the replacement statement does. One of: withdrawn, replaced.
	Effect string `json:"effect"`
	// The replacing statement id, which must already be in the log; null for withdrawn.
	Replacement *string `json:"replacement"`
	// Why.
	Reason CorrectionReason `json:"reason"`
	// When Trooth issued it, as Trooth asserts. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	IssuedAt string `json:"issued_at"`
	// The signing key, inside the signed bytes.
	Signer Signer `json:"signer"`
}

// CorrectionReason: The reason for a correction.
type CorrectionReason struct {
	// evaluator_defect: the evaluator read wrongly. mapping_defect: the check mapping was wrong. source_misread: a source was misread. signing_key_compromised: the key that signed it is compromised. dispute_upheld: a dispute about the reading was upheld. withdrawn_by_trooth: withdrawn for another stated reason. One of: evaluator_defect, mapping_defect, source_misread, signing_key_compromised, dispute_upheld, withdrawn_by_trooth.
	Code string `json:"code"`
	// The reason in words, 10 to 1000 characters.
	Explanation string `json:"explanation"`
}

// DomainDeclaration: The domain-signed declaration a company publishes at https://<domain>/.well-known/trooth.json (docs/DECLARATION.md): its own Ed25519 key, its products, its APIs and its code repositories, signed with that key over the RFC 8785 bytes of the document without `signature`. At most 64 KB. It is self-signed: a declaration that checks shows that whoever controlled the site's content when it was read published this key and these subjects; it does not establish the legal entity or a person's authority to act for it. Added in trooth 0.14.0.
type DomainDeclaration struct {
	// The format. One of: trooth.declaration.v1.
	Format string `json:"format"`
	// The domain, lower case. It must equal the host the document is served from.
	Domain string `json:"domain"`
	// When the declaration was signed, ISO 8601 in UTC. Not in the future.
	IssuedAt string `json:"issued_at"`
	// When the declaration stops checking, ISO 8601 in UTC; after issued_at and at most 400 days after it.
	ExpiresAt string `json:"expires_at"`
	// Optional: the company's Trooth record, https://trooth.co/network/company/<slug>. The one URL not on the domain.
	Record *string `json:"record,omitempty"`
	// The company's own public keys, one to eight; more than one during a key rotation. Never a private key.
	Keys []DeclarationKey `json:"keys"`
	// Products the domain's owner names. Each url is on the domain or a subdomain of it.
	Products []DeclaredProduct `json:"products,omitempty"`
	// APIs the domain's owner names, each with an optional MCP server and the SHA-256 of its tool manifest.
	Apis []DeclaredApi `json:"apis,omitempty"`
	// Organizations or users on a code host (github.com, gitlab.com, bitbucket.org, codeberg.org) the domain's owner names.
	Repositories []string `json:"repositories,omitempty"`
	// Ed25519 over the RFC 8785 bytes of the document without this member, by one of `keys`.
	Signature DeclarationSignature `json:"signature"`
}

// DeclarationKey: An Ed25519 public key as a JWK (RFC 8037) with its id.
type DeclarationKey struct {
	// <domain>#<the RFC 7638 JWK thumbprint of the key, base64url>.
	Kid string `json:"kid"`
	// The key type. One of: OKP.
	Kty string `json:"kty"`
	// The curve. One of: Ed25519.
	Crv string `json:"crv"`
	// The 32-byte public key, base64url without padding.
	X string `json:"x"`
}

// DeclaredProduct: A product the domain's owner names. Its subject id is trooth:product:<domain>/<id>.
type DeclaredProduct struct {
	// The product's id, unique in the declaration.
	ID string `json:"id"`
	// The product's name, 1 to 200 characters.
	Name string `json:"name"`
	// An https URL on the domain or a subdomain of it.
	URL string `json:"url"`
}

// DeclaredMcp: The MCP server of an API.
type DeclaredMcp struct {
	// The MCP endpoint, an https URL on the domain or a subdomain of it.
	URL string `json:"url"`
	// Lowercase hex SHA-256 of the server's tool manifest (docs/EVIDENCE.md section 9).
	ManifestSha256 string `json:"manifest_sha256"`
}

// DeclaredApi: An API the domain's owner names.
type DeclaredApi struct {
	// The API's base URL, https, on the domain or a subdomain of it.
	BaseURL string `json:"base_url"`
	// Optional: its MCP server.
	Mcp *DeclaredMcp `json:"mcp,omitempty"`
}

// DeclarationSignature: The signature over the declaration.
type DeclarationSignature struct {
	// The kid of the key in `keys` that signed.
	Kid string `json:"kid"`
	// The algorithm. One of: Ed25519.
	Alg string `json:"alg"`
	// The canonicalization of the signed bytes. One of: RFC8785.
	Canonicalization string `json:"canonicalization"`
	// ed25519: and the 64-byte signature in base64.
	Value string `json:"value"`
}

// EvidenceManifest: The evidence manifest a v2 or v3 statement binds by digest, published beside the statement as `witnessEvidenceManifest`. Canonical bytes: entries sorted by check_id, each as {"check_id":..,"source":..} or {"check_id":..,"commitment":..}, no whitespace, UTF-8.
type EvidenceManifest []ManifestEntry

// ManifestEntry: One check and the evidence behind it: a public `source`, or a `commitment` to a private one. Exactly one of the two.
type ManifestEntry struct {
	// The check id. Unique in the manifest.
	CheckID string `json:"check_id"`
	// The public URL the check read.
	Source *string `json:"source,omitempty"`
	// `sha256:` plus the hex SHA-256 of salt, a newline byte and the private reference. Only its holder can open it.
	Commitment *string `json:"commitment,omitempty"`
}

// GuardDecideOutput: The one JSON document `trooth guard decide --json` prints on stdout when it decides or declines to: a GuardDecision when the policy covers the tool (exit 0 allow, 20 hold, 21 deny), or a GuardNotCovered when it does not (exit 0). A usage error prints the CLI's error document instead ({"ok": false, "error": "...", "exit": 2}), as every command does.
type GuardDecideOutput any

// GuardDecision: One decision of the Trooth guard (trooth/guard, docs/GUARD.md): allow, hold for a person, or deny an ACTION the customer's agent is about to take, under the customer's policy, with reason codes. It is made on the customer's machine and is never a statement about whether a company is safe. The contract is the one in section 8 of the Trooth Network brief; reasons may also carry a detail string. `trooth guard decide --json` prints this document when the policy covers the tool, and a GuardNotCovered ($defs/notCovered) when it does not; schemas/guard-decide-output.v1.schema.json accepts either.
type GuardDecision struct {
	// allow: every required check held and every rule passed. hold: route the action to a person. deny: a proof failed or a rule the customer marked absolute failed (or the customer's policy chose deny for no record or no source). One of: allow, hold, deny.
	Decision string `json:"decision"`
	// Why, one entry per check or rule. An allow carries only RULE_PASSED.
	Reasons []GuardReason `json:"reasons"`
	// Exact entity ID checked, e.g. trooth:domain:acme.com. Empty when the action named no host.
	Subject string `json:"subject"`
	// The policy the decision was made under.
	Policy GuardPolicyRef `json:"policy"`
	// The signed, logged facts the rules read.
	Evidence []GuardEvidence `json:"evidence"`
	// The intercepted tool call: name, target host, amount or data class. Stored locally, never sent to Trooth.
	Action map[string]any `json:"action,omitempty"`
	// When the decision was made (RFC 3339).
	DecidedAt string `json:"decided_at"`
}

// GuardNotCovered: What `trooth guard decide --json` prints when the policy does not cover the tool: nothing was decided, nothing was read, and the command exits 0. It is not an allow and carries no decision; the caller lets the call run as its own controls intend.
type GuardNotCovered struct {
	// Always false: the policy's applies_to.tools does not match the tool. One of: false.
	Covered bool `json:"covered"`
	// The tool name given with --tool.
	Tool string `json:"tool"`
	// The policy that does not cover the tool.
	Policy GuardPolicyRef `json:"policy"`
	// A plain sentence saying that nothing was decided.
	Note string `json:"note"`
}

// GuardReason: One reason code, with what it is about.
type GuardReason struct {
	// The reason code. One of: RULE_PASSED, EVIDENCE_MISSING, EVIDENCE_STALE, EVIDENCE_DISPUTED, NO_RECORD, SIGNATURE_INVALID, KEY_NOT_TRUSTED, NOT_IN_LOG, SUBJECT_MISMATCH, SCHEMA_UNSUPPORTED, ABSOLUTE_RULE_FAILED, SOURCE_UNREACHABLE.
	Code string `json:"code"`
	// Stable ID of the fact this reason is about
	FactID *string `json:"fact_id,omitempty"`
	// The customer's rule that produced this reason
	RuleID *string `json:"rule_id,omitempty"`
	// For EVIDENCE_MISSING: the claim type that would satisfy the rule
	Needed *string `json:"needed,omitempty"`
	// A plain sentence on what was found. Written by the guard, never copied from vendor content.
	Detail *string `json:"detail,omitempty"`
}

// GuardPolicyRef: Which policy, by id, version and the SHA-256 of its RFC 8785 canonical JSON.
type GuardPolicyRef struct {
	// The policy's name (its `policy` key).
	ID string `json:"id"`
	// The policy's version number.
	Version int64 `json:"version"`
	// SHA-256 (hex) of the RFC 8785 canonical JSON of the policy as parsed.
	Sha256 string `json:"sha256"`
}

// GuardEvidence: One signed, logged fact a rule read.
type GuardEvidence struct {
	// trooth:statement:<sha256>#<claim>: the statement and the claim read from it.
	FactID string `json:"fact_id"`
	// SHA-256 (hex) of the statement's exact payload bytes.
	StatementSha256 string `json:"statement_sha256"`
	// The statement's entry in Trooth's log, or null when it is not shown in the log.
	LogIndex *int64 `json:"log_index"`
	// When the fact was observed.
	ObservedAt string `json:"observed_at"`
	// When the fact stops being fresh for this rule (the rule's max_age_days, else the evidence class's stale-after), or null when unknown.
	StaleAfter *string `json:"stale_after"`
}

// GuardPolicy: A customer's guard policy (docs/GUARD.md section 3), written in YAML (the strict subset bin/lib/yaml-lite.mjs reads) or JSON. The guard refuses unknown keys, wrong types, duplicate rule ids, on_fail deny without absolute, and allow for source_unreachable or failMode. The policy's sha256 is the SHA-256 of the RFC 8785 canonical JSON of the document as parsed.
type GuardPolicy struct {
	// The policy's name.
	Policy string `json:"policy"`
	// The policy's version number; raise it on every change.
	Version int64 `json:"version"`
	// Free text for people; the guard never reads it.
	Description *string `json:"description,omitempty"`
	// Which actions are checked. Everything else passes straight through.
	AppliesTo GuardAppliesTo `json:"applies_to"`
	// Typed argument fields (dotted paths allowed) the target host is read from, in order. Default: url, endpoint, host, domain, base_url, webhook_url, email, to.
	HostFrom []string `json:"host_from,omitempty"`
	// What the guard needs from Trooth's log. Default: required true, min_witnesses 1.
	Log *GuardLogRequirement `json:"log,omitempty"`
	// The rules, each tested against signed, logged facts. Rule ids are unique.
	Rules []GuardRule `json:"rules"`
	// Hosts for CI mode (trooth guard ci).
	Destinations *GuardDestinations `json:"destinations,omitempty"`
	// The decision when no Trooth record exists for the host. Default hold. One of: hold, deny.
	UnknownCounterparty *string `json:"unknown_counterparty,omitempty"`
	// The decision when no Trooth source answers and no cached bundle is held. Default hold. allow is refused. One of: hold, deny.
	SourceUnreachable *string `json:"source_unreachable,omitempty"`
}

// GuardAppliesTo: The tools and HTTP destinations the policy covers.
type GuardAppliesTo struct {
	// Tool names; "*" stands for any run of characters (mcp__bank__*).
	Tools []string `json:"tools,omitempty"`
	// For the http adapter: methods and host patterns whose requests are checked.
	Http []GuardHttpTarget `json:"http,omitempty"`
}

// GuardHttpTarget: One method and host pattern (an exact host, or *. followed by a domain of at least two labels).
type GuardHttpTarget struct {
	// The HTTP method, or * for any.
	Method string `json:"method"`
	// The host pattern.
	Host string `json:"host"`
}

// GuardLogRequirement: Log inclusion and witness cosignatures the policy asks for.
type GuardLogRequirement struct {
	// Whether a statement must be shown in the log (hold NOT_IN_LOG otherwise). A failed proof denies either way.
	Required *bool `json:"required,omitempty"`
	// How many pinned witnesses must have cosigned a checkpoint covering the statement.
	MinWitnesses *int64 `json:"min_witnesses,omitempty"`
}

// GuardRule: One rule. A claim missing, stale or disputed holds; a rule marked absolute that fails denies.
type GuardRule struct {
	// The rule's id, unique in the policy.
	ID string `json:"id"`
	// Free text for people; the guard never reads it.
	Description *string `json:"description,omitempty"`
	// A claim with an optional maximum age, or a valid signature by a key in an accepted state.
	Require any `json:"require"`
	// hold (default), or deny for a rule marked absolute. One of: hold, deny.
	OnFail *string `json:"on_fail,omitempty"`
	// When true, the rule failing denies the action (ABSOLUTE_RULE_FAILED).
	Absolute *bool `json:"absolute,omitempty"`
}

// GuardClaimRequire: A claim read from a signed, logged Trooth artifact.
type GuardClaimRequire struct {
	// trooth_reading, check:<check_id>, legal_entity_registry_record, no_sanctions_name_match, no_sam_exclusion_name_match, domain_registration_record, security_txt_published, or domain_control_confirmed (since trooth 0.14.0, from a confirmed proof in the signed public record binding the domain to the company record or to its declaration key).
	Claim string `json:"claim"`
	// The oldest observation the rule accepts, in days. Default: the evidence class's stale-after.
	MaxAgeDays *int64 `json:"max_age_days,omitempty"`
}

// GuardSignatureRequire: A valid signature by a key in one of the accepted states at signing time.
type GuardSignatureRequire struct {
	// Always valid. One of: valid.
	Signature string `json:"signature"`
	// Accepted key states. Default both.
	KeyStatus []string `json:"key_status,omitempty"`
}

// GuardDestinations: For CI mode: hosts a build may add, and the hosts to watch.
type GuardDestinations struct {
	// Host patterns a build may add without failing.
	Allowed []string `json:"allowed,omitempty"`
	// Host patterns CI mode reports when added and not allowed. Default (empty): every new external host.
	Watch []string `json:"watch,omitempty"`
}

// KeyList: The body of https://api.trooth.co/public/keys, or a saved copy of it. Save it with the time you read it: a saved list cannot show a compromise announced later.
type KeyList struct {
	// Every key, current and past.
	Keys []PublicKey `json:"keys"`
	// When the list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ListReadAt *string `json:"list_read_at,omitempty"`
	// The kid of the key currently used for new statements.
	ActiveKid *string `json:"active_kid,omitempty"`
	// A note from the key service.
	Note *string `json:"note,omitempty"`
}

// PublicKey: One published key and its lifecycle. Only `kid`, `alg`, `encoding`, `public_key`, `status` and the three lifecycle times decide trust (docs/VERIFY.md section 3).
type PublicKey struct {
	// The key id a statement names in key_id.
	Kid string `json:"kid"`
	// Always Ed25519. One of: Ed25519.
	Alg string `json:"alg"`
	// How public_key is written: hex or base64. One of: hex, base64.
	Encoding *string `json:"encoding,omitempty"`
	// The 32-byte Ed25519 public key, in `encoding`.
	PublicKey string `json:"public_key"`
	// active, retired, revoked or compromised. One of: active, retired, revoked, compromised.
	Status string `json:"status"`
	// The same lifecycle state as written by the key service.
	State *string `json:"state,omitempty"`
	// When the key was retired. Statements carrying a read_at strictly before this stay trusted. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	RetiredAt *string `json:"retired_at,omitempty"`
	// When the key was found compromised. Nothing signed by it is relied on. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	CompromisedAt *string `json:"compromised_at,omitempty"`
	// When the key was revoked. A revocation with no compromise recorded is treated as a compromise. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	RevokedAt *string `json:"revoked_at,omitempty"`
	// When the key was created, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	CreatedAt *string `json:"created_at,omitempty"`
	// When the key was first used, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ActivatedAt *string `json:"activated_at,omitempty"`
	// When the key first appeared on the list. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	FirstListedAt *string `json:"first_listed_at,omitempty"`
	// A short fingerprint of the key, for display.
	Fingerprint *string `json:"fingerprint,omitempty"`
	// What the key is for, as a short label.
	Purpose *string `json:"purpose,omitempty"`
	// What the key signs, in words.
	Signs *string `json:"signs,omitempty"`
	// Lifecycle events, oldest first.
	Events []KeyEvent `json:"events,omitempty"`
}

// KeyEvent: One lifecycle event of a key.
type KeyEvent struct {
	// What happened (for example first_listed, retired, compromised).
	Event string `json:"event"`
	// When. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	At string `json:"at"`
	// A note, or null.
	Note *string `json:"note,omitempty"`
}

// LogReceipt: A receipt from Trooth's witness statement log (docs/LOG.md): the entry index, a checkpoint signed by the log key, and an RFC 9162 inclusion proof from the entry to the checkpoint root. The entry is RFC 8785 JSON of {kind, statement}; its leaf hash is SHA-256(0x00 || entry).
type LogReceipt struct {
	// The log origin, which the checkpoint must also name. One of: trooth.co/witness-log/v1.
	Log string `json:"log"`
	// The zero-based entry index.
	Index int64 `json:"index"`
	// The size of the signed tree the proof is against. Equals the checkpoint size.
	TreeSize int64 `json:"tree_size"`
	// Standard base64 of the 32-byte root at tree_size. Equals the checkpoint root.
	RootHash string `json:"root_hash"`
	// The RFC 9162 audit path, leaf to root, each a 32-byte hash in standard base64.
	InclusionProof []string `json:"inclusion_proof"`
	// A C2SP checkpoint (origin, size, base64 root, each on its own line) followed by a blank line and C2SP signed-note signature lines; the log key's line is an em dash, the key name and base64 of the 4-byte key hash and the 64-byte Ed25519 signature.
	Checkpoint string `json:"checkpoint"`
}

// McpToolsStatement: The payload Trooth signs for an MCP tool reading, carried as the payload of a witness-statement envelope (RFC 8785, Ed25519) and logged as an mcp_tools entry. It names every tool's description and definition hash, so the log alone tells when a server changed what it tells agents.
type McpToolsStatement struct {
	// The payload type. One of: trooth.mcp-tools.v1.
	Statement string `json:"statement"`
	// trooth:mcp:<host and path>.
	SubjectID string `json:"subject_id"`
	// The endpoint read.
	Endpoint string `json:"endpoint"`
	// The reading's read_at. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// The manifest hash.
	ManifestSha256 string `json:"manifest_sha256"`
	// Each tool's hashes, sorted by name.
	Tools []StatementTool `json:"tools"`
	// The previous manifest hash, or null for the first reading.
	PreviousManifestSha256 *string `json:"previous_manifest_sha256"`
	// SHA-256, hex, of the reading's RFC 8785 bytes.
	ReadingSha256 string `json:"reading_sha256"`
	// How those bytes were made. One of: RFC8785.
	ReadingCanonicalization string `json:"reading_canonicalization"`
	// When the statement was signed. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	IssuedAt string `json:"issued_at"`
	// The signing key, inside the signed bytes.
	Signer McpStatementSigner `json:"signer"`
}

// StatementTool: A tool as the statement names it.
type StatementTool struct {
	// The tool name.
	Name string `json:"name"`
	// The description hash.
	DescriptionSha256 string `json:"description_sha256"`
	// The definition hash.
	DefinitionSha256 string `json:"definition_sha256"`
}

// McpStatementSigner: The signing key.
type McpStatementSigner struct {
	// The kid on https://api.trooth.co/public/keys.
	KeyID string `json:"key_id"`
	// Always trooth.co. One of: trooth.co.
	Issuer string `json:"issuer"`
}

// McpToolsReading: The tool list of an MCP server as Trooth read it with no credentials, each tool's description and definition hashed. Served at https://api.trooth.co/scan/mcp-tools/reading?endpoint=<url>. A statement naming the reading is signed and logged as an mcp_tools entry when the manifest changed. docs/EVIDENCE.md section 9 in trooth-cli is the normative text. A hash says what was listed, not that a tool does what its description says.
type McpToolsReading struct {
	// The format. One of: trooth.mcp-tools.v1.
	Format string `json:"format"`
	// The MCP endpoint read (streamable HTTP).
	Endpoint string `json:"endpoint"`
	// trooth:mcp:<host and path>.
	SubjectID string `json:"subject_id"`
	// When it was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// What the server said about itself in initialize.
	Server McpServer `json:"server"`
	// Every tool listed, sorted by name, at most 500.
	Tools []ToolHash `json:"tools"`
	// SHA-256, hex, of the RFC 8785 bytes of [{name, definition_sha256}] sorted by name.
	ManifestSha256 string `json:"manifest_sha256"`
	// The manifest of the reading before this one, or null for the first.
	Previous *PreviousManifest `json:"previous"`
	// Tools added, removed or changed since the previous reading, or null for the first.
	Changed *ManifestDiff `json:"changed"`
	// What the reading is and is not.
	Note string `json:"note"`
	// When Trooth last read the server and found this manifest. Served beside the reading; not part of the bytes it names.
	LastChecked *string `json:"last_checked,omitempty"`
	// The statement naming the reading, and its log receipt. Not part of the bytes it names.
	Signed *McpToolsSigned `json:"signed,omitempty"`
}

// McpServer: The server's own description.
type McpServer struct {
	// serverInfo.name.
	Name *string `json:"name"`
	// serverInfo.version.
	Version *string `json:"version"`
	// The protocol version agreed.
	ProtocolVersion *string `json:"protocol_version"`
}

// ToolHash: One tool as listed.
type ToolHash struct {
	// The tool name.
	Name string `json:"name"`
	// The title, from the tool or its annotations.
	Title *string `json:"title"`
	// The description as listed (empty when there is none).
	Description string `json:"description"`
	// SHA-256, hex, of the description's UTF-8 bytes.
	DescriptionSha256 string `json:"description_sha256"`
	// SHA-256, hex, of the RFC 8785 bytes of the whole tool object as listed.
	DefinitionSha256 string `json:"definition_sha256"`
}

// PreviousManifest: The reading before.
type PreviousManifest struct {
	// Its manifest hash.
	ManifestSha256 string `json:"manifest_sha256"`
	// When it was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
}

// ManifestDiff: Tool names by what happened to them.
type ManifestDiff struct {
	// Tools new in this reading.
	Added []string `json:"added"`
	// Tools no longer listed.
	Removed []string `json:"removed"`
	// Tools whose definition hash changed.
	Changed []string `json:"changed"`
}

// McpToolsSigned: The statement naming the reading.
type McpToolsSigned struct {
	// SHA-256, hex, of the RFC 8785 bytes of the reading without last_checked and signed.
	ReadingSha256 string `json:"reading_sha256"`
	// The signed envelope; its payload is an mcp-tools-statement.v1 document. Null when it could not be signed.
	Statement *WitnessStatement `json:"statement"`
	// trooth:statement:<sha256 of the payload>.
	StatementID *string `json:"statement_id"`
	// The receipt of the statement as an mcp_tools entry, or null when it was not logged.
	Log *LogReceipt `json:"log"`
	// What could not be done, or null.
	Problem *string `json:"problem"`
	// The read_at of the reading that was logged.
	LoggedAtRead *string `json:"logged_at_read"`
}

// ProfileOutput: The one JSON document `trooth profile <domain|slug> --json` prints on stdout: a company's Trust Profile, section by section, read from GET https://trooth.co/api/network/profile?q=<domain>&contract=2 (schema https://trooth.co/schemas/network-profile.v2.schema.json). Each fact carries its value, who said it and its date when Trooth recorded one; a fact with no recorded date has date null, never a date borrowed from another field. The profile is the company's own declared record (facts Trooth observed are labeled as such) and is not signed: the one signed object is the witness statement, which `trooth verify` checks. Printed with exit 0 (found), 1 (no published record: found false, sections empty) or 6 (withheld: withheld true, sections empty). A usage, network or contract error prints the CLI's error document instead ({"ok": false, "error": "...", "exit": N}), as every command does.
type ProfileOutput struct {
	// The domain the profile was read for: the domain given, or the domain of the record whose slug was given.
	Subject string `json:"subject"`
	// The domain, URL or Trooth slug as it was typed.
	Query string `json:"query"`
	// The /api/network/profile contract version this CLI read. One of: 2.
	Contract int `json:"contract"`
	// When this CLI read the record, by this machine's clock, as an ISO 8601 date-time in UTC. It is not the date of any fact.
	ReadAt string `json:"read_at"`
	// True when the Network holds a published record for the subject (including a withheld one). False is an honest absence: it says nothing about the company.
	Found bool `json:"found"`
	// True when the record exists and is withheld while a report about it is reviewed; sections is then empty. Neither an absence nor a finding.
	Withheld bool `json:"withheld"`
	// Present when withheld: Trooth's own words on why, or null.
	WithheldReason *string `json:"withheld_reason,omitempty"`
	// The company name as published, or null when no record was found.
	Name *string `json:"name"`
	// The company's slug on the Network, or null when no record was found.
	Slug *string `json:"slug"`
	// Which record was read, as the projection states it.
	Record ProfileRecordRef `json:"record"`
	// Always false: the profile is not signed. Trooth signs only the witness statement for a reading it took of the company's public surface. One of: false.
	Signed bool `json:"signed"`
	// The command that checks the one signed object, the witness statement: trooth verify <domain>.
	VerifyWith string `json:"verify_with"`
	// When no record was found and the projection gives one, the address at which the company can claim its record; otherwise null. Never built by the CLI.
	ClaimURL *string `json:"claim_url"`
	// The section names --section asked for, in page order, or null for every section.
	RequestedSections []string `json:"requested_sections"`
	// True when the response carried the complete profile (the body's profile member). False when only the typed facts were carried: sections they do not cover are then unavailable.
	ProfilePresent bool `json:"profile_present"`
	// Every section the record carries, in the page's order, or those --section asked for. Empty when no record was found or it is withheld.
	Sections []ProfileSection `json:"sections"`
}

// ProfileRecordRef: Which record was read, as the projection states it: its page, the Trooth-Record-Version and Trooth-Record-Digest headers, and when the company last published a change.
type ProfileRecordRef struct {
	// The company's public Trust Profile page, or null.
	URL *string `json:"url"`
	// The Trooth-Record-Version response header, or null when the server did not state one.
	Version *int64 `json:"version"`
	// The Trooth-Record-Digest response header, or null.
	Digest *string `json:"digest"`
	// When the company last published a change to the record (the body's updatedAt), or null. It is the record's time, not a fact's.
	UpdatedAt *string `json:"updated_at"`
}

// ProfileSection: One section of the Trust Profile, as the record carries it.
type ProfileSection struct {
	// The section name: overview, identity, history, funding, product, pricing, stack, security, privacy, ai, hosting, infrastructure, procurement, relationships, proof, people, documents, evidence, cards or faq, the names the MCP tool trooth_public_trust_profile takes; unsorted for typed facts whose category maps to none of them; or a section id the record adds later.
	Name string `json:"name"`
	// The section title as the page shows it.
	Title string `json:"title"`
	// published: the company shows content here. not_published: the company left it empty; printed "not published" and never filled in. hidden_by_company: the company chose not to show it; no values are carried. unavailable: Trooth could not read it on this load (or the response carried no profile); it is not empty. request_only: the content exists behind a request and is never carried. One of: published, not_published, hidden_by_company, unavailable, request_only.
	State string `json:"state"`
	// Who said what is in this section, as the record labels it, or null when the record carries no label.
	Provenance *string `json:"provenance"`
	// provenance in words, as the text output prints it.
	SaidBy *string `json:"said_by"`
	// What the record says to say about this section, or null.
	Meaning *string `json:"meaning"`
	// The page that shows this section, or null.
	URL *string `json:"url"`
	// Every fact in the section, in the page's order: the section's fields, then each group's fields and items, then typed facts the page does not show. Empty for a section that is not published.
	Facts []ProfileFact `json:"facts"`
	// The notes the record attaches to the section, its groups and its items.
	Notes []ProfileNote `json:"notes"`
}

// ProfileFact: One fact: its value, who said it and its date when one is recorded.
type ProfileFact struct {
	// The field name, as words.
	Label string `json:"label"`
	// The value as published, as text. A group item published by name only is one fact whose label is the group title and whose value is the item's name.
	Value string `json:"value"`
	// The group the fact is in, as the page titles it, or null for a section-level field. Other recorded facts marks a typed fact the page does not show.
	Group *string `json:"group"`
	// The item within the group (for example one product or one sub-processor), or null.
	Item *string `json:"item"`
	// Who said it: the typed fact's origin when the fact is joined to one, else the label of its group or section. One of: company_declared, trooth_observation, public_sources, named_customers, mixed.
	Provenance string `json:"provenance"`
	// Who said it, in words (the company (declared), Trooth (observed), public source: <name>, ...).
	SaidBy string `json:"said_by"`
	// The typed fact key (category.field, for example identity.legal-name) when the fact is joined to a typed fact with the same label and value in the same section; otherwise null.
	Key *string `json:"key"`
	// The typed fact's origin, or null when the fact is not joined to one.
	Origin *string `json:"origin"`
	// Where the value can be read: the typed fact's sourceReference when there is one, else the page that shows the section.
	Source *string `json:"source"`
	// The date Trooth recorded for this fact, as an ISO 8601 date-time: the typed fact's claim.declaredAt for a company declaration, else its claim.observedAt. Null when none is recorded (printed "date unknown"); never the record's update time, a reading's time or another fact's date.
	Date *string `json:"date"`
	// declared (claim.declaredAt) or observed (claim.observedAt); null when date is null.
	DateKind *string `json:"date_kind"`
	// True when another source gave a different account of this fact; the accounts are listed, and Trooth does not choose between them.
	Contested bool `json:"contested"`
	// When contested, each account with who gave it, in the record's fixed order, which is not a ranking. Empty otherwise.
	Accounts []ProfileAccount `json:"accounts"`
	// Always false: no fact is signed by anyone. One of: false.
	Signed bool `json:"signed"`
}

// ProfileAccount: One source's account of a contested fact.
type ProfileAccount struct {
	// Who gave this account. One of: company-declared, witnessed, public-source.
	Origin string `json:"origin"`
	// The account, as text.
	Value string `json:"value"`
}

// ProfileNote: A note the record attaches to a section, a group or an item.
type ProfileNote struct {
	// The group the note belongs to, or null for a section note.
	Group *string `json:"group"`
	// The item the note belongs to, or null.
	Item *string `json:"item"`
	// The note, as the record words it.
	Text string `json:"text"`
}

// PublicRecordStatement: The payload Trooth signs for a public record reading: it names the reading by the SHA-256 of its RFC 8785 bytes. Carried as the `payload` of a witness-statement envelope (RFC 8785, Ed25519) under `signed.statement` in a reading, and logged as a public_record entry. The signature says what Trooth read and when, not that what the sources say is true.
type PublicRecordStatement struct {
	// The payload type. One of: trooth.public-record.v1.
	Statement string `json:"statement"`
	// trooth:domain:<domain>.
	SubjectID string `json:"subject_id"`
	// The domain read.
	Domain string `json:"domain"`
	// The reading's read_at. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// SHA-256, hex, of the reading's RFC 8785 bytes without `signed`.
	RecordSha256 string `json:"record_sha256"`
	// How those bytes were made. One of: RFC8785.
	RecordCanonicalization string `json:"record_canonicalization"`
	// The reading's entity id, or null.
	EntityID *string `json:"entity_id"`
	// Each binding's id and status.
	Bindings []BindingStatus `json:"bindings"`
	// How many responses the reading read.
	Sources int64 `json:"sources"`
	// When the statement was signed. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	IssuedAt string `json:"issued_at"`
	// The signing key, inside the signed bytes.
	Signer StatementSigner `json:"signer"`
}

// BindingStatus: A binding as the statement names it.
type BindingStatus struct {
	// trooth:cik or trooth:lei id.
	ID string `json:"id"`
	// The binding status.
	Status string `json:"status"`
}

// StatementSigner: The signing key.
type StatementSigner struct {
	// The kid on https://api.trooth.co/public/keys.
	KeyID string `json:"key_id"`
	// Always trooth.co. One of: trooth.co.
	Issuer string `json:"issuer"`
}

// PublicRecordReading: What a company has published outside its own website, read from the authorities that hold it (SEC EDGAR, the GLEIF LEI registry, DNS, a Certificate Transparency monitor, the OFAC list, and since trooth 0.12.0 SAM.gov, the USPTO, four state registries, the FTC and RDAP), beside what its own site states, and the evidence tying each identifier to the domain. Served at https://api.trooth.co/scan/public-record/<domain>. Every fact carries the URL to read it again. Since trooth 0.11.0 each reading also carries `signed`: a statement naming the SHA-256 of the reading's RFC 8785 bytes (everything except `signed`), signed with Trooth's statement key and logged. Nothing in it grades, rates or ranks a company. docs/EVIDENCE.md in trooth-cli is the normative text.
type PublicRecordReading struct {
	// The format. One of: trooth.public-record.v1.
	Format string `json:"format"`
	// The domain read.
	Domain string `json:"domain"`
	// trooth:domain:<domain>.
	SubjectID string `json:"subject_id"`
	// When Trooth read the sources. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// What the company's own pages say about which legal entity it is.
	Site SiteRead `json:"site"`
	// Each identifier found and the evidence for and against tying it to the domain.
	Bindings []EntityBinding `json:"bindings"`
	// The SEC filer's record, or null when no filer was identified.
	Sec *SecRecord `json:"sec"`
	// The LEI record, or null when none was identified.
	Lei *LeiRecord `json:"lei"`
	// Mail-authentication records beyond SPF and DMARC, and DNSSEC.
	Dns []PublicFact `json:"dns"`
	// The legal entity the domain is tied to, when a binding is corroborated; null otherwise. Added in trooth 0.11.0.
	Entity *Entity `json:"entity,omitempty"`
	// Unexpired certificates for the exact domain name in Certificate Transparency logs, as a CT monitor returned them; null when it did not answer. Added in trooth 0.11.0.
	Certificates *Certificates `json:"certificates,omitempty"`
	// The site's /.well-known/security.txt (RFC 9116), or null when there is none or the site opted out of being read. Added in trooth 0.11.0.
	SecurityTxt *SecurityTxt `json:"security_txt,omitempty"`
	// Entries on the OFAC sanctions list with exactly the legal names above. A name match is not an identification. Null when the list could not be read or no name was found. Added in trooth 0.11.0.
	Sanctions *Sanctions `json:"sanctions,omitempty"`
	// Every response read for this reading, with the SHA-256 of the bytes read; Trooth keeps the bytes under that hash so a disputed fact can be replayed. Added in trooth 0.11.0.
	Sources []Source `json:"sources,omitempty"`
	// Each source that was not read, or did not answer, and why. A source not read is never guessed at.
	NotRead []NotRead `json:"not_read"`
	// What the reading is and is not, as a paragraph.
	Note string `json:"note"`
	// SAM.gov registrations and exclusions under the legal name, or null when SAM.gov was not read (not_read says why). A name match is not an identification. Added in trooth 0.12.0.
	Sam *SamReading `json:"sam,omitempty"`
	// Patent applications whose first applicant is the legal name, from the USPTO Open Data Portal, or null when it was not read. Added in trooth 0.12.0.
	Patents *PatentReading `json:"patents,omitempty"`
	// Exact-name entries in the state business registries that publish open data (New York, Colorado, Connecticut, Oregon). A name match is not an identification. Added in trooth 0.12.0.
	Registries []RegistryEntry `json:"registries,omitempty"`
	// Hart-Scott-Rodino early termination notices the FTC published naming the legal name as a party, or null when they were not read. Added in trooth 0.12.0.
	MergerReview *MergerReview `json:"merger_review,omitempty"`
	// The domain's registration, from RDAP, or null when no RDAP service answered. Added in trooth 0.12.0.
	DomainRegistration *DomainRegistration `json:"domain_registration,omitempty"`
	// What the sources in this reading record as having changed (renames, acquisitions and dispositions, changes in control, previous legal names, parents, merger review, domain registration), newest first. Added in trooth 0.12.0.
	Changes []Change `json:"changes,omitempty"`
	// Every subject this reading names, each with why: the domain, the entity, filer and LEI ids, jurisdictions, state registry entries, SAM.gov UEIs, and the code repositories, APIs and MCP servers the home page links to (docs/IDS.md). Added in trooth 0.12.0.
	Subjects []NamedSubject `json:"subjects,omitempty"`
	// Each class of evidence in this reading with its stale-after rule, when it was observed and what it does not establish (docs/EVIDENCE.md section 10). Optional; added in trooth 0.13.0.
	EvidenceClasses []EvidenceClass `json:"evidence_classes,omitempty"`
	// What changed since the previous cached reading of the same domain (docs/EVIDENCE.md section 10). Optional; added in trooth 0.13.0.
	Continuity *Continuity `json:"continuity,omitempty"`
	// Each proof that binds two subjects, with its method and status (docs/EVIDENCE.md section 11): the domain to the company record (dns_txt, domain_email_code or identity_provider_sign_in, from Trooth's record of the claim or the challenge TXT), the domain to the company's own key (domain_signed_declaration, and dns_txt when the key pin matches), the domain to a code repository (repository_control). Optional; added in trooth 0.14.0.
	Proofs []Proof `json:"proofs,omitempty"`
	// The domain-signed declaration read at https://<domain>/.well-known/trooth.json (docs/DECLARATION.md), or null when it was not looked for. Only what checked is carried into subjects. Optional; added in trooth 0.14.0.
	Declaration *DeclarationReading `json:"declaration,omitempty"`
	// The statement that names this reading, and its log receipt. Not part of the bytes it names. Added in trooth 0.11.0.
	Signed *Signed `json:"signed,omitempty"`
}

// SamReading: SAM.gov, read under one legal name with Trooth's key (the key is never in the record). Cached for 30 days per name, so read_at can be earlier than the reading's.
type SamReading struct {
	// The SAM.gov API read.
	Source string `json:"source"`
	// When SAM.gov was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// The legal names searched.
	NamesChecked []string `json:"names_checked"`
	// Entity registrations with exactly that legal name, at most 10.
	Registrations []SamRegistration `json:"registrations"`
	// Exclusion records with exactly that name, at most 20. A name match is not an identification.
	Exclusions []SamExclusion `json:"exclusions"`
}

// SamRegistration: A SAM.gov entity registration.
type SamRegistration struct {
	// The Unique Entity ID.
	Uei *string `json:"uei"`
	// The CAGE code.
	Cage *string `json:"cage"`
	// The legal business name registered.
	LegalName string `json:"legal_name"`
	// The registration status.
	Status *string `json:"status"`
	// The registration expiration date.
	Expires *string `json:"expires"`
	// The purpose of registration.
	Purpose *string `json:"purpose"`
}

// SamExclusion: A SAM.gov exclusion record.
type SamExclusion struct {
	// The name excluded.
	Name string `json:"name"`
	// The UEI on the record.
	Uei *string `json:"uei"`
	// The CAGE code on the record.
	Cage *string `json:"cage"`
	// Firm, Individual, Vessel or Special Entity Designation.
	Classification *string `json:"classification"`
	// The exclusion type.
	Type *string `json:"type"`
	// The exclusion program.
	Program *string `json:"program"`
	// The excluding agency.
	Agency *string `json:"agency"`
	// The activation date.
	Active *string `json:"active"`
	// The termination date, or Indefinite.
	Terminates *string `json:"terminates"`
	// The record status.
	RecordStatus *string `json:"record_status"`
}

// PatentReading: Patent applications from the USPTO Open Data Portal. Cached for 7 days per name.
type PatentReading struct {
	// The search API read.
	Source string `json:"source"`
	// When it was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// The first-applicant names searched.
	ApplicantNames []string `json:"applicant_names"`
	// How many applications the search counted.
	Applications int64 `json:"applications"`
	// The newest applications, at most 5.
	Recent []PatentApplication `json:"recent"`
}

// PatentApplication: A patent application.
type PatentApplication struct {
	// The application number.
	Application string `json:"application"`
	// The title of the invention.
	Title *string `json:"title"`
	// The filing date.
	Filed *string `json:"filed"`
	// The application status.
	Status *string `json:"status"`
	// The patent number, once granted.
	Patent *string `json:"patent"`
	// The grant date.
	Granted *string `json:"granted"`
}

// RegistryEntry: An entry in a state business registry with exactly the legal name.
type RegistryEntry struct {
	// The registry's jurisdiction, ISO 3166-2.
	Jurisdiction string `json:"jurisdiction"`
	// The registry and dataset.
	Registry string `json:"registry"`
	// The entity's number in that registry.
	ID string `json:"id"`
	// The name as registered.
	Name string `json:"name"`
	// The status the registry gives (Active for the datasets of active entities only).
	Status *string `json:"status"`
	// The entity type.
	EntityType *string `json:"entity_type"`
	// The formation or registration date in that state.
	Formed *string `json:"formed"`
	// Where the entity was formed, as the registry writes it.
	FormationJurisdiction *string `json:"formation_jurisdiction"`
	// The open-data URL for this entry.
	Source string `json:"source"`
}

// MergerReview: FTC early termination notices under the HSR Act, searched by words of the legal name and kept when a party has exactly that name. Cached for 7 days per name.
type MergerReview struct {
	// The FTC API read.
	Source string `json:"source"`
	// When it was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// The legal names searched.
	NamesChecked []string `json:"names_checked"`
	// Notices naming the company as a party, at most 20.
	Notices []MergerNotice `json:"notices"`
	// How many notices the word search returned before names were compared.
	MatchedInSearch int64 `json:"matched_in_search"`
}

// MergerNotice: An early termination notice.
type MergerNotice struct {
	// The HSR transaction number.
	Transaction string `json:"transaction"`
	// The date early termination was granted.
	Date *string `json:"date"`
	// The acquiring person.
	Acquiring *string `json:"acquiring"`
	// The acquired person.
	Acquired *string `json:"acquired"`
	// The acquired entities named.
	AcquiredEntities []string `json:"acquired_entities"`
	// The company's role in the notice. One of: acquiring, acquired.
	Role string `json:"role"`
	// The notice on ftc.gov.
	URL string `json:"url"`
}

// DomainRegistration: A domain's registration from RDAP (RFC 9083).
type DomainRegistration struct {
	// The RDAP URL read.
	Source string `json:"source"`
	// The registrar.
	Registrar *string `json:"registrar"`
	// The registration date.
	Registered *string `json:"registered"`
	// The last-changed date.
	Changed *string `json:"changed"`
	// The expiration date.
	Expires *string `json:"expires"`
	// The last transfer date.
	Transferred *string `json:"transferred"`
	// EPP status values.
	Status []string `json:"status"`
}

// Change: A change a source records.
type Change struct {
	// What changed. One of: renamed, previous_legal_name, acquisition_or_disposition, change_in_control, merger_review, parent, domain_registered, domain_transferred.
	Kind string `json:"kind"`
	// When, as the source dates it; null when it gives no date.
	Date *string `json:"date"`
	// The change in words.
	Detail string `json:"detail"`
	// Where to read it.
	Source string `json:"source"`
}

// NamedSubject: A subject the reading names (docs/IDS.md).
type NamedSubject struct {
	// The Trooth id.
	ID string `json:"id"`
	// What it names. representative: a contact the site publishes in security.txt (a trooth:contact id); not a person authorized to act for the entity. signing_authority: the key that signed this reading's statement (a trooth:key id), named at signing. Since trooth 0.14.0: company: the company's Trooth record (a trooth:company id). product: a product named in the domain's signed declaration (trooth:product:<domain>/<id>); never inferred from a name match. person: the representative Trooth recorded at claim time (trooth:person:<16 hex>); no personal data in the id. signing_authority is also the company's own key (trooth:key:<domain>#<thumbprint>) from a declaration that checks. api from the declaration names the MCP manifest hash in basis. code_repository is marked repository_control when that proof is confirmed. One of: domain, entity, sec_filer, lei, jurisdiction, state_registry, sam_uei, code_repository, api, mcp_server, representative, signing_authority, company, product, person.
	Kind string `json:"kind"`
	// Why the reading names it.
	Basis string `json:"basis"`
}

// Entity: A legal entity, named by a Trooth id derived from its LEI or SEC CIK (docs/IDS.md).
type Entity struct {
	// trooth:entity:lei:<LEI> when the LEI binding is corroborated, otherwise trooth:entity:cik:<CIK>.
	ID string `json:"id"`
	// The legal name the registry holds.
	Name *string `json:"name"`
	// The corroborated identifiers (trooth:lei, trooth:cik).
	Identifiers []string `json:"identifiers"`
	// Which bindings are corroborated.
	Basis string `json:"basis"`
}

// Certificates: Certificates for the exact domain name in Certificate Transparency logs.
type Certificates struct {
	// The CT monitor URL read.
	Source string `json:"source"`
	// How many unexpired certificates the monitor returned.
	Unexpired int64 `json:"unexpired"`
	// The issuing authorities, at most 10.
	Issuers []string `json:"issuers"`
	// The latest not-before time.
	NewestIssued *string `json:"newest_issued"`
	// The earliest not-after time.
	SoonestExpiry *string `json:"soonest_expiry"`
	// True when the monitor's first page was full, so there may be more.
	PageFull bool `json:"page_full"`
}

// SecurityTxt: A security.txt file (RFC 9116).
type SecurityTxt struct {
	// Where it was read.
	URL string `json:"url"`
	// Contact fields, at most 5.
	Contacts []string `json:"contacts"`
	// The Expires field.
	Expires *string `json:"expires"`
	// Whether Expires was in the past when read; null when it does not parse.
	Expired *bool `json:"expired"`
	// The Policy field.
	Policy *string `json:"policy"`
	// Canonical fields.
	Canonical []string `json:"canonical"`
	// Whether the file is OpenPGP clear-signed. The signature is not checked.
	Signed bool `json:"signed"`
}

// Sanctions: An exact-name check against a sanctions list.
type Sanctions struct {
	// The list and the part of it read.
	List string `json:"list"`
	// The list URL.
	Source string `json:"source"`
	// When the list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// The legal names checked.
	NamesChecked []string `json:"names_checked"`
	// Entries with exactly one of those names (case, punctuation and suffix spellings folded). A name match is not an identification.
	Matches []SanctionsEntry `json:"matches"`
}

// SanctionsEntry: A list entry.
type SanctionsEntry struct {
	// The entry number on the list.
	Uid string `json:"uid"`
	// The name as listed.
	Name string `json:"name"`
	// The sanctions programs.
	Programs string `json:"programs"`
}

// Source: One response read.
type Source struct {
	// The URL requested.
	URL string `json:"url"`
	// The HTTP status.
	Status int64 `json:"status"`
	// SHA-256 of the bytes read, hex.
	Sha256 string `json:"sha256"`
	// How many bytes were read.
	Bytes int64 `json:"bytes"`
	// False when only the start of the document was read (a filing's first 256 KB).
	Complete bool `json:"complete"`
	// When it was requested. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	FetchedAt string `json:"fetched_at"`
}

// Signed: The statement naming the reading, and its log receipt.
type Signed struct {
	// SHA-256, hex, of the RFC 8785 bytes of the reading without `signed` (finite numbers in ECMAScript shortest form).
	RecordSha256 string `json:"record_sha256"`
	// How those bytes were made. One of: RFC8785.
	RecordCanonicalization string `json:"record_canonicalization"`
	// The signed envelope; its payload is a public-record-statement.v1 document. Null when the reading could not be signed.
	Statement *WitnessStatement `json:"statement"`
	// trooth:statement:<sha256 of the payload>.
	StatementID *string `json:"statement_id"`
	// The receipt of the statement as a public_record entry of the witness statement log, or null when it was not logged.
	Log *LogReceipt `json:"log"`
	// What could not be done (not signed, or signed and not logged), or null.
	Problem *string `json:"problem"`
}

// PublicFact: One fact as its source published it, with the URL it was read from.
type PublicFact struct {
	// A stable key, source.field (for example sec.tickers, lei.jurisdiction, dns.mta_sts).
	Key string `json:"key"`
	// The fact as words.
	Label string `json:"label"`
	// The value as published: text, a number, true or false, a list of text, or null when the source states nothing.
	Value any `json:"value"`
	// Where it was read: a URL, or dns:<name> <type> for a DNS record.
	Source string `json:"source"`
}

// BindingEvidence: One piece of evidence for or against a binding.
type BindingEvidence struct {
	// For: filing_namespace_names_domain, registry_lists_domain, through_corroborated_filer (these tie the identifier to the domain), site_names_registry_name (a claim by the site), registries_agree, edgar_names_lei. Against: registry_lists_other_domain, registries_disagree, edgar_names_other_lei.
	Kind string `json:"kind"`
	// What was seen, as a sentence.
	Detail string `json:"detail"`
	// Where it was seen, or null when it follows from other evidence.
	Source *string `json:"source"`
}

// EntityBinding: A link between the domain and a legal-entity identifier, with the evidence for and against it. Nothing is asserted beyond the evidence.
type EntityBinding struct {
	// cik (SEC Central Index Key) or lei (Legal Entity Identifier). One of: cik, lei.
	Identifier string `json:"identifier"`
	// The identifier: 10 digits for a CIK, 20 characters for an LEI.
	Value string `json:"value"`
	// The stable id: trooth:cik:<10 digits> or trooth:lei:<LEI> (docs/IDS.md).
	ID string `json:"id"`
	// How the identifier was found: asked (given by the requester), ticker, site_legal_name (the legal name the site states matched exactly one listed SEC filer), edgar_lei_field, registry_name_match (exact legal name and, when the SEC gives one, the jurisdiction). One of: asked, ticker, site_legal_name, edgar_lei_field, registry_name_match.
	FoundBy string `json:"found_by"`
	// corroborated: authoritative evidence ties it to the domain (the company's own filing or the registry record names the domain). claimed_by_site: the site names this entity, and nothing authoritative ties it. registries_only: registries agree with each other, nothing ties the domain. uncorroborated: no evidence either way. contradicted: authoritative evidence points elsewhere. not_found: the registry holds no such identifier. One of: corroborated, claimed_by_site, registries_only, uncorroborated, contradicted, not_found.
	Status string `json:"status"`
	// What ties the identifier to the domain, strongest first. regulator_filing: the company's 10-K XBRL namespace names the domain. registry_record: the LEI registry record lists the domain. site_statement: the site states the legal name; this is the site's claim. registry_name_match: a name match only; nothing ties the domain. asked: the caller supplied the identifier and nothing above ties it. none: no evidence ties it. Optional; added in trooth 0.13.0 (docs/EVIDENCE.md section 10). dns_txt: a TXT record in the domain's zone (Trooth's claim challenge at _trooth-challenge.<domain> with a value starting trooth-domain-challenge=, or the key pin trooth-key=<thumbprint> at _trooth-key.<domain>). domain_signed_declaration: a /.well-known/trooth.json that checks (docs/DECLARATION.md). identity_provider_sign_in: the publisher signed in through the company's identity provider at the domain (Google Workspace hosted domain or Microsoft Entra tenant), as Trooth recorded at claim time. domain_email_code: a code sent to a mailbox at the domain, as Trooth recorded at claim time. repository_control: the code host marks a domain of the organization as confirmed by the code host (GitHub is_verified). The five values after none were added in trooth 0.14.0. One of: regulator_filing, registry_record, site_statement, registry_name_match, asked, none, dns_txt, domain_signed_declaration, identity_provider_sign_in, domain_email_code, repository_control.
	ProofMethod *string `json:"proof_method,omitempty"`
	// Evidence for the binding.
	For []BindingEvidence `json:"for"`
	// Evidence against it.
	Against []BindingEvidence `json:"against"`
}

// Filing: One SEC filing, as EDGAR lists it.
type Filing struct {
	// The form type (10-K, 10-Q, 8-K, DEF 14A, 20-F ...).
	Form string `json:"form"`
	// The filing date, YYYY-MM-DD.
	Filed string `json:"filed"`
	// The period or event date, when EDGAR gives one.
	ReportDate *string `json:"report_date"`
	// For an 8-K, the item numbers it reports (for example 1.05, 4.01).
	Items []string `json:"items"`
	// EDGAR's description of the primary document.
	Description *string `json:"description"`
	// The primary document on www.sec.gov.
	URL string `json:"url"`
}

// FinancialFact: A value the company filed in XBRL, as it filed it: the latest annual (10-K, full fiscal year) value of the concept.
type FinancialFact struct {
	// The XBRL concept, taxonomy:Name.
	Tag string `json:"tag"`
	// The concept as words.
	Label string `json:"label"`
	// The value as filed.
	Value float64 `json:"value"`
	// The unit (USD).
	Unit string `json:"unit"`
	// The period start for a flow such as revenue; null for a balance such as assets.
	PeriodStart *string `json:"period_start"`
	// The period end.
	PeriodEnd string `json:"period_end"`
	// The form the value was filed in.
	Form string `json:"form"`
	// The filing date.
	Filed string `json:"filed"`
	// The accession number of that filing.
	Accession string `json:"accession"`
	// The data.sec.gov URL the value was read from.
	Source string `json:"source"`
}

// SiteRead: The legal names the company's pages state in copyright notices.
type SiteRead struct {
	// Each legal name stated, with the page.
	LegalNames []SiteName `json:"legal_names"`
	// Whether any page of the site could be read.
	Read bool `json:"read"`
	// Why no name was found, or why the site was not read (for example its robots.txt opts out).
	Reason *string `json:"reason"`
	// Pages the home page links to on the company's own domain: investor relations, trust center, security, status, sustainability. Linked, not read. Added in trooth 0.11.0.
	Links []SiteLink `json:"links,omitempty"`
}

// SiteLink: A page the home page links to.
type SiteLink struct {
	// What the page is. One of: investor_relations, trust_center, security, status, sustainability.
	Kind string `json:"kind"`
	// The link, without query or fragment.
	URL string `json:"url"`
}

// SiteName: A legal name a page states.
type SiteName struct {
	// The name as written.
	Name string `json:"name"`
	// The page.
	Source string `json:"source"`
}

// SecRecord: The SEC filer's registration facts, filings and annual XBRL values.
type SecRecord struct {
	// The Central Index Key, 10 digits.
	Cik string `json:"cik"`
	// Registration facts on file with the SEC.
	Facts []PublicFact `json:"facts"`
	// The latest filing of each key form type, keyed by form.
	Latest map[string]Filing `json:"latest"`
	// 8-K filings of the last two years, newest first, at most 50.
	Events []Filing `json:"events"`
	// The earliest date the events cover.
	EventsCoverSince *string `json:"events_cover_since"`
	// 8-K filings reporting Item 1.05, a material cybersecurity incident.
	CybersecurityIncidents []Filing `json:"cybersecurity_incidents"`
	// 8-K filings reporting Item 4.01, a change of certifying accountant.
	AuditorChanges []Filing `json:"auditor_changes"`
	// 8-K filings reporting Item 4.02, non-reliance on financial statements issued before.
	NonReliance []Filing `json:"non_reliance"`
	// Forms 3, 4 and 5 filed in the last 90 days.
	InsiderFormsLast90Days int64 `json:"insider_forms_last_90_days"`
	// Annual values as filed.
	Financials []FinancialFact `json:"financials"`
}

// LeiRecord: The Legal Entity Identifier record.
type LeiRecord struct {
	// The LEI.
	Lei string `json:"lei"`
	// The record's facts.
	Facts []PublicFact `json:"facts"`
	// The direct parent the record reports, or null.
	DirectParent *Parent `json:"direct_parent"`
	// The ultimate parent the record reports, or null.
	UltimateParent *Parent `json:"ultimate_parent"`
}

// Parent: A parent entity.
type Parent struct {
	// The parent's LEI.
	Lei string `json:"lei"`
	// Its legal name.
	Name *string `json:"name"`
}

// NotRead: A source not read.
type NotRead struct {
	// The source.
	Source string `json:"source"`
	// Why.
	Reason string `json:"reason"`
}

// EvidenceClass: One class of evidence in the reading, kept apart from the others, with its own freshness rule and a line saying what it does not establish.
type EvidenceClass struct {
	// The class of evidence. Default stale-after days: regulator_filing 90, registry_record 365, sanctions_list 7, procurement_exclusion 7, domain_registration 30, dns_configuration 2, certificate_transparency 7, site_publication 30, patent_record 90, merger_review 30. Since trooth 0.14.0: domain_declaration 30 (a key the site publishes shows who controlled the site's content when Trooth read it; it does not establish the legal entity or a person's authority to act for it), trooth_claim_record 365 (domain control at claim time; it does not establish that the person may act for the legal entity). One of: regulator_filing, registry_record, sanctions_list, procurement_exclusion, domain_registration, dns_configuration, certificate_transparency, site_publication, patent_record, merger_review, domain_declaration, trooth_claim_record.
	Class string `json:"class"`
	// The sections of this record that hold this class of evidence.
	Sections []string `json:"sections"`
	// After this many days from observed_at a reader should take the evidence as stale and read again.
	StaleAfterDays int64 `json:"stale_after_days"`
	// What this class of evidence does not show, in one sentence.
	DoesNotEstablish string `json:"does_not_establish"`
	// Whether this reading read any of the sections.
	Read bool `json:"read"`
	// When the evidence was observed: the reading's read_at, or the source's own earlier read time when a cached answer was used. Null when not read.
	ObservedAt *string `json:"observed_at"`
	// observed_at plus stale_after_days, as an ISO 8601 time. Null when not read.
	StaleAfter *string `json:"stale_after"`
}

// ContinuityEvent: One difference between this reading and the previous reading of the same domain.
type ContinuityEvent struct {
	// What differs. entity_changed: the domain now ties to a different legal entity. entity_appeared: it now ties to one and did not before. entity_disappeared: it tied to one and now ties to none. renamed: the same entity under a new name. parent_changed: the LEI record names a different direct or ultimate parent. registrar_changed: RDAP names a different registrar. domain_transferred: RDAP records a transfer after the previous reading. unchanged: none of these. Since trooth 0.14.0: declaration_appeared: a declaration that checks is published and the previous reading had none. declaration_key_changed: the declaration's keys differ from the previous reading's. declaration_disappeared: the previous reading had a declaration that checked and this one does not. One of: entity_changed, entity_appeared, entity_disappeared, renamed, parent_changed, registrar_changed, domain_transferred, unchanged, declaration_appeared, declaration_key_changed, declaration_disappeared.
	Kind string `json:"kind"`
	// The difference in words, naming both readings' values.
	Detail string `json:"detail"`
}

// ContinuityPrevious: The previous cached reading of the same domain this reading was compared with.
type ContinuityPrevious struct {
	// When the previous reading was taken.
	ReadAt string `json:"read_at"`
	// Lowercase hex SHA-256 of the previous record as it was cached.
	RecordSha256 string `json:"record_sha256"`
}

// Continuity: This reading compared with the previous cached reading of the same domain. A changed entity is never merged: the new reading carries only what it read now, and the event names both.
type Continuity struct {
	// The previous reading compared with; null when there is none.
	Previous *ContinuityPrevious `json:"previous"`
	// What differs; empty when there is no previous reading, and a single unchanged event when nothing listed differs.
	Events []ContinuityEvent `json:"events"`
}

// Proof: One proof binding two subjects.
type Proof struct {
	// <proof kind>:<n>, unique in the reading.
	ID string `json:"id"`
	// The two subject ids the proof binds, the domain first.
	Binds []string `json:"binds"`
	// How the binding was shown (the same values as bindings[].proof_method). One of: regulator_filing, registry_record, site_statement, registry_name_match, asked, none, dns_txt, domain_signed_declaration, identity_provider_sign_in, domain_email_code, repository_control.
	ProofMethod string `json:"proof_method"`
	// confirmed: the proof holds as read. claimed: asserted, and nothing read confirms it. not_found: looked for and not there. not_read: the source could not be read (a 403 or 404 from a code host is not read, never absent). One of: confirmed, claimed, not_found, not_read.
	Status string `json:"status"`
	// What was read, in words.
	Detail string `json:"detail"`
	// The URL read, or "trooth record" for Trooth's own record of the claim.
	Source string `json:"source"`
	// When the proof was observed: the reading's read_at, or for Trooth's record of the claim, when the claim was confirmed. Null when not read.
	ObservedAt *string `json:"observed_at"`
}

// DeclarationReading: The domain-signed declaration as this reading found it.
type DeclarationReading struct {
	// https://<domain>/.well-known/trooth.json.
	URL string `json:"url"`
	// checked: every rule in docs/DECLARATION.md holds. invalid: a rule fails (reason says which). expired: it checks but expires_at has passed. absent: the site answers 404 or 410. not_read: the site could not be read. One of: checked, invalid, expired, absent, not_read.
	Status string `json:"status"`
	// Why, in words.
	Reason *string `json:"reason"`
	// Lowercase hex SHA-256 of the bytes served; null when nothing was read.
	Sha256 *string `json:"sha256"`
	// The declaration's issued_at.
	IssuedAt *string `json:"issued_at"`
	// The declaration's expires_at.
	ExpiresAt *string `json:"expires_at"`
	// The kids of the keys it publishes (<domain>#<thumbprint>).
	Keys []string `json:"keys"`
	// Whether the TXT record at _trooth-key.<domain> names one of the keys.
	KeyPinnedByDns bool `json:"key_pinned_by_dns"`
	// The products it names, when it checks; empty otherwise.
	Products []DeclaredProduct `json:"products"`
	// The APIs it names, when it checks; empty otherwise.
	Apis []DeclaredApi `json:"apis"`
	// The repositories it names, when it checks; empty otherwise.
	Repositories []string `json:"repositories"`
}

// VerificationBundle: Everything needed to check one witness statement with no network: the statement, its evidence manifest, the key list as read, and the exact mapping bytes. Written by `trooth verify --save-bundle`; read by `trooth verify --bundle` and the SDKs. A bundle is only as fresh as its key list.
type VerificationBundle struct {
	// The bundle format. One of: trooth.verification-bundle.v1.
	Bundle string `json:"bundle"`
	// When the bundle was written. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	CreatedAt string `json:"created_at"`
	// The domain the bundle was saved for. A reader may ask about another; a statement for a different domain is a mismatch.
	Domain *string `json:"domain"`
	// The signed envelope, exactly as published.
	Statement WitnessStatement `json:"statement"`
	// The evidence manifest, or null when none was saved.
	Manifest *EvidenceManifest `json:"manifest"`
	// The key list as read when the bundle was written.
	Keys BundleKeys `json:"keys"`
	// The exact mapping bytes, or null when none were saved.
	Mapping *BundleMapping `json:"mapping"`
	// What the witness statement log answered when the bundle was written: the log key used, the receipt or null, and every correction. Absent in a bundle written before the log, or when the log was not read.
	Log *BundleLog `json:"log,omitempty"`
}

// BundleLog: The log answer, carried so the log part can be checked offline too.
type BundleLog struct {
	// The log verifier key the receipt was checked against, as a signed-note key (name+hash+key). A pinned key, when the checker has one, replaces it.
	Vkey string `json:"vkey"`
	// The receipt for the statement, or null when the log held no entry for it.
	Receipt *LogReceipt `json:"receipt"`
	// Every logged correction naming this statement, each with its own receipt.
	Corrections []LoggedCorrection `json:"corrections"`
}

// LoggedCorrection: A correction envelope and its receipt.
type LoggedCorrection struct {
	// The correction envelope: its payload is a trooth.correction.v1 document in RFC 8785 bytes.
	Statement WitnessStatement `json:"statement"`
	// The receipt for the correction.
	Receipt LogReceipt `json:"receipt"`
}

// BundleKeys: The key list as read.
type BundleKeys struct {
	// The keys array of the key list.
	Keys []PublicKey `json:"keys"`
	// When the key list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ListReadAt *string `json:"list_read_at"`
	// Where it was read from: a URL or a file path.
	Source *string `json:"source"`
}

// BundleMapping: The mapping document, byte for byte.
type BundleMapping struct {
	// Where the bytes were read from.
	URL *string `json:"url"`
	// The digest of the carried bytes, for display. A checker hashes the bytes itself and compares with the signed digest.
	Digest string `json:"digest"`
	// The exact mapping bytes, standard base64.
	BytesBase64 string `json:"bytes_base64"`
}

// VerifyResult: The JSON document `trooth verify --json` writes, and the shape the SDKs return. The verdict is the only conclusion; everything else says how it was reached.
type VerifyResult struct {
	// The domain asked about, or the signed domain when none was asked.
	Domain *string `json:"domain"`
	// checked: v2 or v3, everything bound and matching. checked_v1: a v1 statement that checks. partially_checked: a mapping or manifest was not supplied. signature_not_trusted: malformed, invalid or untrusted key. mismatch: trusted, but a count, the domain, the mapping, the manifest or a log receipt disagrees. superseded: everything held, and a correction Trooth signed and logged withdraws or replaces the statement. One of: checked, checked_v1, partially_checked, signature_not_trusted, mismatch, superseded.
	Verdict string `json:"verdict"`
	// The statement version, or unknown. One of: v1, v2, v3, unknown.
	Version string `json:"version"`
	// The read_at the payload carries. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt *string `json:"read_at,omitempty"`
	// The reading id the payload carries.
	ReadingID *string `json:"reading_id,omitempty"`
	// trooth:statement: plus the hex SHA-256 of the exact payload bytes (docs/IDS.md).
	StatementID *string `json:"statement_id,omitempty"`
	// valid, invalid or malformed. One of: valid, invalid, malformed.
	Signature string `json:"signature"`
	// The signing key and whether it is trusted at read_at.
	Key KeyTrust `json:"key"`
	// The signed domain against the domain asked about.
	Subject Subject `json:"subject"`
	// The mapping and manifest against their signed digests.
	Binding Binding `json:"binding"`
	// Whether the signed counts agree with the signed checks.
	Counts CountCheck `json:"counts"`
	// The witness statement log part of the check. Absent when the log was not asked (offline from saved files, --no-log) or the signature was not trusted.
	Log *LogCheck `json:"log,omitempty"`
	// What a valid signature of this version shows and does not show, in words.
	Assurance string `json:"assurance"`
	// When the key list used was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	KeysReadAt *string `json:"keys_read_at,omitempty"`
	// Where each input came from: a URL, a file path, or null when not supplied.
	Sources map[string]*string `json:"sources,omitempty"`
}

// KeyTrust: The key decision.
type KeyTrust struct {
	// The key id the envelope names.
	Kid string `json:"kid"`
	// The lifecycle state found on the key list. One of: active, retired, compromised, revoked_unrecorded, unknown.
	State string `json:"state"`
	// Whether a valid signature from this key at this time is relied on.
	Trusted bool `json:"trusted"`
	// Why, in words.
	Reason string `json:"reason"`
}

// Subject: The subject decision.
type Subject struct {
	// The domain in the signed payload.
	Signed *string `json:"signed"`
	// The domain asked about.
	Asked *string `json:"asked"`
	// match, mismatch, or not_checked (no domain given, or the signature was not trusted). One of: match, mismatch, not_checked.
	Status string `json:"status"`
}

// Binding: The binding decision.
type Binding struct {
	// bound, partially_checked, mismatch, absent (v1 binds neither) or unchecked (signature not trusted). One of: bound, partially_checked, mismatch, absent, unchecked.
	Status string `json:"status"`
	// The mapping result. One of: match, mismatch, not_supplied, absent.
	Mapping string `json:"mapping"`
	// The manifest result. One of: match, mismatch, not_supplied, absent.
	Manifest string `json:"manifest"`
}

// LogCheck: What the log showed about the statement.
type LogCheck struct {
	// included: the receipt checks against a checkpoint signed by the log key. not_logged: the log holds no entry for it (reported, not a failure in this version). unavailable: the log could not be read. checkpoint_invalid: the checkpoint is not signed by the log key or names another log. proof_invalid: the receipt does not take this statement to the signed root. One of: included, not_logged, unavailable, checkpoint_invalid, proof_invalid.
	Status string `json:"status"`
	// The entry index the receipt names, or null.
	Index *int64 `json:"index"`
	// The signed tree size the receipt is against, or null.
	TreeSize *int64 `json:"tree_size"`
	// Why, in words.
	Reason *string `json:"reason"`
	// Each correction the log returned and whether it checked.
	Corrections []CorrectionCheck `json:"corrections"`
	// The statement id of the first correction that checked, or null.
	SupersededBy *string `json:"superseded_by"`
	// Where the log key came from: pinned in this release, --log-vkey, carried in a bundle, or served by the log.
	VkeySource *string `json:"vkey_source,omitempty"`
}

// CorrectionCheck: One correction and whether it is relied on.
type CorrectionCheck struct {
	// True when it is signed by a trusted key, in RFC 8785 bytes, names this statement, and is included in the log.
	Valid bool `json:"valid"`
	// The statement id of the correction itself.
	CorrectionStatementID *string `json:"correction_statement_id"`
	// The reason code it carries.
	Code *string `json:"code"`
	// withdrawn or replaced.
	Effect *string `json:"effect"`
	// The replacing statement id, for replaced.
	Replacement *string `json:"replacement"`
	// When Trooth issued it, as Trooth asserts. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	IssuedAt *string `json:"issued_at"`
	// Why it is or is not relied on, in words.
	Reason *string `json:"reason"`
}

// CountCheck: The count decision.
type CountCheck struct {
	// True when every identity holds.
	IdentitiesHold bool `json:"identities_hold"`
	// Each identity that does not hold, in words.
	Problems []string `json:"problems"`
}

// WitnessPayloadV1: The JSON a trooth.witness-statement.v1 payload holds. v1 binds the outcomes and counts only: no mapping, manifest, evaluator or subject scope.
type WitnessPayloadV1 struct {
	// The statement version. One of: trooth.witness-statement.v1.
	Statement string `json:"statement"`
	// The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).
	ReadingID string `json:"reading_id"`
	// The domain the reading was taken of: lowercase, no trailing dot.
	Domain string `json:"domain"`
	// When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// Every check in the reading.
	Checks []CheckV1 `json:"checks"`
	// The two counts, which must agree with the checks.
	Counts CountsV1 `json:"counts"`
}

// CheckV1: One check in a v1 reading. v1 carries no reason.
type CheckV1 struct {
	// The check id.
	ID string `json:"id"`
	// The check category.
	Category string `json:"category"`
	// probe or attest.
	Kind string `json:"kind"`
	// One of three outcomes. One of: as expected, not as expected, not read.
	Outcome string `json:"outcome"`
}

// CountsV1: The two counts a v1 payload carries.
type CountsV1 struct {
	// Checks whose outcome is not `not read`.
	Read int64 `json:"read"`
	// Checks whose outcome is `as expected`.
	AsExpected int64 `json:"as_expected"`
}

// WitnessPayloadV2: The JSON a trooth.witness-statement.v2 payload holds. Its members are signed in exactly this order with no whitespace. It binds the check mapping, the evaluator, the subject scope and the evidence manifest.
type WitnessPayloadV2 struct {
	// The statement version. One of: trooth.witness-statement.v2.
	Statement string `json:"statement"`
	// The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).
	ReadingID string `json:"reading_id"`
	// The domain the reading was taken of: lowercase, no trailing dot.
	Domain string `json:"domain"`
	// When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// What the reading covered.
	SubjectScope SubjectScope `json:"subject_scope"`
	// The check mapping, bound by digest.
	Methodology Methodology `json:"methodology"`
	// The software that took the reading.
	Evaluator Evaluator `json:"evaluator"`
	// The evidence manifest, bound by digest.
	EvidenceManifest EvidenceManifestRef `json:"evidence_manifest"`
	// Every check in the reading.
	Checks []Check `json:"checks"`
	// Counts that must agree with the checks.
	Counts Counts `json:"counts"`
}

// Check: One check in the reading and its outcome.
type Check struct {
	// The check id in the check mapping the payload names (for example S1, L2).
	ID string `json:"id"`
	// The check category in the mapping (for example security, legal, ai, ip, business).
	Category string `json:"category"`
	// How the check is taken: `probe` reads the public surface; `attest` reads something the company published about itself.
	Kind string `json:"kind"`
	// One of three outcomes. There is no fourth value and no score. One of: as expected, not as expected, not read.
	Outcome string `json:"outcome"`
	// Null when the outcome is `as expected`; otherwise why.
	Reason *CheckReason `json:"reason"`
}

// CheckReason: Why a check is not `as expected`. Present on every check whose outcome is `not read` or `not as expected`.
type CheckReason struct {
	// The reason code. source_unavailable, timeout, evaluator_limitation, carried_from_earlier_reading and check_misconfigured go with `not read`; contrary_observation and expected_item_absent go with `not as expected`. One of: source_unavailable, timeout, evaluator_limitation, carried_from_earlier_reading, check_misconfigured, contrary_observation, expected_item_absent.
	Code string `json:"code"`
	// The version of the reason vocabulary. One of: trooth.check-explanations.v1.
	Version string `json:"version"`
	// The public source the reason refers to, or null. Always null when `withheld` is true.
	SourceRef *string `json:"source_ref"`
	// True when the source behind this reason is not published (for example a private document); only a commitment to it is in the evidence manifest.
	Withheld bool `json:"withheld"`
	// Why the source is withheld. Required, non-empty, when `withheld` is true; otherwise null.
	WithheldReason *string `json:"withheld_reason"`
}

// Counts: Counts that MUST agree with the checks: read + not_read = in_reading; as_expected + not_as_expected = read; in_reading = the number of checks. They are reported apart and never added into one number.
type Counts struct {
	// Checks whose outcome is not `not read`.
	Read int64 `json:"read"`
	// Checks whose outcome is `as expected`.
	AsExpected int64 `json:"as_expected"`
	// Checks whose outcome is `not as expected`.
	NotAsExpected int64 `json:"not_as_expected"`
	// Checks whose outcome is `not read`.
	NotRead int64 `json:"not_read"`
	// All checks in the reading.
	InReading int64 `json:"in_reading"`
}

// SubjectScope: What the reading covered.
type SubjectScope struct {
	// The domain read. Equals the payload domain.
	Domain string `json:"domain"`
	// Which surface was read. `public`: only what anyone can fetch.
	Surface string `json:"surface"`
	// The number of checks in scope. Equals the number of checks listed.
	ChecksInScope int64 `json:"checks_in_scope"`
}

// Methodology: The exact check mapping the reading used, bound by digest.
type Methodology struct {
	// The name of the standard the mapping belongs to.
	Standard string `json:"standard"`
	// The mapping version.
	MappingVersion string `json:"mapping_version"`
	// Where the exact mapping bytes are served. Immutable versions live under https://trooth.co/standard/check-mapping/.
	MappingURL string `json:"mapping_url"`
	// `sha256:` plus the lowercase hex SHA-256 of the exact mapping bytes.
	MappingDigest string `json:"mapping_digest"`
}

// Evaluator: The software that took the reading.
type Evaluator struct {
	// The evaluator name.
	Name string `json:"name"`
	// The evaluator version.
	Version string `json:"version"`
}

// EvidenceManifestRef: The evidence manifest the reading binds, by digest.
type EvidenceManifestRef struct {
	// `sha256:` plus the hex SHA-256 of the canonical manifest bytes (evidence-manifest.schema.json).
	Digest string `json:"digest"`
	// The number of manifest entries.
	Entries int64 `json:"entries"`
	// How the manifest bytes are formed: entries sorted by check_id, keys check_id then source or commitment, no whitespace, UTF-8.
	Canonicalization string `json:"canonicalization"`
}

// WitnessPayloadV3: The JSON a trooth.witness-statement.v3 payload holds: the v2 content plus subject_id and signer, serialized as RFC 8785 (JCS). Every number is an integer between -(2^53 - 1) and 2^53 - 1, so every implementation produces the same bytes.
type WitnessPayloadV3 struct {
	// Every check in the reading.
	Checks []Check `json:"checks"`
	// Counts that must agree with the checks.
	Counts Counts `json:"counts"`
	// The domain the reading was taken of: lowercase, no trailing dot.
	Domain string `json:"domain"`
	// The software that took the reading.
	Evaluator Evaluator `json:"evaluator"`
	// The evidence manifest, bound by digest.
	EvidenceManifest EvidenceManifestRef `json:"evidence_manifest"`
	// The check mapping, bound by digest.
	Methodology Methodology `json:"methodology"`
	// When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).
	ReadingID string `json:"reading_id"`
	// The signing key, inside the signed bytes.
	Signer Signer `json:"signer"`
	// The statement version. One of: trooth.witness-statement.v3.
	Statement string `json:"statement"`
	// The subject by its stable id, trooth:domain:<domain> (docs/IDS.md). MUST name the payload domain.
	SubjectID string `json:"subject_id"`
	// What the reading covered.
	SubjectScope SubjectScope `json:"subject_scope"`
}

// Signer: The signing key, named inside the signed bytes so the envelope cannot point at another key.
type Signer struct {
	// The kid of the signing key. MUST equal the envelope key_id.
	KeyID string `json:"key_id"`
	// Who signs: trooth.co. One of: trooth.co.
	Issuer string `json:"issuer"`
}

// WitnessStatement: The signed envelope Trooth publishes as `witnessStatement` on a record. The signature covers the exact UTF-8 bytes of `payload`, nothing else. How to check it: docs/VERIFY.md in github.com/troothllc/trooth-cli.
type WitnessStatement struct {
	// The signing input: the exact JSON text that was signed. Parse it to read it; never re-serialize it to check it. Its `statement` field names the version (witness-payload.v1, v2 or v3).
	Payload string `json:"payload"`
	// The Ed25519 signature over the payload bytes: `ed25519:` followed by standard base64 of the 64 signature bytes.
	Signature string `json:"signature"`
	// The `kid` of the signing key on https://api.trooth.co/public/keys. A v3 payload names the same key inside the signed bytes, at signer.key_id.
	KeyID string `json:"key_id"`
	// The signature algorithm. Always Ed25519 (RFC 8032, pure EdDSA). One of: Ed25519.
	Alg string `json:"alg"`
	// How the payload bytes were produced. `json-fixed-key-order-no-whitespace-utf8` for v1 and v2; `RFC8785` (JSON Canonicalization Scheme, integers only) for v3, where the payload MUST equal the canonical form of the JSON it holds. One of: json-fixed-key-order-no-whitespace-utf8, RFC8785.
	Canonicalization string `json:"canonicalization"`
}
