// GENERATED by scripts/gen-types.mjs from schemas/ in github.com/troothllc/trooth-cli.
// Do not edit by hand: change the schema and run `node scripts/gen-types.mjs`.

package trooth

// EvidenceManifest: The evidence manifest a v2 or v3 statement binds by digest, published beside the statement as `witnessEvidenceManifest`. Canonical bytes: entries sorted by check_id, each as {"check_id":..,"source":..} or {"check_id":..,"commitment":..}, no whitespace, UTF-8.
type EvidenceManifest []ManifestEntry

// ManifestEntry: One check and the evidence behind it: a public `source`, or a `commitment` to a private one. Exactly one of the two.
type ManifestEntry struct {
	// The check id. Unique in the manifest.
	CheckID string `json:"check_id"`
	// The public URL the check read.
	Source *string `json:"source,omitempty"`
	// `sha256:` plus the hex SHA-256 of salt, a newline byte and the private reference. Only its holder can open it.
	Commitment *string `json:"commitment,omitempty"`
}

// KeyList: The body of https://api.trooth.co/public/keys, or a saved copy of it. Save it with the time you read it: a saved list cannot show a compromise announced later.
type KeyList struct {
	// Every key, current and past.
	Keys []PublicKey `json:"keys"`
	// When the list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ListReadAt *string `json:"list_read_at,omitempty"`
	// The kid of the key currently used for new statements.
	ActiveKid *string `json:"active_kid,omitempty"`
	// A note from the key service.
	Note *string `json:"note,omitempty"`
}

// PublicKey: One published key and its lifecycle. Only `kid`, `alg`, `encoding`, `public_key`, `status` and the three lifecycle times decide trust (docs/VERIFY.md section 3).
type PublicKey struct {
	// The key id a statement names in key_id.
	Kid string `json:"kid"`
	// Always Ed25519. One of: Ed25519.
	Alg string `json:"alg"`
	// How public_key is written: hex or base64. One of: hex, base64.
	Encoding *string `json:"encoding,omitempty"`
	// The 32-byte Ed25519 public key, in `encoding`.
	PublicKey string `json:"public_key"`
	// active, retired, revoked or compromised. One of: active, retired, revoked, compromised.
	Status string `json:"status"`
	// The same lifecycle state as written by the key service.
	State *string `json:"state,omitempty"`
	// When the key was retired. Statements carrying a read_at strictly before this stay trusted. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	RetiredAt *string `json:"retired_at,omitempty"`
	// When the key was found compromised. Nothing signed by it is relied on. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	CompromisedAt *string `json:"compromised_at,omitempty"`
	// When the key was revoked. A revocation with no compromise recorded is treated as a compromise. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	RevokedAt *string `json:"revoked_at,omitempty"`
	// When the key was created, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	CreatedAt *string `json:"created_at,omitempty"`
	// When the key was first used, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ActivatedAt *string `json:"activated_at,omitempty"`
	// When the key first appeared on the list. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	FirstListedAt *string `json:"first_listed_at,omitempty"`
	// A short fingerprint of the key, for display.
	Fingerprint *string `json:"fingerprint,omitempty"`
	// What the key is for, as a short label.
	Purpose *string `json:"purpose,omitempty"`
	// What the key signs, in words.
	Signs *string `json:"signs,omitempty"`
	// Lifecycle events, oldest first.
	Events []KeyEvent `json:"events,omitempty"`
}

// KeyEvent: One lifecycle event of a key.
type KeyEvent struct {
	// What happened (for example first_listed, retired, compromised).
	Event string `json:"event"`
	// When. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	At string `json:"at"`
	// A note, or null.
	Note *string `json:"note,omitempty"`
}

// VerificationBundle: Everything needed to check one witness statement with no network: the statement, its evidence manifest, the key list as read, and the exact mapping bytes. Written by `trooth verify --save-bundle`; read by `trooth verify --bundle` and the SDKs. A bundle is only as fresh as its key list.
type VerificationBundle struct {
	// The bundle format. One of: trooth.verification-bundle.v1.
	Bundle string `json:"bundle"`
	// When the bundle was written. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	CreatedAt string `json:"created_at"`
	// The domain the bundle was saved for. A reader may ask about another; a statement for a different domain is a mismatch.
	Domain *string `json:"domain"`
	// The signed envelope, exactly as published.
	Statement WitnessStatement `json:"statement"`
	// The evidence manifest, or null when none was saved.
	Manifest *EvidenceManifest `json:"manifest"`
	// The key list as read when the bundle was written.
	Keys BundleKeys `json:"keys"`
	// The exact mapping bytes, or null when none were saved.
	Mapping *BundleMapping `json:"mapping"`
}

// BundleKeys: The key list as read.
type BundleKeys struct {
	// The keys array of the key list.
	Keys []PublicKey `json:"keys"`
	// When the key list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ListReadAt *string `json:"list_read_at"`
	// Where it was read from: a URL or a file path.
	Source *string `json:"source"`
}

// BundleMapping: The mapping document, byte for byte.
type BundleMapping struct {
	// Where the bytes were read from.
	URL *string `json:"url"`
	// The digest of the carried bytes, for display. A checker hashes the bytes itself and compares with the signed digest.
	Digest string `json:"digest"`
	// The exact mapping bytes, standard base64.
	BytesBase64 string `json:"bytes_base64"`
}

// VerifyResult: The JSON document `trooth verify --json` writes, and the shape the SDKs return. The verdict is the only conclusion; everything else says how it was reached.
type VerifyResult struct {
	// The domain asked about, or the signed domain when none was asked.
	Domain *string `json:"domain"`
	// checked: v2 or v3, everything bound and matching. checked_v1: a v1 statement that checks. partially_checked: a mapping or manifest was not supplied. signature_not_trusted: malformed, invalid or untrusted key. mismatch: trusted, but a count, the domain, the mapping or the manifest disagrees. One of: checked, checked_v1, partially_checked, signature_not_trusted, mismatch.
	Verdict string `json:"verdict"`
	// The statement version, or unknown. One of: v1, v2, v3, unknown.
	Version string `json:"version"`
	// The read_at the payload carries. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt *string `json:"read_at,omitempty"`
	// The reading id the payload carries.
	ReadingID *string `json:"reading_id,omitempty"`
	// trooth:statement: plus the hex SHA-256 of the exact payload bytes (docs/IDS.md).
	StatementID *string `json:"statement_id,omitempty"`
	// valid, invalid or malformed. One of: valid, invalid, malformed.
	Signature string `json:"signature"`
	// The signing key and whether it is trusted at read_at.
	Key KeyTrust `json:"key"`
	// The signed domain against the domain asked about.
	Subject Subject `json:"subject"`
	// The mapping and manifest against their signed digests.
	Binding Binding `json:"binding"`
	// Whether the signed counts agree with the signed checks.
	Counts CountCheck `json:"counts"`
	// What a valid signature of this version shows and does not show, in words.
	Assurance string `json:"assurance"`
	// When the key list used was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	KeysReadAt *string `json:"keys_read_at,omitempty"`
	// Where each input came from: a URL, a file path, or null when not supplied.
	Sources map[string]*string `json:"sources,omitempty"`
}

// KeyTrust: The key decision.
type KeyTrust struct {
	// The key id the envelope names.
	Kid string `json:"kid"`
	// The lifecycle state found on the key list. One of: active, retired, compromised, revoked_unrecorded, unknown.
	State string `json:"state"`
	// Whether a valid signature from this key at this time is relied on.
	Trusted bool `json:"trusted"`
	// Why, in words.
	Reason string `json:"reason"`
}

// Subject: The subject decision.
type Subject struct {
	// The domain in the signed payload.
	Signed *string `json:"signed"`
	// The domain asked about.
	Asked *string `json:"asked"`
	// match, mismatch, or not_checked (no domain given, or the signature was not trusted). One of: match, mismatch, not_checked.
	Status string `json:"status"`
}

// Binding: The binding decision.
type Binding struct {
	// bound, partially_checked, mismatch, absent (v1 binds neither) or unchecked (signature not trusted). One of: bound, partially_checked, mismatch, absent, unchecked.
	Status string `json:"status"`
	// The mapping result. One of: match, mismatch, not_supplied, absent.
	Mapping string `json:"mapping"`
	// The manifest result. One of: match, mismatch, not_supplied, absent.
	Manifest string `json:"manifest"`
}

// CountCheck: The count decision.
type CountCheck struct {
	// True when every identity holds.
	IdentitiesHold bool `json:"identities_hold"`
	// Each identity that does not hold, in words.
	Problems []string `json:"problems"`
}

// WitnessPayloadV1: The JSON a trooth.witness-statement.v1 payload holds. v1 binds the outcomes and counts only: no mapping, manifest, evaluator or subject scope.
type WitnessPayloadV1 struct {
	// The statement version. One of: trooth.witness-statement.v1.
	Statement string `json:"statement"`
	// The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).
	ReadingID string `json:"reading_id"`
	// The domain the reading was taken of: lowercase, no trailing dot.
	Domain string `json:"domain"`
	// When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// Every check in the reading.
	Checks []CheckV1 `json:"checks"`
	// The two counts, which must agree with the checks.
	Counts CountsV1 `json:"counts"`
}

// CheckV1: One check in a v1 reading. v1 carries no reason.
type CheckV1 struct {
	// The check id.
	ID string `json:"id"`
	// The check category.
	Category string `json:"category"`
	// probe or attest.
	Kind string `json:"kind"`
	// One of three outcomes. One of: as expected, not as expected, not read.
	Outcome string `json:"outcome"`
}

// CountsV1: The two counts a v1 payload carries.
type CountsV1 struct {
	// Checks whose outcome is not `not read`.
	Read int64 `json:"read"`
	// Checks whose outcome is `as expected`.
	AsExpected int64 `json:"as_expected"`
}

// WitnessPayloadV2: The JSON a trooth.witness-statement.v2 payload holds. Its members are signed in exactly this order with no whitespace. It binds the check mapping, the evaluator, the subject scope and the evidence manifest.
type WitnessPayloadV2 struct {
	// The statement version. One of: trooth.witness-statement.v2.
	Statement string `json:"statement"`
	// The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).
	ReadingID string `json:"reading_id"`
	// The domain the reading was taken of: lowercase, no trailing dot.
	Domain string `json:"domain"`
	// When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// What the reading covered.
	SubjectScope SubjectScope `json:"subject_scope"`
	// The check mapping, bound by digest.
	Methodology Methodology `json:"methodology"`
	// The software that took the reading.
	Evaluator Evaluator `json:"evaluator"`
	// The evidence manifest, bound by digest.
	EvidenceManifest EvidenceManifestRef `json:"evidence_manifest"`
	// Every check in the reading.
	Checks []Check `json:"checks"`
	// Counts that must agree with the checks.
	Counts Counts `json:"counts"`
}

// Check: One check in the reading and its outcome.
type Check struct {
	// The check id in the check mapping the payload names (for example S1, L2).
	ID string `json:"id"`
	// The check category in the mapping (for example security, legal, ai, ip, business).
	Category string `json:"category"`
	// How the check is taken: `probe` reads the public surface; `attest` reads something the company published about itself.
	Kind string `json:"kind"`
	// One of three outcomes. There is no fourth value and no score. One of: as expected, not as expected, not read.
	Outcome string `json:"outcome"`
	// Null when the outcome is `as expected`; otherwise why.
	Reason *CheckReason `json:"reason"`
}

// CheckReason: Why a check is not `as expected`. Present on every check whose outcome is `not read` or `not as expected`.
type CheckReason struct {
	// The reason code. source_unavailable, timeout, evaluator_limitation, carried_from_earlier_reading and check_misconfigured go with `not read`; contrary_observation and expected_item_absent go with `not as expected`. One of: source_unavailable, timeout, evaluator_limitation, carried_from_earlier_reading, check_misconfigured, contrary_observation, expected_item_absent.
	Code string `json:"code"`
	// The version of the reason vocabulary. One of: trooth.check-explanations.v1.
	Version string `json:"version"`
	// The public source the reason refers to, or null. Always null when `withheld` is true.
	SourceRef *string `json:"source_ref"`
	// True when the source behind this reason is not published (for example a private document); only a commitment to it is in the evidence manifest.
	Withheld bool `json:"withheld"`
	// Why the source is withheld. Required, non-empty, when `withheld` is true; otherwise null.
	WithheldReason *string `json:"withheld_reason"`
}

// Counts: Counts that MUST agree with the checks: read + not_read = in_reading; as_expected + not_as_expected = read; in_reading = the number of checks. They are reported apart and never added into one number.
type Counts struct {
	// Checks whose outcome is not `not read`.
	Read int64 `json:"read"`
	// Checks whose outcome is `as expected`.
	AsExpected int64 `json:"as_expected"`
	// Checks whose outcome is `not as expected`.
	NotAsExpected int64 `json:"not_as_expected"`
	// Checks whose outcome is `not read`.
	NotRead int64 `json:"not_read"`
	// All checks in the reading.
	InReading int64 `json:"in_reading"`
}

// SubjectScope: What the reading covered.
type SubjectScope struct {
	// The domain read. Equals the payload domain.
	Domain string `json:"domain"`
	// Which surface was read. `public`: only what anyone can fetch.
	Surface string `json:"surface"`
	// The number of checks in scope. Equals the number of checks listed.
	ChecksInScope int64 `json:"checks_in_scope"`
}

// Methodology: The exact check mapping the reading used, bound by digest.
type Methodology struct {
	// The name of the standard the mapping belongs to.
	Standard string `json:"standard"`
	// The mapping version.
	MappingVersion string `json:"mapping_version"`
	// Where the exact mapping bytes are served. Immutable versions live under https://trooth.co/standard/check-mapping/.
	MappingURL string `json:"mapping_url"`
	// `sha256:` plus the lowercase hex SHA-256 of the exact mapping bytes.
	MappingDigest string `json:"mapping_digest"`
}

// Evaluator: The software that took the reading.
type Evaluator struct {
	// The evaluator name.
	Name string `json:"name"`
	// The evaluator version.
	Version string `json:"version"`
}

// EvidenceManifestRef: The evidence manifest the reading binds, by digest.
type EvidenceManifestRef struct {
	// `sha256:` plus the hex SHA-256 of the canonical manifest bytes (evidence-manifest.schema.json).
	Digest string `json:"digest"`
	// The number of manifest entries.
	Entries int64 `json:"entries"`
	// How the manifest bytes are formed: entries sorted by check_id, keys check_id then source or commitment, no whitespace, UTF-8.
	Canonicalization string `json:"canonicalization"`
}

// WitnessPayloadV3: The JSON a trooth.witness-statement.v3 payload holds: the v2 content plus subject_id and signer, serialized as RFC 8785 (JCS). Every number is an integer between -(2^53 - 1) and 2^53 - 1, so every implementation produces the same bytes.
type WitnessPayloadV3 struct {
	// Every check in the reading.
	Checks []Check `json:"checks"`
	// Counts that must agree with the checks.
	Counts Counts `json:"counts"`
	// The domain the reading was taken of: lowercase, no trailing dot.
	Domain string `json:"domain"`
	// The software that took the reading.
	Evaluator Evaluator `json:"evaluator"`
	// The evidence manifest, bound by digest.
	EvidenceManifest EvidenceManifestRef `json:"evidence_manifest"`
	// The check mapping, bound by digest.
	Methodology Methodology `json:"methodology"`
	// When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).
	ReadingID string `json:"reading_id"`
	// The signing key, inside the signed bytes.
	Signer Signer `json:"signer"`
	// The statement version. One of: trooth.witness-statement.v3.
	Statement string `json:"statement"`
	// The subject by its stable id, trooth:domain:<domain> (docs/IDS.md). MUST name the payload domain.
	SubjectID string `json:"subject_id"`
	// What the reading covered.
	SubjectScope SubjectScope `json:"subject_scope"`
}

// Signer: The signing key, named inside the signed bytes so the envelope cannot point at another key.
type Signer struct {
	// The kid of the signing key. MUST equal the envelope key_id.
	KeyID string `json:"key_id"`
	// Who signs: trooth.co. One of: trooth.co.
	Issuer string `json:"issuer"`
}

// WitnessStatement: The signed envelope Trooth publishes as `witnessStatement` on a record. The signature covers the exact UTF-8 bytes of `payload`, nothing else. How to check it: docs/VERIFY.md in github.com/troothllc/trooth-cli.
type WitnessStatement struct {
	// The signing input: the exact JSON text that was signed. Parse it to read it; never re-serialize it to check it. Its `statement` field names the version (witness-payload.v1, v2 or v3).
	Payload string `json:"payload"`
	// The Ed25519 signature over the payload bytes: `ed25519:` followed by standard base64 of the 64 signature bytes.
	Signature string `json:"signature"`
	// The `kid` of the signing key on https://api.trooth.co/public/keys. A v3 payload names the same key inside the signed bytes, at signer.key_id.
	KeyID string `json:"key_id"`
	// The signature algorithm. Always Ed25519 (RFC 8032, pure EdDSA). One of: Ed25519.
	Alg string `json:"alg"`
	// How the payload bytes were produced. `json-fixed-key-order-no-whitespace-utf8` for v1 and v2; `RFC8785` (JSON Canonicalization Scheme, integers only) for v3, where the payload MUST equal the canonical form of the JSON it holds. One of: json-fixed-key-order-no-whitespace-utf8, RFC8785.
	Canonicalization string `json:"canonicalization"`
}
