// GENERATED by scripts/gen-types.mjs from schemas/ in github.com/troothllc/trooth-cli.
// Do not edit by hand: change the schema and run `node scripts/gen-types.mjs`.

package trooth

// CorrectionPayload: The JSON a trooth.correction.v1 payload holds: Trooth withdrawing or replacing a statement it signed. Signed like a v3 statement (RFC 8785 bytes, Ed25519, the signer inside the signed bytes) and entered in the witness statement log. The statement it corrects stays in the log; nothing is deleted.
type CorrectionPayload struct {
	// The payload type. One of: trooth.correction.v1.
	Statement string `json:"statement"`
	// An identifier for this correction, unique in the log.
	CorrectionID string `json:"correction_id"`
	// The statement id this correction withdraws or replaces. It must already be in the log.
	Supersedes string `json:"supersedes"`
	// The subject of the statement it corrects.
	SubjectID string `json:"subject_id"`
	// withdrawn: no statement takes its place. replaced: the replacement statement does. One of: withdrawn, replaced.
	Effect string `json:"effect"`
	// The replacing statement id, which must already be in the log; null for withdrawn.
	Replacement *string `json:"replacement"`
	// Why.
	Reason CorrectionReason `json:"reason"`
	// When Trooth issued it, as Trooth asserts. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	IssuedAt string `json:"issued_at"`
	// The signing key, inside the signed bytes.
	Signer Signer `json:"signer"`
}

// CorrectionReason: The reason for a correction.
type CorrectionReason struct {
	// evaluator_defect: the evaluator read wrongly. mapping_defect: the check mapping was wrong. source_misread: a source was misread. signing_key_compromised: the key that signed it is compromised. dispute_upheld: a dispute about the reading was upheld. withdrawn_by_trooth: withdrawn for another stated reason. One of: evaluator_defect, mapping_defect, source_misread, signing_key_compromised, dispute_upheld, withdrawn_by_trooth.
	Code string `json:"code"`
	// The reason in words, 10 to 1000 characters.
	Explanation string `json:"explanation"`
}

// EvidenceManifest: The evidence manifest a v2 or v3 statement binds by digest, published beside the statement as `witnessEvidenceManifest`. Canonical bytes: entries sorted by check_id, each as {"check_id":..,"source":..} or {"check_id":..,"commitment":..}, no whitespace, UTF-8.
type EvidenceManifest []ManifestEntry

// ManifestEntry: One check and the evidence behind it: a public `source`, or a `commitment` to a private one. Exactly one of the two.
type ManifestEntry struct {
	// The check id. Unique in the manifest.
	CheckID string `json:"check_id"`
	// The public URL the check read.
	Source *string `json:"source,omitempty"`
	// `sha256:` plus the hex SHA-256 of salt, a newline byte and the private reference. Only its holder can open it.
	Commitment *string `json:"commitment,omitempty"`
}

// KeyList: The body of https://api.trooth.co/public/keys, or a saved copy of it. Save it with the time you read it: a saved list cannot show a compromise announced later.
type KeyList struct {
	// Every key, current and past.
	Keys []PublicKey `json:"keys"`
	// When the list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ListReadAt *string `json:"list_read_at,omitempty"`
	// The kid of the key currently used for new statements.
	ActiveKid *string `json:"active_kid,omitempty"`
	// A note from the key service.
	Note *string `json:"note,omitempty"`
}

// PublicKey: One published key and its lifecycle. Only `kid`, `alg`, `encoding`, `public_key`, `status` and the three lifecycle times decide trust (docs/VERIFY.md section 3).
type PublicKey struct {
	// The key id a statement names in key_id.
	Kid string `json:"kid"`
	// Always Ed25519. One of: Ed25519.
	Alg string `json:"alg"`
	// How public_key is written: hex or base64. One of: hex, base64.
	Encoding *string `json:"encoding,omitempty"`
	// The 32-byte Ed25519 public key, in `encoding`.
	PublicKey string `json:"public_key"`
	// active, retired, revoked or compromised. One of: active, retired, revoked, compromised.
	Status string `json:"status"`
	// The same lifecycle state as written by the key service.
	State *string `json:"state,omitempty"`
	// When the key was retired. Statements carrying a read_at strictly before this stay trusted. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	RetiredAt *string `json:"retired_at,omitempty"`
	// When the key was found compromised. Nothing signed by it is relied on. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	CompromisedAt *string `json:"compromised_at,omitempty"`
	// When the key was revoked. A revocation with no compromise recorded is treated as a compromise. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	RevokedAt *string `json:"revoked_at,omitempty"`
	// When the key was created, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	CreatedAt *string `json:"created_at,omitempty"`
	// When the key was first used, when recorded. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ActivatedAt *string `json:"activated_at,omitempty"`
	// When the key first appeared on the list. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	FirstListedAt *string `json:"first_listed_at,omitempty"`
	// A short fingerprint of the key, for display.
	Fingerprint *string `json:"fingerprint,omitempty"`
	// What the key is for, as a short label.
	Purpose *string `json:"purpose,omitempty"`
	// What the key signs, in words.
	Signs *string `json:"signs,omitempty"`
	// Lifecycle events, oldest first.
	Events []KeyEvent `json:"events,omitempty"`
}

// KeyEvent: One lifecycle event of a key.
type KeyEvent struct {
	// What happened (for example first_listed, retired, compromised).
	Event string `json:"event"`
	// When. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	At string `json:"at"`
	// A note, or null.
	Note *string `json:"note,omitempty"`
}

// LogReceipt: A receipt from Trooth's witness statement log (docs/LOG.md): the entry index, a checkpoint signed by the log key, and an RFC 9162 inclusion proof from the entry to the checkpoint root. The entry is RFC 8785 JSON of {kind, statement}; its leaf hash is SHA-256(0x00 || entry).
type LogReceipt struct {
	// The log origin, which the checkpoint must also name. One of: trooth.co/witness-log/v1.
	Log string `json:"log"`
	// The zero-based entry index.
	Index int64 `json:"index"`
	// The size of the signed tree the proof is against. Equals the checkpoint size.
	TreeSize int64 `json:"tree_size"`
	// Standard base64 of the 32-byte root at tree_size. Equals the checkpoint root.
	RootHash string `json:"root_hash"`
	// The RFC 9162 audit path, leaf to root, each a 32-byte hash in standard base64.
	InclusionProof []string `json:"inclusion_proof"`
	// A C2SP checkpoint (origin, size, base64 root, each on its own line) followed by a blank line and C2SP signed-note signature lines; the log key's line is an em dash, the key name and base64 of the 4-byte key hash and the 64-byte Ed25519 signature.
	Checkpoint string `json:"checkpoint"`
}

// PublicRecordReading: What a company has published outside its own website, read from the authorities that hold it (SEC EDGAR, the GLEIF LEI registry, DNS), beside the legal name its own site states, and the evidence tying each identifier to the domain. Served at https://api.trooth.co/scan/public-record/<domain>. Not signed: every fact carries the URL to read it again. Nothing in it grades, rates or ranks a company. docs/EVIDENCE.md in trooth-cli is the normative text.
type PublicRecordReading struct {
	// The format. One of: trooth.public-record.v1.
	Format string `json:"format"`
	// The domain read.
	Domain string `json:"domain"`
	// trooth:domain:<domain>.
	SubjectID string `json:"subject_id"`
	// When Trooth read the sources. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// What the company's own pages say about which legal entity it is.
	Site SiteRead `json:"site"`
	// Each identifier found and the evidence for and against tying it to the domain.
	Bindings []EntityBinding `json:"bindings"`
	// The SEC filer's record, or null when no filer was identified.
	Sec *SecRecord `json:"sec"`
	// The LEI record, or null when none was identified.
	Lei *LeiRecord `json:"lei"`
	// Mail-authentication records beyond SPF and DMARC, and DNSSEC.
	Dns []PublicFact `json:"dns"`
	// Each source that was not read, or did not answer, and why. A source not read is never guessed at.
	NotRead []NotRead `json:"not_read"`
	// What the reading is and is not, as a paragraph.
	Note string `json:"note"`
}

// PublicFact: One fact as its source published it, with the URL it was read from.
type PublicFact struct {
	// A stable key, source.field (for example sec.tickers, lei.jurisdiction, dns.mta_sts).
	Key string `json:"key"`
	// The fact as words.
	Label string `json:"label"`
	// The value as published: text, a number, true or false, a list of text, or null when the source states nothing.
	Value any `json:"value"`
	// Where it was read: a URL, or dns:<name> <type> for a DNS record.
	Source string `json:"source"`
}

// BindingEvidence: One piece of evidence for or against a binding.
type BindingEvidence struct {
	// For: filing_namespace_names_domain, registry_lists_domain, through_corroborated_filer (these tie the identifier to the domain), site_names_registry_name (a claim by the site), registries_agree, edgar_names_lei. Against: registry_lists_other_domain, registries_disagree, edgar_names_other_lei.
	Kind string `json:"kind"`
	// What was seen, as a sentence.
	Detail string `json:"detail"`
	// Where it was seen, or null when it follows from other evidence.
	Source *string `json:"source"`
}

// EntityBinding: A link between the domain and a legal-entity identifier, with the evidence for and against it. Nothing is asserted beyond the evidence.
type EntityBinding struct {
	// cik (SEC Central Index Key) or lei (Legal Entity Identifier). One of: cik, lei.
	Identifier string `json:"identifier"`
	// The identifier: 10 digits for a CIK, 20 characters for an LEI.
	Value string `json:"value"`
	// The stable id: trooth:cik:<10 digits> or trooth:lei:<LEI> (docs/IDS.md).
	ID string `json:"id"`
	// How the identifier was found: asked (given by the requester), ticker, site_legal_name (the legal name the site states matched exactly one listed SEC filer), edgar_lei_field, registry_name_match (exact legal name and, when the SEC gives one, the jurisdiction). One of: asked, ticker, site_legal_name, edgar_lei_field, registry_name_match.
	FoundBy string `json:"found_by"`
	// corroborated: authoritative evidence ties it to the domain (the company's own filing or the registry record names the domain). claimed_by_site: the site names this entity, and nothing authoritative ties it. registries_only: registries agree with each other, nothing ties the domain. uncorroborated: no evidence either way. contradicted: authoritative evidence points elsewhere. not_found: the registry holds no such identifier. One of: corroborated, claimed_by_site, registries_only, uncorroborated, contradicted, not_found.
	Status string `json:"status"`
	// Evidence for the binding.
	For []BindingEvidence `json:"for"`
	// Evidence against it.
	Against []BindingEvidence `json:"against"`
}

// Filing: One SEC filing, as EDGAR lists it.
type Filing struct {
	// The form type (10-K, 10-Q, 8-K, DEF 14A, 20-F ...).
	Form string `json:"form"`
	// The filing date, YYYY-MM-DD.
	Filed string `json:"filed"`
	// The period or event date, when EDGAR gives one.
	ReportDate *string `json:"report_date"`
	// For an 8-K, the item numbers it reports (for example 1.05, 4.01).
	Items []string `json:"items"`
	// EDGAR's description of the primary document.
	Description *string `json:"description"`
	// The primary document on www.sec.gov.
	URL string `json:"url"`
}

// FinancialFact: A value the company filed in XBRL, as it filed it: the latest annual (10-K, full fiscal year) value of the concept.
type FinancialFact struct {
	// The XBRL concept, taxonomy:Name.
	Tag string `json:"tag"`
	// The concept as words.
	Label string `json:"label"`
	// The value as filed.
	Value float64 `json:"value"`
	// The unit (USD).
	Unit string `json:"unit"`
	// The period start for a flow such as revenue; null for a balance such as assets.
	PeriodStart *string `json:"period_start"`
	// The period end.
	PeriodEnd string `json:"period_end"`
	// The form the value was filed in.
	Form string `json:"form"`
	// The filing date.
	Filed string `json:"filed"`
	// The accession number of that filing.
	Accession string `json:"accession"`
	// The data.sec.gov URL the value was read from.
	Source string `json:"source"`
}

// SiteRead: The legal names the company's pages state in copyright notices.
type SiteRead struct {
	// Each legal name stated, with the page.
	LegalNames []SiteName `json:"legal_names"`
	// Whether any page of the site could be read.
	Read bool `json:"read"`
	// Why no name was found, or why the site was not read (for example its robots.txt opts out).
	Reason *string `json:"reason"`
}

// SiteName: A legal name a page states.
type SiteName struct {
	// The name as written.
	Name string `json:"name"`
	// The page.
	Source string `json:"source"`
}

// SecRecord: The SEC filer's registration facts, filings and annual XBRL values.
type SecRecord struct {
	// The Central Index Key, 10 digits.
	Cik string `json:"cik"`
	// Registration facts on file with the SEC.
	Facts []PublicFact `json:"facts"`
	// The latest filing of each key form type, keyed by form.
	Latest map[string]Filing `json:"latest"`
	// 8-K filings of the last two years, newest first, at most 50.
	Events []Filing `json:"events"`
	// The earliest date the events cover.
	EventsCoverSince *string `json:"events_cover_since"`
	// 8-K filings reporting Item 1.05, a material cybersecurity incident.
	CybersecurityIncidents []Filing `json:"cybersecurity_incidents"`
	// 8-K filings reporting Item 4.01, a change of certifying accountant.
	AuditorChanges []Filing `json:"auditor_changes"`
	// 8-K filings reporting Item 4.02, non-reliance on financial statements issued before.
	NonReliance []Filing `json:"non_reliance"`
	// Forms 3, 4 and 5 filed in the last 90 days.
	InsiderFormsLast90Days int64 `json:"insider_forms_last_90_days"`
	// Annual values as filed.
	Financials []FinancialFact `json:"financials"`
}

// LeiRecord: The Legal Entity Identifier record.
type LeiRecord struct {
	// The LEI.
	Lei string `json:"lei"`
	// The record's facts.
	Facts []PublicFact `json:"facts"`
	// The direct parent the record reports, or null.
	DirectParent *Parent `json:"direct_parent"`
	// The ultimate parent the record reports, or null.
	UltimateParent *Parent `json:"ultimate_parent"`
}

// Parent: A parent entity.
type Parent struct {
	// The parent's LEI.
	Lei string `json:"lei"`
	// Its legal name.
	Name *string `json:"name"`
}

// NotRead: A source not read.
type NotRead struct {
	// The source.
	Source string `json:"source"`
	// Why.
	Reason string `json:"reason"`
}

// VerificationBundle: Everything needed to check one witness statement with no network: the statement, its evidence manifest, the key list as read, and the exact mapping bytes. Written by `trooth verify --save-bundle`; read by `trooth verify --bundle` and the SDKs. A bundle is only as fresh as its key list.
type VerificationBundle struct {
	// The bundle format. One of: trooth.verification-bundle.v1.
	Bundle string `json:"bundle"`
	// When the bundle was written. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	CreatedAt string `json:"created_at"`
	// The domain the bundle was saved for. A reader may ask about another; a statement for a different domain is a mismatch.
	Domain *string `json:"domain"`
	// The signed envelope, exactly as published.
	Statement WitnessStatement `json:"statement"`
	// The evidence manifest, or null when none was saved.
	Manifest *EvidenceManifest `json:"manifest"`
	// The key list as read when the bundle was written.
	Keys BundleKeys `json:"keys"`
	// The exact mapping bytes, or null when none were saved.
	Mapping *BundleMapping `json:"mapping"`
	// What the witness statement log answered when the bundle was written: the log key used, the receipt or null, and every correction. Absent in a bundle written before the log, or when the log was not read.
	Log *BundleLog `json:"log,omitempty"`
}

// BundleLog: The log answer, carried so the log part can be checked offline too.
type BundleLog struct {
	// The log verifier key the receipt was checked against, as a signed-note key (name+hash+key). A pinned key, when the checker has one, replaces it.
	Vkey string `json:"vkey"`
	// The receipt for the statement, or null when the log held no entry for it.
	Receipt *LogReceipt `json:"receipt"`
	// Every logged correction naming this statement, each with its own receipt.
	Corrections []LoggedCorrection `json:"corrections"`
}

// LoggedCorrection: A correction envelope and its receipt.
type LoggedCorrection struct {
	// The correction envelope: its payload is a trooth.correction.v1 document in RFC 8785 bytes.
	Statement WitnessStatement `json:"statement"`
	// The receipt for the correction.
	Receipt LogReceipt `json:"receipt"`
}

// BundleKeys: The key list as read.
type BundleKeys struct {
	// The keys array of the key list.
	Keys []PublicKey `json:"keys"`
	// When the key list was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ListReadAt *string `json:"list_read_at"`
	// Where it was read from: a URL or a file path.
	Source *string `json:"source"`
}

// BundleMapping: The mapping document, byte for byte.
type BundleMapping struct {
	// Where the bytes were read from.
	URL *string `json:"url"`
	// The digest of the carried bytes, for display. A checker hashes the bytes itself and compares with the signed digest.
	Digest string `json:"digest"`
	// The exact mapping bytes, standard base64.
	BytesBase64 string `json:"bytes_base64"`
}

// VerifyResult: The JSON document `trooth verify --json` writes, and the shape the SDKs return. The verdict is the only conclusion; everything else says how it was reached.
type VerifyResult struct {
	// The domain asked about, or the signed domain when none was asked.
	Domain *string `json:"domain"`
	// checked: v2 or v3, everything bound and matching. checked_v1: a v1 statement that checks. partially_checked: a mapping or manifest was not supplied. signature_not_trusted: malformed, invalid or untrusted key. mismatch: trusted, but a count, the domain, the mapping, the manifest or a log receipt disagrees. superseded: everything held, and a correction Trooth signed and logged withdraws or replaces the statement. One of: checked, checked_v1, partially_checked, signature_not_trusted, mismatch, superseded.
	Verdict string `json:"verdict"`
	// The statement version, or unknown. One of: v1, v2, v3, unknown.
	Version string `json:"version"`
	// The read_at the payload carries. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt *string `json:"read_at,omitempty"`
	// The reading id the payload carries.
	ReadingID *string `json:"reading_id,omitempty"`
	// trooth:statement: plus the hex SHA-256 of the exact payload bytes (docs/IDS.md).
	StatementID *string `json:"statement_id,omitempty"`
	// valid, invalid or malformed. One of: valid, invalid, malformed.
	Signature string `json:"signature"`
	// The signing key and whether it is trusted at read_at.
	Key KeyTrust `json:"key"`
	// The signed domain against the domain asked about.
	Subject Subject `json:"subject"`
	// The mapping and manifest against their signed digests.
	Binding Binding `json:"binding"`
	// Whether the signed counts agree with the signed checks.
	Counts CountCheck `json:"counts"`
	// The witness statement log part of the check. Absent when the log was not asked (offline from saved files, --no-log) or the signature was not trusted.
	Log *LogCheck `json:"log,omitempty"`
	// What a valid signature of this version shows and does not show, in words.
	Assurance string `json:"assurance"`
	// When the key list used was read. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	KeysReadAt *string `json:"keys_read_at,omitempty"`
	// Where each input came from: a URL, a file path, or null when not supplied.
	Sources map[string]*string `json:"sources,omitempty"`
}

// KeyTrust: The key decision.
type KeyTrust struct {
	// The key id the envelope names.
	Kid string `json:"kid"`
	// The lifecycle state found on the key list. One of: active, retired, compromised, revoked_unrecorded, unknown.
	State string `json:"state"`
	// Whether a valid signature from this key at this time is relied on.
	Trusted bool `json:"trusted"`
	// Why, in words.
	Reason string `json:"reason"`
}

// Subject: The subject decision.
type Subject struct {
	// The domain in the signed payload.
	Signed *string `json:"signed"`
	// The domain asked about.
	Asked *string `json:"asked"`
	// match, mismatch, or not_checked (no domain given, or the signature was not trusted). One of: match, mismatch, not_checked.
	Status string `json:"status"`
}

// Binding: The binding decision.
type Binding struct {
	// bound, partially_checked, mismatch, absent (v1 binds neither) or unchecked (signature not trusted). One of: bound, partially_checked, mismatch, absent, unchecked.
	Status string `json:"status"`
	// The mapping result. One of: match, mismatch, not_supplied, absent.
	Mapping string `json:"mapping"`
	// The manifest result. One of: match, mismatch, not_supplied, absent.
	Manifest string `json:"manifest"`
}

// LogCheck: What the log showed about the statement.
type LogCheck struct {
	// included: the receipt checks against a checkpoint signed by the log key. not_logged: the log holds no entry for it (reported, not a failure in this version). unavailable: the log could not be read. checkpoint_invalid: the checkpoint is not signed by the log key or names another log. proof_invalid: the receipt does not take this statement to the signed root. One of: included, not_logged, unavailable, checkpoint_invalid, proof_invalid.
	Status string `json:"status"`
	// The entry index the receipt names, or null.
	Index *int64 `json:"index"`
	// The signed tree size the receipt is against, or null.
	TreeSize *int64 `json:"tree_size"`
	// Why, in words.
	Reason *string `json:"reason"`
	// Each correction the log returned and whether it checked.
	Corrections []CorrectionCheck `json:"corrections"`
	// The statement id of the first correction that checked, or null.
	SupersededBy *string `json:"superseded_by"`
	// Where the log key came from: pinned in this release, --log-vkey, carried in a bundle, or served by the log.
	VkeySource *string `json:"vkey_source,omitempty"`
}

// CorrectionCheck: One correction and whether it is relied on.
type CorrectionCheck struct {
	// True when it is signed by a trusted key, in RFC 8785 bytes, names this statement, and is included in the log.
	Valid bool `json:"valid"`
	// The statement id of the correction itself.
	CorrectionStatementID *string `json:"correction_statement_id"`
	// The reason code it carries.
	Code *string `json:"code"`
	// withdrawn or replaced.
	Effect *string `json:"effect"`
	// The replacing statement id, for replaced.
	Replacement *string `json:"replacement"`
	// When Trooth issued it, as Trooth asserts. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	IssuedAt *string `json:"issued_at"`
	// Why it is or is not relied on, in words.
	Reason *string `json:"reason"`
}

// CountCheck: The count decision.
type CountCheck struct {
	// True when every identity holds.
	IdentitiesHold bool `json:"identities_hold"`
	// Each identity that does not hold, in words.
	Problems []string `json:"problems"`
}

// WitnessPayloadV1: The JSON a trooth.witness-statement.v1 payload holds. v1 binds the outcomes and counts only: no mapping, manifest, evaluator or subject scope.
type WitnessPayloadV1 struct {
	// The statement version. One of: trooth.witness-statement.v1.
	Statement string `json:"statement"`
	// The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).
	ReadingID string `json:"reading_id"`
	// The domain the reading was taken of: lowercase, no trailing dot.
	Domain string `json:"domain"`
	// When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// Every check in the reading.
	Checks []CheckV1 `json:"checks"`
	// The two counts, which must agree with the checks.
	Counts CountsV1 `json:"counts"`
}

// CheckV1: One check in a v1 reading. v1 carries no reason.
type CheckV1 struct {
	// The check id.
	ID string `json:"id"`
	// The check category.
	Category string `json:"category"`
	// probe or attest.
	Kind string `json:"kind"`
	// One of three outcomes. One of: as expected, not as expected, not read.
	Outcome string `json:"outcome"`
}

// CountsV1: The two counts a v1 payload carries.
type CountsV1 struct {
	// Checks whose outcome is not `not read`.
	Read int64 `json:"read"`
	// Checks whose outcome is `as expected`.
	AsExpected int64 `json:"as_expected"`
}

// WitnessPayloadV2: The JSON a trooth.witness-statement.v2 payload holds. Its members are signed in exactly this order with no whitespace. It binds the check mapping, the evaluator, the subject scope and the evidence manifest.
type WitnessPayloadV2 struct {
	// The statement version. One of: trooth.witness-statement.v2.
	Statement string `json:"statement"`
	// The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).
	ReadingID string `json:"reading_id"`
	// The domain the reading was taken of: lowercase, no trailing dot.
	Domain string `json:"domain"`
	// When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// What the reading covered.
	SubjectScope SubjectScope `json:"subject_scope"`
	// The check mapping, bound by digest.
	Methodology Methodology `json:"methodology"`
	// The software that took the reading.
	Evaluator Evaluator `json:"evaluator"`
	// The evidence manifest, bound by digest.
	EvidenceManifest EvidenceManifestRef `json:"evidence_manifest"`
	// Every check in the reading.
	Checks []Check `json:"checks"`
	// Counts that must agree with the checks.
	Counts Counts `json:"counts"`
}

// Check: One check in the reading and its outcome.
type Check struct {
	// The check id in the check mapping the payload names (for example S1, L2).
	ID string `json:"id"`
	// The check category in the mapping (for example security, legal, ai, ip, business).
	Category string `json:"category"`
	// How the check is taken: `probe` reads the public surface; `attest` reads something the company published about itself.
	Kind string `json:"kind"`
	// One of three outcomes. There is no fourth value and no score. One of: as expected, not as expected, not read.
	Outcome string `json:"outcome"`
	// Null when the outcome is `as expected`; otherwise why.
	Reason *CheckReason `json:"reason"`
}

// CheckReason: Why a check is not `as expected`. Present on every check whose outcome is `not read` or `not as expected`.
type CheckReason struct {
	// The reason code. source_unavailable, timeout, evaluator_limitation, carried_from_earlier_reading and check_misconfigured go with `not read`; contrary_observation and expected_item_absent go with `not as expected`. One of: source_unavailable, timeout, evaluator_limitation, carried_from_earlier_reading, check_misconfigured, contrary_observation, expected_item_absent.
	Code string `json:"code"`
	// The version of the reason vocabulary. One of: trooth.check-explanations.v1.
	Version string `json:"version"`
	// The public source the reason refers to, or null. Always null when `withheld` is true.
	SourceRef *string `json:"source_ref"`
	// True when the source behind this reason is not published (for example a private document); only a commitment to it is in the evidence manifest.
	Withheld bool `json:"withheld"`
	// Why the source is withheld. Required, non-empty, when `withheld` is true; otherwise null.
	WithheldReason *string `json:"withheld_reason"`
}

// Counts: Counts that MUST agree with the checks: read + not_read = in_reading; as_expected + not_as_expected = read; in_reading = the number of checks. They are reported apart and never added into one number.
type Counts struct {
	// Checks whose outcome is not `not read`.
	Read int64 `json:"read"`
	// Checks whose outcome is `as expected`.
	AsExpected int64 `json:"as_expected"`
	// Checks whose outcome is `not as expected`.
	NotAsExpected int64 `json:"not_as_expected"`
	// Checks whose outcome is `not read`.
	NotRead int64 `json:"not_read"`
	// All checks in the reading.
	InReading int64 `json:"in_reading"`
}

// SubjectScope: What the reading covered.
type SubjectScope struct {
	// The domain read. Equals the payload domain.
	Domain string `json:"domain"`
	// Which surface was read. `public`: only what anyone can fetch.
	Surface string `json:"surface"`
	// The number of checks in scope. Equals the number of checks listed.
	ChecksInScope int64 `json:"checks_in_scope"`
}

// Methodology: The exact check mapping the reading used, bound by digest.
type Methodology struct {
	// The name of the standard the mapping belongs to.
	Standard string `json:"standard"`
	// The mapping version.
	MappingVersion string `json:"mapping_version"`
	// Where the exact mapping bytes are served. Immutable versions live under https://trooth.co/standard/check-mapping/.
	MappingURL string `json:"mapping_url"`
	// `sha256:` plus the lowercase hex SHA-256 of the exact mapping bytes.
	MappingDigest string `json:"mapping_digest"`
}

// Evaluator: The software that took the reading.
type Evaluator struct {
	// The evaluator name.
	Name string `json:"name"`
	// The evaluator version.
	Version string `json:"version"`
}

// EvidenceManifestRef: The evidence manifest the reading binds, by digest.
type EvidenceManifestRef struct {
	// `sha256:` plus the hex SHA-256 of the canonical manifest bytes (evidence-manifest.schema.json).
	Digest string `json:"digest"`
	// The number of manifest entries.
	Entries int64 `json:"entries"`
	// How the manifest bytes are formed: entries sorted by check_id, keys check_id then source or commitment, no whitespace, UTF-8.
	Canonicalization string `json:"canonicalization"`
}

// WitnessPayloadV3: The JSON a trooth.witness-statement.v3 payload holds: the v2 content plus subject_id and signer, serialized as RFC 8785 (JCS). Every number is an integer between -(2^53 - 1) and 2^53 - 1, so every implementation produces the same bytes.
type WitnessPayloadV3 struct {
	// Every check in the reading.
	Checks []Check `json:"checks"`
	// Counts that must agree with the checks.
	Counts Counts `json:"counts"`
	// The domain the reading was taken of: lowercase, no trailing dot.
	Domain string `json:"domain"`
	// The software that took the reading.
	Evaluator Evaluator `json:"evaluator"`
	// The evidence manifest, bound by digest.
	EvidenceManifest EvidenceManifestRef `json:"evidence_manifest"`
	// The check mapping, bound by digest.
	Methodology Methodology `json:"methodology"`
	// When Trooth took the reading, as Trooth asserts it when signing. There is no independent timestamp. An ISO 8601 date-time in UTC, as written by Trooth (for example 2026-10-06T20:00:44.820Z).
	ReadAt string `json:"read_at"`
	// The id of the reading. Also usable as trooth:reading:<reading_id> (docs/IDS.md).
	ReadingID string `json:"reading_id"`
	// The signing key, inside the signed bytes.
	Signer Signer `json:"signer"`
	// The statement version. One of: trooth.witness-statement.v3.
	Statement string `json:"statement"`
	// The subject by its stable id, trooth:domain:<domain> (docs/IDS.md). MUST name the payload domain.
	SubjectID string `json:"subject_id"`
	// What the reading covered.
	SubjectScope SubjectScope `json:"subject_scope"`
}

// Signer: The signing key, named inside the signed bytes so the envelope cannot point at another key.
type Signer struct {
	// The kid of the signing key. MUST equal the envelope key_id.
	KeyID string `json:"key_id"`
	// Who signs: trooth.co. One of: trooth.co.
	Issuer string `json:"issuer"`
}

// WitnessStatement: The signed envelope Trooth publishes as `witnessStatement` on a record. The signature covers the exact UTF-8 bytes of `payload`, nothing else. How to check it: docs/VERIFY.md in github.com/troothllc/trooth-cli.
type WitnessStatement struct {
	// The signing input: the exact JSON text that was signed. Parse it to read it; never re-serialize it to check it. Its `statement` field names the version (witness-payload.v1, v2 or v3).
	Payload string `json:"payload"`
	// The Ed25519 signature over the payload bytes: `ed25519:` followed by standard base64 of the 64 signature bytes.
	Signature string `json:"signature"`
	// The `kid` of the signing key on https://api.trooth.co/public/keys. A v3 payload names the same key inside the signed bytes, at signer.key_id.
	KeyID string `json:"key_id"`
	// The signature algorithm. Always Ed25519 (RFC 8032, pure EdDSA). One of: Ed25519.
	Alg string `json:"alg"`
	// How the payload bytes were produced. `json-fixed-key-order-no-whitespace-utf8` for v1 and v2; `RFC8785` (JSON Canonicalization Scheme, integers only) for v3, where the payload MUST equal the canonical form of the JSON it holds. One of: json-fixed-key-order-no-whitespace-utf8, RFC8785.
	Canonicalization string `json:"canonicalization"`
}
