// scripts/gen-types.mjs - types for TypeScript, Python (Pydantic v2) and Go,
// generated from schemas/. The schemas are the source; these files are never
// edited by hand.
//
//   node scripts/gen-types.mjs           write the three files
//   node scripts/gen-types.mjs --check   exit 1 when any of them is not current
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const schemaDir = new URL('schemas/', root);
const files = readdirSync(schemaDir).filter((f) => f.endsWith('.json')).sort();
const schemas = Object.fromEntries(files.map((f) => [f, JSON.parse(readFileSync(new URL(f, schemaDir), 'utf8'))]));

// Every named type: each schema root and each $defs entry, by its title.
const types = [];
const byPointer = new Map();
for (const f of files) {
  const s = schemas[f];
  byPointer.set(`${f}#`, s.title);
  types.push({ name: s.title, schema: s, file: f });
  for (const [k, d] of Object.entries(s.$defs || {})) {
    byPointer.set(`${f}#/$defs/${k}`, d.title);
    types.push({ name: d.title, schema: d, file: f });
  }
}
const names = types.map((t) => t.name);
if (new Set(names).size !== names.length) throw new Error('two schema types share a title');

function refName(ref, file) {
  const [f, frag] = ref.split('#');
  const key = `${f || file}#${frag || ''}`;
  const n = byPointer.get(key);
  if (!n) throw new Error(`unresolved $ref ${ref} in ${file}`);
  return n;
}

// A small intermediate form: {k:'ref',name} {k:'str'|'int'|'bool'|'any'} {k:'lit',values}
// {k:'arr',of} {k:'map',of} {k:'null',of}
function ir(s, file) {
  if (s.$ref) return { k: 'ref', name: refName(s.$ref, file) };
  if (s.oneOf && s.oneOf.length === 2 && s.oneOf.some((b) => b.type === 'null') && !s.type) {
    return { k: 'null', of: ir(s.oneOf.find((b) => b.type !== 'null'), file) };
  }
  if (s.anyOf && !s.type) return { k: 'union', of: s.anyOf.map((b) => ir(b, file)) };
  let t = s.type;
  if (Array.isArray(t)) {
    const rest = t.filter((x) => x !== 'null');
    if (rest.length !== 1) throw new Error(`unsupported type list ${t}`);
    return t.includes('null') ? { k: 'null', of: ir({ ...s, type: rest[0] }, file) } : ir({ ...s, type: rest[0] }, file);
  }
  if ('const' in s) return { k: 'lit', values: [s.const] };
  if (s.enum) return { k: 'lit', values: s.enum };
  if (t === 'string') return { k: 'str' };
  if (t === 'integer') return { k: 'int' };
  if (t === 'number') return { k: 'num' };
  if (t === 'null') return { k: 'nul' };
  if (t === 'boolean') return { k: 'bool' };
  if (t === 'array') return { k: 'arr', of: ir(s.items, file) };
  if (t === 'object' && !s.properties) return { k: 'map', of: s.additionalProperties && typeof s.additionalProperties === 'object' ? ir(s.additionalProperties, file) : { k: 'any' } };
  throw new Error(`unsupported schema in ${file}: ${JSON.stringify(s).slice(0, 120)}`);
}

const HEAD = (c) => `${c} GENERATED by scripts/gen-types.mjs from schemas/ in github.com/troothllc/trooth-cli.\n${c} Do not edit by hand: change the schema and run \`node scripts/gen-types.mjs\`.\n`;

/* ----------------------------------------------------------- TypeScript ---- */
function ts(x) {
  switch (x.k) {
    case 'ref': return x.name;
    case 'str': return 'string';
    case 'int': return 'number';
    case 'num': return 'number';
    case 'nul': return 'null';
    case 'union': return x.of.map(ts).join(' | ');
    case 'bool': return 'boolean';
    case 'any': return 'unknown';
    case 'lit': return x.values.map((v) => JSON.stringify(v)).join(' | ');
    case 'arr': { const i = ts(x.of); return /[| ]/.test(i) ? `Array<${i}>` : `${i}[]`; }
    case 'map': return `Record<string, ${ts(x.of)}>`;
    case 'null': return `${ts(x.of)} | null`;
  }
}
const jsdoc = (d, ind = '') => `${ind}/** ${String(d).replace(/\*\//g, '*\\/')} */\n`;
let T = HEAD('//') + '\n';
for (const t of types) {
  T += jsdoc(t.schema.description);
  if (t.schema.type === 'object' && t.schema.properties) {
    const req = new Set(t.schema.required || []);
    T += `export interface ${t.name} {\n`;
    for (const [k, p] of Object.entries(t.schema.properties)) T += jsdoc(p.description, '  ') + `  ${k}${req.has(k) ? '' : '?'}: ${ts(ir(p, t.file))};\n`;
    T += '}\n\n';
  } else {
    T += `export type ${t.name} = ${ts(ir(t.schema, t.file))};\n\n`;
  }
}

/* --------------------------------------------------------------- Python ---- */
function py(x) {
  switch (x.k) {
    case 'ref': return x.name;
    case 'str': return 'str';
    case 'int': return 'int';
    case 'num': return 'float';
    case 'nul': return 'None';
    case 'union': return `Union[${x.of.map(py).join(', ')}]`;
    case 'bool': return 'bool';
    case 'any': return 'Any';
    case 'lit': return `Literal[${x.values.map((v) => JSON.stringify(v)).join(', ')}]`;
    case 'arr': return `List[${py(x.of)}]`;
    case 'map': return `Dict[str, ${py(x.of)}]`;
    case 'null': return `Optional[${py(x.of)}]`;
  }
}
const pystr = (s) => JSON.stringify(String(s));
const PY_KEYWORDS = new Set(['for', 'from', 'class', 'def', 'global', 'import', 'in', 'is', 'lambda', 'not', 'or', 'pass', 'return', 'try', 'while', 'with', 'yield', 'and', 'as', 'assert', 'break', 'continue', 'del', 'elif', 'else', 'except', 'finally', 'if', 'nonlocal', 'raise', 'None', 'True', 'False', 'async', 'await']);
let P = HEAD('#') + '"""Pydantic v2 models for the documents Trooth publishes about a witness statement."""\n\nfrom __future__ import annotations\n\nfrom typing import Any, Dict, List, Literal, Optional, Union\n\nfrom pydantic import BaseModel, ConfigDict, Field\n\n';
const models = [];
const aliases = []; // after the classes they name, before model_rebuild resolves them
for (const t of types) {
  if (t.schema.type === 'object' && t.schema.properties) {
    const req = new Set(t.schema.required || []);
    P += `\nclass ${t.name}(BaseModel):\n    ${pystr(t.schema.description)}\n\n    model_config = ConfigDict(extra="allow", populate_by_name=True)\n\n`;
    for (const [k, p] of Object.entries(t.schema.properties)) {
      const x = ir(p, t.file);
      const typ = req.has(k) ? py(x) : (x.k === 'null' ? py(x) : `Optional[${py(x)}]`);
      const kw = PY_KEYWORDS.has(k);
      P += `    ${kw ? `${k}_` : k}: ${typ} = Field(${req.has(k) ? '...' : 'None'}, ${kw ? `alias=${pystr(k)}, ` : ''}description=${pystr(p.description)})\n`;
    }
    models.push(t.name);
  } else {
    aliases.push(`\n${t.name} = ${py(ir(t.schema, t.file))}\n${'"""'}${t.schema.description}${'"""'}\n`);
  }
}
P += aliases.join('') + '\n\n' + models.map((m) => `${m}.model_rebuild()`).join('\n') + '\n';

/* ------------------------------------------------------------------- Go ---- */
const goName = (k) => k.split('_').map((w) => (['id', 'url', 'kid'].includes(w) ? (w === 'kid' ? 'Kid' : w.toUpperCase()) : w.charAt(0).toUpperCase() + w.slice(1))).join('');
function go(x) {
  switch (x.k) {
    case 'ref': return x.name;
    case 'str': case 'lit': return 'string';
    case 'int': return 'int64';
    case 'num': return 'float64';
    case 'nul': case 'union': return 'any';
    case 'bool': return 'bool';
    case 'any': return 'any';
    case 'arr': return `[]${go(x.of)}`;
    case 'map': return `map[string]${go(x.of)}`;
    case 'null': { const i = go(x.of); return i.startsWith('[]') || i.startsWith('map[') ? i : `*${i}`; }
  }
}
const gocomment = (d, ind = '') => String(d).split('\n').map((l) => `${ind}// ${l}`).join('\n') + '\n';
let G = HEAD('//') + '\npackage trooth\n\n';
for (const t of types) {
  G += gocomment(`${t.name}: ${t.schema.description}`);
  if (t.schema.type === 'object' && t.schema.properties) {
    const req = new Set(t.schema.required || []);
    G += `type ${t.name} struct {\n`;
    for (const [k, p] of Object.entries(t.schema.properties)) {
      const x = ir(p, t.file);
      let typ = go(x);
      if (!req.has(k) && !typ.startsWith('*') && !typ.startsWith('[]') && !typ.startsWith('map[')) typ = `*${typ}`;
      const lits = x.k === 'lit' ? ` One of: ${x.values.join(', ')}.` : '';
      G += gocomment(`${p.description}${lits}`, '\t') + `\t${goName(k)} ${typ} \`json:"${k}${req.has(k) ? '' : ',omitempty'}"\`\n`;
    }
    G += '}\n\n';
  } else {
    G += `type ${t.name} ${go(ir(t.schema, t.file))}\n\n`;
  }
}
G = G.replace(/\n+$/, '\n');

const outputs = [
  ['types/trooth.d.ts', T.replace(/\n+$/, '\n')],
  ['sdk/python/trooth_verify/models.py', P],
  ['sdk/go/trooth/types.go', G],
];
let stale = 0;
for (const [rel, text] of outputs) {
  const u = new URL(rel, root);
  if (process.argv.includes('--check')) {
    if (!existsSync(u) || readFileSync(u, 'utf8') !== text) { console.error(`${rel} is not current: run node scripts/gen-types.mjs`); stale++; }
  } else writeFileSync(u, text);
}
if (stale) process.exit(1);
console.log(process.argv.includes('--check') ? `types are current (${types.length} types, 3 languages)` : `wrote ${outputs.length} files (${types.length} types)`);
